force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <description>Agrupa as unidades cadastradas por empreendimento.</description>
    <label>Torre</label>
    <nameField>
        <label>Nome da torre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Blocos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoSimulador__mdt/ConfiguracaoSimulador__mdt.object-meta.xml
<CustomObject>
    <label>Configuração de Simulador de Vendas</label>
    <pluralLabel>Configuração de Simulador de Vendas</pluralLabel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EspelhoVendasController.cls
public with sharing class EspelhoVendasController {

    @AuraEnabled(cacheable=true)
    public static List<Empreendimento__c> getEmpreendimentosDisponiveis() {
        return EspelhoVendasService.getEmpreendimentosDisponiveis();
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Product2> retornarUnidadesDisponiveis(Id idEmpreendimento) {
        return EspelhoVendasService.retornarUnidadesDisponiveis(idEmpreendimento);
    }

    @AuraEnabled(cacheable=true)
    public static List<String> buscarNomesEmpreendimentos(){
       return EspelhoVendasService.buscarNomesEmpreendimentos();
    }

    @AuraEnabled(cacheable=true)
    public static List<Bloco__c> buscarBlocosPorEmpreendimento(Id idEmpreendimento){
       return EspelhoVendasService.buscarBlocosPorEmpreendimento(idEmpreendimento);
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> buscarStatusUnidades(){
       return EspelhoVendasService.buscarStatusUnidades();
    }

    @AuraEnabled(cacheable=true)
    public static List<RecordType> buscarTiposUnidades(){
       return EspelhoVendasService.buscarTiposUnidades();
    }

    @AuraEnabled(cacheable=true)
    public static List<ConfiguracaoSimulador__mdt> getConfiguracaoEspelho() {
        return EspelhoVendasService.getConfiguracaoEspelho();
    }
}