force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <description>Agrupa as unidades cadastradas por empreendimento.</description>
    <label>Torre</label>
    <nameField>
        <label>Nome da torre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Blocos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/DiasDeVencimentoDaParcela__c.field-meta.xml
<CustomField>
    <fullName>DiasDeVencimentoDaParcela__c</fullName>
    <description>Dias de vencimento para series de pagamento</description>
    <label>Dias de vencimento da parcela</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/DisponivelNoEspelho__c.field-meta.xml
<CustomField>
    <fullName>DisponivelNoEspelho__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Marque este campo para disponibilizar este empreendimento no espelho de vendas</description>
    <inlineHelpText>Marque este campo para disponibilizar este empreendimento no espelho de vendas</inlineHelpText>
    <label>Disponível no espelho</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/VagasUnidade__c.field-meta.xml
<CustomField>
    <fullName>VagasUnidade__c</fullName>
    <label>Vagas por Unidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Andar__c.field-meta.xml
<CustomField>
    <fullName>Andar__c</fullName>
    <label>Andar</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AreaTotal__c.field-meta.xml
<CustomField>
    <fullName>AreaTotal__c</fullName>
    <label>Área Total</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Coeficiente__c.field-meta.xml
<CustomField>
    <fullName>Coeficiente__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Coeficiente a ser aplicado nesta unidade para geração do valor comercial.</description>
    <inlineHelpText>Coeficiente a ser aplicado nesta unidade para geração do valor comercial.</inlineHelpText>
    <label>Coeficiente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CorDisponivel__c.field-meta.xml
<CustomField>
    <fullName>CorDisponivel__c</fullName>
    <formula>IF(ISPICKVAL(Status__c, &apos;Livre&apos;), &apos;#3CB371&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CorDisponivel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CorReservado__c.field-meta.xml
<CustomField>
    <fullName>CorReservado__c</fullName>
    <formula>IF(ISPICKVAL(Status__c, &apos;Reservada&apos;), &apos;#000000&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CorReservado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CorVendida__c.field-meta.xml
<CustomField>
    <fullName>CorVendida__c</fullName>
    <formula>IF(ISPICKVAL(Status__c, &apos;Vendida&apos;), &apos;#DC143C&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CorVendida</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MetragemDaUnidadeM__c.field-meta.xml
<CustomField>
    <fullName>MetragemDaUnidadeM__c</fullName>
    <label>Metragem da Unidade (m²)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MetragemTotal__c.field-meta.xml
<CustomField>
    <fullName>MetragemTotal__c</fullName>
    <description>Indica a metragem total da unidade, consistindo no somatório das áreas privativas coberta e descoberta.</description>
    <formula>MetragemPrivativaCoberta__c + MetragemPrivativaDescoberta__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indica a metragem total da unidade, consistindo no somatório das áreas privativas coberta e descoberta.</inlineHelpText>
    <label>Metragem total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDeSuites__c.field-meta.xml
<CustomField>
    <fullName>NumeroDeSuites__c</fullName>
    <label>Número de suítes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroQuartos__c.field-meta.xml
<CustomField>
    <fullName>NumeroQuartos__c</fullName>
    <label>Número de quartos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <formula>ValorBase__c * Coeficiente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservada</fullName>
            </value>
            <value>
                <fullName>Disponível</fullName>
                <default>true</default>
                <label>Disponível</label>
            </value>
            <value>
                <fullName>Vendida</fullName>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoProduto</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/TipoVaga__c.field-meta.xml
<CustomField>
    <fullName>TipoVaga__c</fullName>
    <label>Tipo de Vaga</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Individual</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Dupla</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Tripla</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/VagasUnidade__c.field-meta.xml
<CustomField>
    <fullName>VagasUnidade__c</fullName>
    <label>Vagas por Unidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ValorDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>ValorDaUnidade__c</fullName>
    <formula>Bloco__r.Empreendimento__r.ValorMetroQuadrado__c * MetragemDaUnidadeM__c +  ValorDeAcrescimo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor da Unidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Vaga.recordType-meta.xml
<RecordType>
    <fullName>Vaga</fullName>
    <active>true</active>
    <label>Vaga</label>
</RecordType>

force-app/main/default/classes/ProdutoSelector.cls
public class ProdutoSelector {
    private static final Id VAGA_RECORD_TYPE_ID = Schema.SObjectType.Product2.getRecordTypeInfosByName()
    .get('Vaga')
    .getRecordTypeId();




    public static Product2 getProdutosById(Id id){
        return [
            SELECT
                Empreendimento__r.Name,
                Empreendimento__r.DiasDeVencimentoDaParcela__c,
                Name, Andar__c,
                MetragemTotal__c,
                NumeroDaUnidade__c,
                NumeroQuartos__c,
                QuantidadeVagas__c,
                Bloco__r.Name,
                PrecoLista__c,
                Family
            from Product2 where id = :id
        ];
    }

    public static Map<Id, Product2> CoeficienteProdutoPorId(List<Id> produtoIds) {
        Map<Id, Product2> produtoMap = new Map<Id, Product2>([
            SELECT
                Id,
                Coeficiente__c 
            FROM Product2 
            WHERE Id IN :produtoIds
        ]);
        return produtoMap;
    }

    // MetragemDaUnidadeM__c
    // ValorDaUnidade__c

    public static Map<Id, Product2> obterUnidadesRelacionadas(Set<Id> empreendimento){
        Map<Id, Product2> unidadesMap = new Map<Id, Product2>([
            SELECT
                Id,
                Name,
                ValorDaUnidade__c,
                Coeficiente__c,
                MetragemDaUnidadeM__c,
                Empreendimento__c
            FROM Product2 
            WHERE Empreendimento__c IN :empreendimento
        ]);
        return unidadesMap;
    }

    public static List<Product2> getProductsDisponivelByIdEmpreendimento(Id idEmpreendimento) {
        return [
            SELECT 
                Id,
                Name,
                ProductCode,
                QuantidadeVagas__c,
                ValorDaUnidade__c,
                Status__c,
                Andar__c,
                CorDisponivel__c,
                Bloco__r.name,
                RecordType.name,
                CorReservado__c,
                CorVendida__c,
                MetragemDaUnidadeM__c,
                NumeroDeSuites__c,
                NumeroQuartos__c,
                Empreendimento__r.Name,
                Empreendimento__r.DiasDeVencimentoDaParcela__c,
                NumeroDaUnidade__c
            FROM Product2
            WHERE 
                Status__c != '' AND
                Empreendimento__r.DisponivelNoEspelho__c = true AND
                Empreendimento__c = :idEmpreendimento
        ];
    }

    public static List<Product2> getProductsDisponivel() {
        return [
            SELECT 
                Id,
                Name,
                ProductCode,
                QuantidadeVagas__c,
                ValorDaUnidade__c,
                Status__c,
                Andar__c,
                CorDisponivel__c,
                Bloco__r.name,
                RecordType.name,
                CorReservado__c,
                CorVendida__c,
                MetragemDaUnidadeM__c,
                NumeroDeSuites__c,
                NumeroQuartos__c,
                Empreendimento__r.Name,
                Empreendimento__r.DiasDeVencimentoDaParcela__c,
                NumeroDaUnidade__c
            FROM Product2
            WHERE 
                Status__c != '' AND
                Empreendimento__r.DisponivelNoEspelho__c = true
        ];
    }


    public static List<Product2> getVagasGaragem(Id idEmpreendimento){
        System.debug('idEmpreendimento: ' + idEmpreendimento);

        return[

        SELECT 
        id,
        Name,
        Tipo__c,
        Status__c,
        VagasUnidade__c,
        AreaTotal__c,
        TipoVaga__c,
        Empreendimento__c, 
        Empreendimento__r.VagasUnidade__c,
        RecordType.Name 
        FROM Product2 
        WHERE
            Empreendimento__c = :idEmpreendimento
        AND RecordType.Name = 'Vaga'
        ];
    }

    public static List<Product2> getQtdVagas(Id idUnidade) {
        return 
        [
            SELECT 
            id,
            Name,
            QuantidadeVagas__c
            FROM Product2 
            WHERE 
            id = :idUnidade        
        ];
    }
}