force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <description>Agrupa as unidades cadastradas por empreendimento.</description>
    <label>Torre</label>
    <nameField>
        <label>Nome da torre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Blocos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/DisponivelNoEspelho__c.field-meta.xml
<CustomField>
    <fullName>DisponivelNoEspelho__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Marque este campo para disponibilizar este empreendimento no espelho de vendas</description>
    <inlineHelpText>Marque este campo para disponibilizar este empreendimento no espelho de vendas</inlineHelpText>
    <label>Disponível no espelho</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservada</fullName>
            </value>
            <value>
                <fullName>Disponível</fullName>
                <default>true</default>
                <label>Disponível</label>
            </value>
            <value>
                <fullName>Vendida</fullName>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Unidade.recordType-meta.xml
<RecordType>
    <fullName>Unidade</fullName>
    <active>true</active>
    <label>Unidade</label>
</RecordType>

force-app/main/default/classes/EspelhoVendasServiceTest.cls
@isTest
public class EspelhoVendasServiceTest {
    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData() {
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Tower test',
            CNPJ__c = '38514518000116',
            DisponivelNoEspelho__c = true
        );

        insert empreendimento;

        Bloco__c bloco = new Bloco__c(
            Name = 'Torre A',
            Empreendimento__c = empreendimento.Id
        );

        insert bloco;

        Product2 unidade = new Product2(
            Name = 'Unidade',
            Bloco__c = bloco.Id,
            NumeroDaUnidade__c = 1,
            Status__c = 'Disponível',
            Empreendimento__c = empreendimento.Id
        );

        insert unidade;
    }


    @isTest
    static void testGetEmpreendimentosDisponiveis() {
        Test.startTest();
        List<Empreendimento__c> result = EspelhoVendasService.getEmpreendimentosDisponiveis();
        Test.stopTest();

        System.assertNotEquals(0, result.size(), 'Deve retornar uma lista de empreendimentos disponíveis');
    }

    @isTest
    static void testRetornarUnidadesDisponiveis() {
        Id idEmpreendimento = [SELECT Id FROM Empreendimento__c LIMIT 1].Id;

        Test.startTest();
        List<Product2> result = EspelhoVendasService.retornarUnidadesDisponiveis(idEmpreendimento);
        Test.stopTest();

        System.assertNotEquals(0, result.size(), 'Deve retornar uma lista de unidades disponíveis');
    }

    @isTest
    static void buscarBlocosPorEmpreendimentoTest() {
        Id idEmpreendimento = [SELECT Id FROM Empreendimento__c LIMIT 1].Id;

        Test.startTest();
        List<Bloco__c> result = EspelhoVendasService.buscarBlocosPorEmpreendimento(idEmpreendimento);
        Test.stopTest();

        System.assertNotEquals(0, result.size(), 'Deve retornar uma lista de unidades disponíveis');
    }

    @isTest
    static void testBuscarNomesEmpreendimentos() {
        Test.startTest();
        List<String> result = EspelhoVendasService.buscarNomesEmpreendimentos();
        Test.stopTest();

        System.assertNotEquals(0, result.size(), 'Deve retornar uma lista de nomes de empreendimentos');
    }

    // @isTest
    // static void testGetConfiguracaoEspelho() {
    //     Test.startTest();
    //     // Simula a recuperação de dados de metadados personalizados
    //     List<Configura_o_de__mdt> configuracoes = new List<Configura_o_de__mdt>();

    //     for (Integer i = 0; i < 3; i++) {
    //         Configura_o_de__mdt config = new Configura_o_de__mdt();
    //         config.Status__c = 'Status ' + i;
    //         config.Cor__c = 'Cor ' + i;
    //         configuracoes.add(config);
    //     }

    //     Test.setMock(Configura_o_de__mdt.class, configuracoes);
        
    //     List<Configura_o_de__mdt> result = EspelhoVendasService.getConfiguracaoEspelho();
    //     Test.stopTest();

    //     System.assertNotEquals(0, result.size(), 'Deve retornar uma lista de configurações de espelho');
    // }

    @isTest
    static void testBuscarStatusUnidades() {
        Test.startTest();
        List<String> result = EspelhoVendasService.buscarStatusUnidades();
        Test.stopTest();

        System.assertNotEquals(0, result.size(), 'Deve retornar uma lista de status de unidades');
    }

    @isTest
    static void testBuscarTiposUnidades() {
        Test.startTest();
        List<RecordType> result = EspelhoVendasService.buscarTiposUnidades();
        Test.stopTest();

        System.assertNotEquals(0, result.size(), 'Deve retornar uma lista de tipos de unidades');
    }
}