force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <description>Agrupa as unidades cadastradas por empreendimento.</description>
    <label>Torre</label>
    <nameField>
        <label>Nome da torre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Blocos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BlocoDomainTest.cls
@isTest
private class BlocoDomainTest {

    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData() {
        List<Empreendimento__c> empreendimentos = new List<Empreendimento__c>{
            new Empreendimento__c(
                Name = 'Empreendimento 1',
                CNPJ__c = '36020155000137'
            ),
            new Empreendimento__c(
                Name = 'Empreendimento 2',
                CNPJ__c = '36020155000137'
            )
        };

        insert empreendimentos;

        List<Bloco__c> blocos = new List<Bloco__c>{
            new Bloco__c(
                Name = 'Bloco 1',
                Empreendimento__c = empreendimentos.get(0).Id
            ),
            new Bloco__c(
                Name = 'Bloco 2',
                Empreendimento__c = empreendimentos.get(0).Id
            ),
            new Bloco__c(
                Name = 'Bloco 3',
                Empreendimento__c = empreendimentos.get(1).Id
            )
        };

        insert blocos;
    }

    @isTest
    private static void obterBlocosEmpreendimentoPorChaveExternaTest() {
        Id idEmpreendimento = [SELECT Id FROM Empreendimento__c WHERE Name = 'Empreendimento 1'].get(0).Id;

        Assert.isTrue(BlocoDomain.obterBlocosEmpreendimentoPorChaveExterna(idEmpreendimento).size() > 0);
    }
}