force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <description>Agrupa as unidades cadastradas por empreendimento.</description>
    <label>Torre</label>
    <nameField>
        <label>Nome da torre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/ChaveExterna__c.field-meta.xml
<CustomField>
    <fullName>ChaveExterna__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Indique a chave externa deste bloco.</description>
    <externalId>true</externalId>
    <label>Chave externa</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Blocos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bloco__c/fields/QuantidadeAndares__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeAndares__c</fullName>
    <label>Quantidade de andares</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BlocoSelectorTest.cls
@isTest
private class BlocoSelectorTest {

    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData() {
        List<Empreendimento__c> empreendimentos = new List<Empreendimento__c>{
            new Empreendimento__c(
                Name = 'Empreendimento 1',
                CNPJ__c = '42318254000100'
            ),
            new Empreendimento__c(
                Name = 'Empreendimento 2',
                CNPJ__c = '21268544000109'
            )
        };

        insert empreendimentos;

        List<Bloco__c> blocos = new List<Bloco__c>{
            new Bloco__c(
                Name = 'Bloco 1',
                Empreendimento__c = empreendimentos.get(0).Id
            ),
            new Bloco__c(
                Name = 'Bloco 2',
                Empreendimento__c = empreendimentos.get(0).Id
            ),
            new Bloco__c(
                Name = 'Bloco 3',
                Empreendimento__c = empreendimentos.get(1).Id
            )
        };

        insert blocos;
    }

    @isTest
    static void obterBlocosPorIdsEmpreendimentosTest() {
        Set<Id> idsEmpreendimentos = new Set<Id>();

        for (Empreendimento__c e : [SELECT Id FROM Empreendimento__c]) {
            idsEmpreendimentos.add(e.Id);
        }

        List<Bloco__c> blocos = [SELECT Name, QuantidadeAndares__c, ChaveExterna__c, Empreendimento__c FROM Bloco__c WHERE Empreendimento__c IN :idsEmpreendimentos];

        Assert.areEqual(blocos, BlocoSelector.obterBlocosPorIdsEmpreendimentos(idsEmpreendimentos));
        Assert.isTrue(BlocoSelector.obterBlocosPorIdsEmpreendimentos(idsEmpreendimentos).size() > 0);
    }

}