force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <description>Agrupa as unidades cadastradas por empreendimento.</description>
    <label>Torre</label>
    <nameField>
        <label>Nome da torre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Blocos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/DiasDeVencimentoDaParcela__c.field-meta.xml
<CustomField>
    <fullName>DiasDeVencimentoDaParcela__c</fullName>
    <description>Dias de vencimento para series de pagamento</description>
    <label>Dias de vencimento da parcela</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/DisponivelNoEspelho__c.field-meta.xml
<CustomField>
    <fullName>DisponivelNoEspelho__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Marque este campo para disponibilizar este empreendimento no espelho de vendas</description>
    <inlineHelpText>Marque este campo para disponibilizar este empreendimento no espelho de vendas</inlineHelpText>
    <label>Disponível no espelho</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Andar__c.field-meta.xml
<CustomField>
    <fullName>Andar__c</fullName>
    <label>Andar</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Coeficiente__c.field-meta.xml
<CustomField>
    <fullName>Coeficiente__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Coeficiente a ser aplicado nesta unidade para geração do valor comercial.</description>
    <inlineHelpText>Coeficiente a ser aplicado nesta unidade para geração do valor comercial.</inlineHelpText>
    <label>Coeficiente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CorDisponivel__c.field-meta.xml
<CustomField>
    <fullName>CorDisponivel__c</fullName>
    <formula>IF(ISPICKVAL(Status__c, &apos;Livre&apos;), &apos;#3CB371&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CorDisponivel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CorReservado__c.field-meta.xml
<CustomField>
    <fullName>CorReservado__c</fullName>
    <formula>IF(ISPICKVAL(Status__c, &apos;Reservada&apos;), &apos;#000000&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CorReservado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/CorVendida__c.field-meta.xml
<CustomField>
    <fullName>CorVendida__c</fullName>
    <formula>IF(ISPICKVAL(Status__c, &apos;Vendida&apos;), &apos;#DC143C&apos;, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CorVendida</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MetragemDaUnidadeM__c.field-meta.xml
<CustomField>
    <fullName>MetragemDaUnidadeM__c</fullName>
    <label>Metragem da Unidade (m²)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MetragemTotal__c.field-meta.xml
<CustomField>
    <fullName>MetragemTotal__c</fullName>
    <description>Indica a metragem total da unidade, consistindo no somatório das áreas privativas coberta e descoberta.</description>
    <formula>MetragemPrivativaCoberta__c + MetragemPrivativaDescoberta__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Indica a metragem total da unidade, consistindo no somatório das áreas privativas coberta e descoberta.</inlineHelpText>
    <label>Metragem total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDeSuites__c.field-meta.xml
<CustomField>
    <fullName>NumeroDeSuites__c</fullName>
    <label>Número de suítes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroQuartos__c.field-meta.xml
<CustomField>
    <fullName>NumeroQuartos__c</fullName>
    <label>Número de quartos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <formula>ValorBase__c * Coeficiente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Reservada</fullName>
            </value>
            <value>
                <fullName>Disponível</fullName>
                <default>true</default>
                <label>Disponível</label>
            </value>
            <value>
                <fullName>Vendida</fullName>
            </value>
            <value>
                <fullName>Bloqueado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ValorDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>ValorDaUnidade__c</fullName>
    <formula>Bloco__r.Empreendimento__r.ValorMetroQuadrado__c * MetragemDaUnidadeM__c +  ValorDeAcrescimo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor da Unidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Unidade.recordType-meta.xml
<RecordType>
    <fullName>Unidade</fullName>
    <active>true</active>
    <label>Unidade</label>
</RecordType>

force-app/main/default/classes/ProdutoSelectorTest.cls
@isTest
private class ProdutoSelectorTest {
    
    @TestSetup
    static void makeData() {
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Empreendimento Teste',
            CNPJ__c = '10155540000106'
        );

        insert empreendimento;

        Bloco__c bloco = new Bloco__c(
            Name = 'Torre A',
            Empreendimento__c = empreendimento.Id
        );

        insert bloco;

        insert new List<Product2> {
            new Product2(
                Name = 'Unidade',
                Bloco__c = bloco.Id,
                NumeroDaUnidade__c = 1,
                Empreendimento__c = empreendimento.Id
            ),
            new Product2(
                Name = 'Unidade1',
                Bloco__c = bloco.Id,
                NumeroDaUnidade__c = 2,
                Empreendimento__c = empreendimento.Id
            )
        };
    }


    @isTest
    private static void getProdutosByIdTest() {
        Id idUnidade = [SELECT Id FROM Product2 LIMIT 1].Id;

        Test.startTest();
        Product2 unidade = ProdutoSelector.getProdutosById(idUnidade);
        Test.stopTest();

        Assert.isNotNull(unidade);
    }

    @IsTest
    private static void CoeficienteProdutoPorIdTest() {
        Map<Id,Product2> expectedMap = new Map<Id,Product2>([
            SELECT 
                Id,
                Coeficiente__c
            FROM Product2
        ]);

        Test.startTest();
        Map<Id,Product2> actualMap = ProdutoSelector.CoeficienteProdutoPorId(new List<Id>(expectedMap.keySet()));
        Test.stopTest();

        for(Id idUnidade : expectedMap.keySet()) {
            Assert.isTrue(actualMap.containsKey(idUnidade));
            Assert.areEqual(expectedMap.get(idUnidade), actualMap.get(idUnidade));
        }
    }

    @isTest
    private static void obterUnidadesRelacionadasTest() {
        Set<Id> idsEmpreendimentos = new Map<Id,Empreendimento__c>([SELECT Id FROM Empreendimento__c]).keySet();

        Map<Id,Product2> expectedMap = new Map<Id,Product2>([
            SELECT
                Id,
                Name,
                PrecoLista__c,
                Coeficiente__c,
                MetragemTotal__c,
                Empreendimento__c
            FROM Product2 
            WHERE Empreendimento__c IN :idsEmpreendimentos
        ]);

        Test.startTest();
        Map<Id,Product2> actualMap = ProdutoSelector.obterUnidadesRelacionadas(idsEmpreendimentos);
        Test.stopTest();

        for(Id idUnidade : expectedMap.keySet()) {
            Assert.isTrue(actualMap.containsKey(idUnidade));
            Assert.areEqual(expectedMap.get(idUnidade), actualMap.get(idUnidade));
        }
    }

    @isTest
    private static void getProductsDisponivelByIdEmpreendimentoTest() {
        Id idEmpreendimento = [SELECT Id FROM Empreendimento__c LIMIT 1].Id;

        List<Product2> expectedList = [
            SELECT 
                Id,
                Name,
                ProductCode,
                ValorDaUnidade__c,
                Status__c,
                Andar__c,
                CorDisponivel__c,
                Bloco__r.name,
                RecordType.name,
                CorReservado__c,
                CorVendida__c,
                MetragemDaUnidadeM__c,
                NumeroDeSuites__c,
                NumeroQuartos__c,
                Empreendimento__r.Name,
                Empreendimento__r.DiasDeVencimentoDaParcela__c,
                NumeroDaUnidade__c
            FROM Product2
            WHERE 
                Status__c != '' AND
                Empreendimento__r.DisponivelNoEspelho__c = true AND
                Empreendimento__c = :idEmpreendimento
        ];

        Test.startTest();
        List<Product2> actualList = ProdutoSelector.getProductsDisponivelByIdEmpreendimento(idEmpreendimento);
        Test.stopTest();

        Assert.areEqual(expectedList, actualList);
    }
}