force-app/main/default/objects/UnidadeTabelaVendas__c/UnidadeTabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Entrada de Preço</label>
    <nameField>
        <label>Nome de Unidade da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entrada de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/CoeficienteTabela__c.field-meta.xml
<CustomField>
    <fullName>CoeficienteTabela__c</fullName>
    <label>Coeficiente na Tabela</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/MetragemUnidade__c.field-meta.xml
<CustomField>
    <fullName>MetragemUnidade__c</fullName>
    <label>Metragem da Unidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipName>Unidades_da_Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entrada de Preços</relationshipLabel>
    <relationshipName>UnidadesTabelaVendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/ValorVenda__c.field-meta.xml
<CustomField>
    <fullName>ValorVenda__c</fullName>
    <formula>(
    (PrecoLista__c  * CoeficienteTabela__c) -
    IF(ISBLANK(TabelaVenda__r.ValorDeAcrescimo__c), 0.0, TabelaVenda__r.ValorDeAcrescimo__c)
) * 
IF(ISBLANK(TabelaVenda__r.PercentualDeAcrescimo__c), 1.0, 1 + TabelaVenda__r.PercentualDeAcrescimo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor de venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/UnidadeTabelaSelector.cls
public class UnidadeTabelaSelector {
    public static List<UnidadeTabelaVendas__c> obterUnidadeTabelaPorId(Id tabelaVendaRelacionada){
        return [
            SELECT
            Id,
            TabelaVenda__c,
            PrecoLista__c
            FROM UnidadeTabelaVendas__c 
            WHERE TabelaVenda__c = :tabelaVendaRelacionada
        ];
    }

    public static Map<Id, UnidadeTabelaVendas__c> obterUnidadesTabelaExistentes(set<Id> tabelavendasIds){
        Map<Id,UnidadeTabelaVendas__c> unidadesTabelaMap = new Map<Id, UnidadeTabelaVendas__c>([
            SELECT Id, Name, PrecoLista__c, CoeficienteTabela__c, MetragemUnidade__c, Unidade__c, TabelaVenda__c
            FROM UnidadeTabelaVendas__c
            WHERE TabelaVenda__c IN :tabelaVendasIds
        ]);
        return unidadesTabelaMap;
    }

    public static UnidadeTabelaVendas__c obterUnidadesTabelaPorIdUnidade(Id idUnidade){
        return [SELECT id, ValorVenda__c, Unidade__c from UnidadeTabelaVendas__c where Unidade__c =: idUnidade limit 1];
    }
}