force-app/main/default/objects/Quote/fields/ComissaoConformeTabela__c.field-meta.xml
<CustomField>
    <fullName>ComissaoConformeTabela__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comissão Conforme Tabela</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/DescontoConformeTabela__c.field-meta.xml
<CustomField>
    <fullName>DescontoConformeTabela__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Desconto Conforme Tabela</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <label>Preço de Lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/SeriePagamentos__c.object-meta.xml
<CustomObject>
    <label>Série de Pagamentos</label>
    <nameField>
        <label>Nome de Série de Pagamentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series de Pagamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SeriePagamentos__c/fields/Cotacao__c.field-meta.xml
<CustomField>
    <fullName>Cotacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotação</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Series de Pagamentos</relationshipLabel>
    <relationshipName>Series_de_Pagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/DiaVencimentoParcela__c.field-meta.xml
<CustomField>
    <fullName>DiaVencimentoParcela__c</fullName>
    <label>Dia de Vencimento da Parcela</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/InicioPagamento__c.field-meta.xml
<CustomField>
    <fullName>InicioPagamento__c</fullName>
    <inlineHelpText>Numeral, em meses. Se for &quot;0&quot;, significa hoje. Se for &quot;40&quot;, significa &quot;daqui a 40 meses&quot; a partir de hoje</inlineHelpText>
    <label>Início de Pagamento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/QuantidadeParcelas__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeParcelas__c</fullName>
    <label>Quantidade de Parcelas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/TipoCondicao__c.field-meta.xml
<CustomField>
    <fullName>TipoCondicao__c</fullName>
    <label>Tipo de Condição</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TiposCondicoes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/ValorTotal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotal__c</fullName>
    <label>Valor total (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/ValorTotalNominal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotalNominal__c</fullName>
    <label>Valor Total Nominal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/recordTypes/SerieCotacao.recordType-meta.xml
<RecordType>
    <fullName>SerieCotacao</fullName>
    <active>true</active>
    <label>Série Cotação</label>
</RecordType>

force-app/main/default/globalValueSets/TiposCondicoes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ato</fullName>
    </customValue>
    <customValue>
        <fullName>Sinal</fullName>
    </customValue>
    <customValue>
        <fullName>Mensais</fullName>
    </customValue>
    <customValue>
        <fullName>Semestrais</fullName>
    </customValue>
    <customValue>
        <fullName>Anuais</fullName>
    </customValue>
    <customValue>
        <fullName>Única</fullName>
    </customValue>
    <customValue>
        <fullName>Financiamento</fullName>
    </customValue>
    <customValue>
        <fullName>Periódica</fullName>
    </customValue>
    <customValue>
        <fullName>Bimestral</fullName>
    </customValue>
    <customValue>
        <fullName>Trimestral</fullName>
    </customValue>
    <masterLabel>Tipos de Condições</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteService.cls
public with sharing class QuoteService {
    private static final Id SERIE_RECORD_TYPE_ID = Schema.SObjectType.SeriePagamentos__c.getRecordTypeInfosByDeveloperName()
    .get('SerieCotacao')
    .getRecordTypeId();

    public static void handleConcluirSimulacao(List<SeriePagamentos__c> series, List<QuoteLineItem> qlis, Id idCotacao, Boolean isParaAprovacao, Double valorUnidadeTabela) {

        Set<Id> productIds = new Set<Id>();
        for (QuoteLineItem qli : qlis) {
            productIds.add(qli.Product2Id);
        }

        Map<Id, Id> pbEntryProductMap = new Map<Id, Id>();
        for (PricebookEntry pbEntry : [SELECT Id, Product2Id FROM PricebookEntry WHERE Product2Id IN :productIds]) {
            pbEntryProductMap.put(pbEntry.Product2Id, pbEntry.Id);
        }

        for (QuoteLineItem qli : qlis) {
            qli.PricebookEntryId = pbEntryProductMap.get(qli.Product2Id);
        }
        
        for (SeriePagamentos__c serie : series) {
            serie.RecordTypeId = SERIE_RECORD_TYPE_ID;
        }

        insert qlis;
        insert series;

        Quote quoteToUpdate = new Quote(
            Id = idCotacao, 
            Status = 'Em Aprovação', 
            PrecoLista__c = valorUnidadeTabela,
            ComissaoConformeTabela__c = true, 
            DescontoConformeTabela__c = !isParaAprovacao
        );
        
        update quoteToUpdate;
    }

    public static List<QuoteLineItem> criarQuoteLineItems(List<QuoteLineItem> qlis) {
        insert qlis;
        return qlis;
    }

    public static List<SeriePagamentos__c> buscarSeriesPorCotacao(Id idCotacao) {
        return [SELECT 
            Id,
            TipoCondicao__c,
            InicioPagamento__c,
            QuantidadeParcelas__c,
            ValorTotal__c,
            ValorTotalNominal__c,
            DiaVencimentoParcela__c
        FROM SeriePagamentos__c WHERE Cotacao__c = :idCotacao];
    }
}