force-app/main/default/objects/Documento__c/Documento__c.object-meta.xml
<CustomObject>
    <label>Documento</label>
    <nameField>
        <label>Nome do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Documento__c/fields/Entregue__c.field-meta.xml
<CustomField>
    <fullName>Entregue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Entregue?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status Aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Entregue</fullName>
            </value>
            <value>
                <fullName>Pendente de Análise</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Vencido</fullName>
                <label>Expirada</label>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EntregaDocumento.cls
public class EntregaDocumento {
    public static void AtualizarDocumentoEntregue(List<ContentDocumentLink> linksDocumentos) {
        List<Documento__c> documentosAtualizar = new List<Documento__c>();

        for(ContentDocumentLink linkDocumento : linksDocumentos) {
            if(String.valueOf(linkDocumento.LinkedEntityId.getsobjecttype()) == 'Documento__c') {
                Documento__c documento = DocumentoSelector.obterDocumentoPorId(linkDocumento.LinkedEntityId);
                documento.Entregue__c = true;
                documento.StatusAprovacao__c = 'Entregue';
    
                documentosAtualizar.add(documento);
            }
        }

        if(!documentosAtualizar.isEmpty()) {
            update documentosAtualizar;
        }
    }
}