force-app/main/default/objects/Documento__c/Documento__c.object-meta.xml
<CustomObject>
    <label>Documento</label>
    <nameField>
        <label>Nome do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Documento__c/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status Aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Entregue</fullName>
            </value>
            <value>
                <fullName>Pendente de Análise</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Vencido</fullName>
                <label>Expirada</label>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Documento__c/fields/StatusIcone__c.field-meta.xml
<CustomField>
    <fullName>StatusIcone__c</fullName>
    <label>Ícone de status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IconeStatusDocumentoService.cls
public class IconeStatusDocumentoService {
    static Map<String, String> mapStatusIconeStatus = new Map<String, String> {
        'Não Entregue' => '/resource/NaoEntregueIconResource',
        'Entregue' => '/resource/EntregueIconResource',
        'Reprovado' => '/resource/ReprovadoIconResource',
        'Em Análise' => '/resource/EmAnaliseIconResource',
        'Vencido' => '/resource/ReprovadoIconResource',
        'Aprovado' => '/resource/AprovadoIconResource'
    };

    public static void atualizarIconeStatusDocumento(List<Documento__c> documentosNovos, Map<Id, Documento__c> documentosAntigos) {
        for(Documento__c documento : documentosNovos) {
            if(documento.StatusAprovacao__c != documentosAntigos.get(documento.Id).StatusAprovacao__c) {
                documento.StatusIcone__c = mapStatusIconeStatus.get(documento.StatusAprovacao__c);
            }
        }
    }
}