force-app/main/default/objects/SeriePagamentos__c/SeriePagamentos__c.object-meta.xml
<CustomObject>
    <label>Série de Pagamentos</label>
    <nameField>
        <label>Nome de Série de Pagamentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series de Pagamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SeriePagamentos__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Series de Pagamentos</relationshipLabel>
    <relationshipName>SeriesPagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Clonado__c.field-meta.xml
<CustomField>
    <fullName>Clonado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clonado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/ClonadoPor__c.field-meta.xml
<CustomField>
    <fullName>ClonadoPor__c</fullName>
    <label>Clonado Por</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/DataDaClonagem__c.field-meta.xml
<CustomField>
    <fullName>DataDaClonagem__c</fullName>
    <label>Data da Clonagem</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/OrigemTabelaDeVenda__c.field-meta.xml
<CustomField>
    <fullName>OrigemTabelaDeVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Origem Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>TabelaDeVendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PercentualDeAcrescimo__c.field-meta.xml
<CustomField>
    <fullName>PercentualDeAcrescimo__c</fullName>
    <inlineHelpText>Percentual (%) que será acrescido no valor das Unidades</inlineHelpText>
    <label>Percentual de acréscimo (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/VigenciaFim__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFim__c</fullName>
    <label>Vigência fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/VigenciaInicio__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicio__c</fullName>
    <label>Vigência início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TabelaVendaService.cls
public class TabelaVendaService {
    public static Id clonarTabela(Map<String,String> tabelaClone, Id idTabela) {
        System.debug(tabelaClone);

        TabelaVendas__c tabelaOriginal = TabelaVendasSelector.getTabelaVendasPorId(idTabela);
            
        if (tabelaOriginal == null) {
           throw new AuraHandledException('Tabela de Vendas original não encontrada.');
        }
        
        TabelaVendas__c tabelaVendaClone = tabelaOriginal.clone(false, true, false, false);
        
            tabelaVendaClone.Name = tabelaClone.get('Name');
            tabelaVendaClone.VigenciaInicio__c = Date.valueOf(tabelaClone.get('VigenciaInicio__c'));
            tabelaVendaClone.VigenciaFim__c = Date.valueOf(tabelaClone.get('VigenciaFim__c'));
            tabelaVendaClone.PercentualDeAcrescimo__c = tabelaClone.get('PercentualDeAcrescimo__c') != null ? Decimal.valueOf(tabelaClone.get('PercentualDeAcrescimo__c')) : 0;        
            tabelaVendaClone.Clonado__c = true;
            tabelaVendaClone.Ativo__c = false;
            tabelaVendaClone.ClonadoPor__c = UserInfo.getName();
            tabelaVendaClone.OrigemTabelaDeVenda__c = tabelaOriginal.Id;
            tabelaVendaClone.DataDaClonagem__c = Date.today();
       
        List<TabelaVendas__c> tabelasParaValidacao = new List<TabelaVendas__c>{ tabelaVendaClone };

            TabelaVendasHelper.validarTipoVenda(tabelasParaValidacao);
            TabelaVendasHelper.validarTabelaIguais(tabelasParaValidacao, true);
       

            insert tabelaVendaClone;
       

            clonarSeries(idTabela, tabelaVendaClone.Id);
         
        return tabelaVendaClone.Id;
    }

    private static void clonarSeries(Id idTabelaOriginal, Id idTabelaClonada) {
        List<SeriePagamentos__c> seriesOriginais = TabelaVendasSelector.getSeriesPagamentosPorTabela(idTabelaOriginal);
        System.debug(seriesOriginais);
        
        List<SeriePagamentos__c> seriesClonadas = new List<SeriePagamentos__c>();
        
        for (SeriePagamentos__c serieOriginal : seriesOriginais) {
            SeriePagamentos__c serieClonada = serieOriginal.clone(false, true, false, false);
        
            serieClonada.TabelaVenda__c = idTabelaClonada;
            seriesClonadas.add(serieClonada);
        }
        
        insert seriesClonadas;

        
    }
}