force-app/main/default/objects/SeriePagamentos__c/SeriePagamentos__c.object-meta.xml
<CustomObject>
    <label>Série de Pagamentos</label>
    <nameField>
        <label>Nome de Série de Pagamentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series de Pagamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SeriePagamentos__c/fields/ValorTotalNominal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotalNominal__c</fullName>
    <label>Valor Total Nominal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/UnidadeTabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Entrada de Preço</label>
    <nameField>
        <label>Nome de Unidade da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entrada de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/MetragemUnidade__c.field-meta.xml
<CustomField>
    <fullName>MetragemUnidade__c</fullName>
    <label>Metragem da Unidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/ValorMetroQuadradoTabela__c.field-meta.xml
<CustomField>
    <fullName>ValorMetroQuadradoTabela__c</fullName>
    <formula>ValorVenda__c /  MetragemUnidade__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor (m2)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/ValorMinimoVenda__c.field-meta.xml
<CustomField>
    <fullName>ValorMinimoVenda__c</fullName>
    <formula>(
(PrecoLista__c * CoeficienteTabela__c) -
IF(ISBLANK(TabelaVenda__r.DescontoNominalMoeda__c), 0.0, TabelaVenda__r.DescontoNominalMoeda__c)
) *
IF(ISBLANK(TabelaVenda__r.DescontoNominalPorcentagem__c), 1.0, 1 - TabelaVenda__r.DescontoNominalPorcentagem__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Mínimo de Venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/ValorVenda__c.field-meta.xml
<CustomField>
    <fullName>ValorVenda__c</fullName>
    <formula>(
    (PrecoLista__c  * CoeficienteTabela__c) -
    IF(ISBLANK(TabelaVenda__r.ValorDeAcrescimo__c), 0.0, TabelaVenda__r.ValorDeAcrescimo__c)
) * 
IF(ISBLANK(TabelaVenda__r.PercentualDeAcrescimo__c), 1.0, 1 + TabelaVenda__r.PercentualDeAcrescimo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor de venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ComparativoService.cls
public class ComparativoService {
    
    public class ComparacaoResultado {
        @AuraEnabled
        public String item { get; set; } 
        @AuraEnabled
        public Double valorTabela { get; set; }
        @AuraEnabled
        public Double valorProposta { get; set; }
        @AuraEnabled
        public Double diferenca { get; set; }
    }

    public static List<ComparacaoResultado> calcularComparacao(Id unidadeId, Id tabelaId, List<SeriePagamentos__c> proposta) {
        TabelaVendas__c tabelaVenda = TabelaVendasSelector.obterTabelasRelacionadas(tabelaId);

        UnidadeTabelaVendas__c unidadeTabela = UnidadeTabelaSelector.obterEntradaPrecoPorId(unidadeId);
        Decimal valorProposta = 0.0;
        for (SeriePagamentos__c serie : proposta) {
            valorProposta += serie.ValorTotalNominal__c;
        }   
        
        List<UnidadeTabelaVendas__c> tabelaVendaUnidades = TabelaVendasSelector.obterUnidadeTabelasPorId(tabelaId);
        List<ComparacaoResultado> resultados = new List<ComparacaoResultado>();

        ComparacaoResultado valorM2 = new ComparacaoResultado();
        valorM2.item = 'Valor do m²';
        valorM2.valorTabela = unidadeTabela.ValorMetroQuadradoTabela__c;
        valorM2.valorProposta = valorProposta / unidadeTabela.MetragemUnidade__c;
        valorM2.diferenca =  valorM2.valorProposta - valorM2.valorTabela;
        resultados.add(valorM2);
        
        ComparacaoResultado descontoNominal = new ComparacaoResultado();
        descontoNominal.item = 'Desconto Nominal';
        descontoNominal.valorTabela = unidadeTabela.ValorVenda__c - unidadeTabela.ValorMinimoVenda__c;
        descontoNominal.valorProposta = unidadeTabela.ValorVenda__c - valorProposta;
        descontoNominal.diferenca =  descontoNominal.valorProposta - descontoNominal.valorTabela;
        resultados.add(descontoNominal);
        
        ComparacaoResultado descontoPercentual = new ComparacaoResultado();
        descontoPercentual.item = 'Desconto Percentual';
        descontoPercentual.valorTabela = descontoNominal.valorTabela * 100 / unidadeTabela.ValorVenda__c; 
        descontoPercentual.valorProposta = descontoNominal.valorProposta * 100 / valorProposta;
        descontoPercentual.diferenca = descontoPercentual.valorProposta - descontoPercentual.valorTabela ;
        resultados.add(descontoPercentual);

        return resultados;
    }
}