force-app/main/default/objects/SeriePagamentos__c/SeriePagamentos__c.object-meta.xml
<CustomObject>
    <label>Série de Pagamentos</label>
    <nameField>
        <label>Nome de Série de Pagamentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series de Pagamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SeriePagamentos__c/fields/Cotacao__c.field-meta.xml
<CustomField>
    <fullName>Cotacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotação</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Series de Pagamentos</relationshipLabel>
    <relationshipName>Series_de_Pagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Series de Pagamentos</relationshipLabel>
    <relationshipName>SeriesPagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Cotacao__c.field-meta.xml
<CustomField>
    <fullName>Cotacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotação</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcela__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcela__c</fullName>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Mensal</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Semestral</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Anual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcelaPos__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcelaPos__c</fullName>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TabelaVendasService.cls
public with sharing class TabelaVendasService {
    public static Id criarTabelaDaSimulacao(List<SeriePagamentos__c> seriesProposta, Id idCotacao, String nomeCotacao, TabelaVendas__c tabelaSelecionada){
        
        System.debug(idCotacao);
        System.debug(nomeCotacao);

        Integer periocidadeParcelaPos = Integer.valueOf(tabelaSelecionada.PeriodicidadeParcelaPos__c);
        // Integer periodicidadeParcela = Integer.valueOf(tabelaSelecionada.PeriodicidadeParcela__c);
        Integer periodicidadeParcela = 0;
        System.debug('tabela'+tabelaSelecionada);
        system.debug('PeriocidaPP = '+periocidadeParcelaPos);
        system.debug('PeriocidaP = '+periodicidadeParcela);

        if(periocidadeParcelaPos != 1 && periocidadeParcelaPos != 6 && periocidadeParcelaPos != 12) {
            periocidadeParcelaPos = 1;
        }
        
        if(periodicidadeParcela != 1 && periodicidadeParcela != 6 && periodicidadeParcela != 12) {
            periodicidadeParcela = 1;
        }

        tabelaVendas__c tabelaVendaCotacao = tabelaVendasSelector.buscarTabelaPorIdCotacao(idCotacao);
        
            if(tabelaVendaCotacao != null){
                List<SeriePagamentos__c> seriesTabelaCotacao = SeriePagamentoSelector.obterSeriePorIdTabelaVendas(tabelaVendaCotacao.Id);

                DELETE seriesTabelaCotacao;
                DELETE tabelaVendaCotacao;
            }
        RecordType recordType = [SELECT id, name FROM RecordType WHERE SObjectType = 'TabelaVendas__c' AND Name = 'Tabela de Proposta' LIMIT 1];

        TabelaVendas__c novaTabelaCotacao = new TabelaVendas__c();
        novaTabelaCotacao.Name = 'Simulação ' + nomeCotacao;
        novaTabelaCotacao.Cotacao__c = idCotacao;
        novaTabelaCotacao.RecordTypeId = recordType.Id;
        novaTabelaCotacao.PeriodicidadeParcelaPos__c = periocidadeParcelaPos;
        //novaTabelaCotacao.PeriodicidadeParcela__c = periodicidadeParcela;
        
        INSERT novaTabelaCotacao;

        for (SeriePagamentos__c serie : seriesProposta) {
            serie.TabelaVenda__c = novaTabelaCotacao.Id;
        }
        System.debug(seriesProposta);

        INSERT seriesProposta;

        return novaTabelaCotacao.Id;
    }
}