force-app/main/default/objects/SeriePagamentos__c/SeriePagamentos__c.object-meta.xml
<CustomObject>
    <label>Série de Pagamentos</label>
    <nameField>
        <label>Nome de Série de Pagamentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series de Pagamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SeriePagamentos__c/fields/InicioPagamento__c.field-meta.xml
<CustomField>
    <fullName>InicioPagamento__c</fullName>
    <inlineHelpText>Numeral, em meses. Se for &quot;0&quot;, significa hoje. Se for &quot;40&quot;, significa &quot;daqui a 40 meses&quot; a partir de hoje</inlineHelpText>
    <label>Início de Pagamento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/QuantidadeParcelas__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeParcelas__c</fullName>
    <label>Quantidade de Parcelas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/Restante__c.field-meta.xml
<CustomField>
    <fullName>Restante__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Marca o item que completará 100% do valor da venda.</inlineHelpText>
    <label>Restante</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Series de Pagamentos</relationshipLabel>
    <relationshipName>SeriesPagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/TipoCondicao__c.field-meta.xml
<CustomField>
    <fullName>TipoCondicao__c</fullName>
    <label>Tipo de Condição</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TiposCondicoes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/ValorTotal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotal__c</fullName>
    <label>Valor total (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/UnidadeTabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Entrada de Preço</label>
    <nameField>
        <label>Nome de Unidade da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entrada de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipName>Unidades_da_Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/TiposCondicoes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ato</fullName>
    </customValue>
    <customValue>
        <fullName>Sinal</fullName>
    </customValue>
    <customValue>
        <fullName>Mensais</fullName>
    </customValue>
    <customValue>
        <fullName>Semestrais</fullName>
    </customValue>
    <customValue>
        <fullName>Anuais</fullName>
    </customValue>
    <customValue>
        <fullName>Única</fullName>
    </customValue>
    <customValue>
        <fullName>Financiamento</fullName>
    </customValue>
    <customValue>
        <fullName>Periódica</fullName>
    </customValue>
    <customValue>
        <fullName>Bimestral</fullName>
    </customValue>
    <customValue>
        <fullName>Trimestral</fullName>
    </customValue>
    <masterLabel>Tipos de Condições</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SeriePagamentosServiceTest.cls
@isTest
public with sharing class SeriePagamentosServiceTest {
    
    @TestSetup
    static void makeData(){
        TabelaVendas__c tabela = TestDataFactory.gerarTabelaVendas();
        insert tabela;

        SeriePagamentos__c seriesTabela = TestDataFactory.gerarSeriePagamento(tabela.Id);
        seriesTabela.Restante__c = true;
        insert seriesTabela;

        UnidadeTabelaVendas__c unidadeTabela = TestDataFactory.gerarUnidadeTabelaVendas(tabela.id);
        insert unidadeTabela;     
    }

    @isTest
    public static void testSetValorRealVPLTabelaVendas(){
        TabelaVendas__c tabela = [SELECT id FROM TabelaVendas__c LIMIT 1];
        Test.startTest();
        Map<String, Decimal> retornoValoresReaisVPL = SeriePagamentosService.setValorRealVPLTabelaVendas(tabela.Id);
        Test.stopTest();

        Assert.areEqual(3000.00, retornoValoresReaisVPL.get('valorVPL'), 'Os valores devem ser iguais.');
    }

    @isTest
    public static void testSetValorRealPropostaCliente(){
        TabelaVendas__c tabela = [SELECT id FROM TabelaVendas__c LIMIT 1];

        SeriePagamentosService.ObjetoSerie objetoSerie = new SeriePagamentosService.ObjetoSerie();
        objetoSerie.id = 'serie01';
        objetoSerie.valorTotal = 1;
        objetoSerie.quantidadeParcelas = 1;
        objetoSerie.inicioPagamento = 1;
        objetoSerie.tabelaVenda = tabela.Id;
        objetoSerie.aposHabiteSe = false;

        Test.startTest();
        Map<String, Decimal> retornoValoresReaisProposta = SeriePagamentosService.setValorRealPropostaCliente(tabela.Id,new List<SeriePagamentosService.ObjetoSerie>{objetoSerie}, 300000);
        Test.stopTest();

        Assert.areEqual(3000.00, retornoValoresReaisProposta.get('valorVPL'), 'Os valores devem ser iguais.');
  
    }

    @isTest
    public static void testInsertSeriePagamentos(){
        Test.startTest();
        
        SeriePagamentos__c serie = new SeriePagamentos__c(
            Name = 'Teste',
            InicioPagamento__c = 1,
            QuantidadeParcelas__c = 1,
            ValorTotal__c = 1,
            TabelaVenda__c = [SELECT Id FROM TabelaVendas__c LIMIT 1].Id,
            TipoCondicao__c = 'Ato',
            Restante__c = true
        );
        
        Database.SaveResult resultInsert = Database.insert(serie, false);
        System.assert(resultInsert.isSuccess());
        
        Test.stopTest();
    }
}