force-app/main/default/objects/Account/recordTypes/PessoaJuridicaPJ.recordType-meta.xml
<RecordType>
    <fullName>PessoaJuridicaPJ</fullName>
    <active>true</active>
    <label>Pessoa Jurídica (PJ)</label>
</RecordType>

force-app/main/default/objects/Comprador__c/Comprador__c.object-meta.xml
<CustomObject>
    <label>Comprador</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Comprador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compradores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comprador__c/fields/CompradorPrincipal__c.field-meta.xml
<CustomField>
    <fullName>CompradorPrincipal__c</fullName>
    <label>Comprador principal?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Jurídica (PJ), Pessoa Física (PF), Imobiliária</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/PorcentagemDeParticipacao__c.field-meta.xml
<CustomField>
    <fullName>PorcentagemDeParticipacao__c</fullName>
    <label>% de participação</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/TipoParticipante__c.field-meta.xml
<CustomField>
    <fullName>TipoParticipante__c</fullName>
    <label>Tipo de Participante</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprador</fullName>
            </value>
            <value>
                <fullName>Sócio</fullName>
            </value>
            <value>
                <fullName>Fiador</fullName>
            </value>
            <value>
                <fullName>Procurador</fullName>
            </value>
            <value>
                <fullName>Cônjuge/Companheiro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Comprador__c/recordTypes/Comprador.recordType-meta.xml
<RecordType>
    <fullName>Comprador</fullName>
    <active>true</active>
    <label>Comprador</label>
</RecordType>

force-app/main/default/classes/CompradorHelper.cls
public with sharing class CompradorHelper {
    
    public static void getTotalPercent(List<Comprador__c> compradores) {
        if (compradores == null || compradores.isEmpty()) {
            return;
        }
        
        Set<Id> oportunidadeIds = new Set<Id>();
        for (Comprador__c participante : compradores) {
            if (participante.Oportunidade__c != null) {
                oportunidadeIds.add(participante.Oportunidade__c);
            }
        }
        
        Map<Id, Decimal> opportunityPercentages = new Map<Id, Decimal>();
        Map<Id, Comprador__c> mapExistingTipoParticipante = new Map<Id, Comprador__c>();
        List<Comprador__c> allTipoParticipantes = [
            SELECT Oportunidade__c, PorcentagemDeParticipacao__c
            FROM Comprador__c
            WHERE Oportunidade__c IN :oportunidadeIds
        ];
        
        for (Comprador__c tipoParticipante : allTipoParticipantes) {
            if (tipoParticipante.Oportunidade__c != null) {
                Decimal currentPercentage = tipoParticipante.PorcentagemDeParticipacao__c != null ? tipoParticipante.PorcentagemDeParticipacao__c : 0;
                if (opportunityPercentages.containsKey(tipoParticipante.Oportunidade__c)) {
                    opportunityPercentages.put(tipoParticipante.Oportunidade__c, opportunityPercentages.get(tipoParticipante.Oportunidade__c) + currentPercentage);
                } else {
                    opportunityPercentages.put(tipoParticipante.Oportunidade__c, currentPercentage);
                }
            }
            mapExistingTipoParticipante.put(tipoParticipante.Id, tipoParticipante);
        }
        
        for (Comprador__c participante : compradores) {
            if (participante.Oportunidade__c != null && opportunityPercentages.containsKey(participante.Oportunidade__c)) {
                Decimal total = opportunityPercentages.get(participante.Oportunidade__c);
                
                Decimal currentParticipation = participante.PorcentagemDeParticipacao__c != null ? participante.PorcentagemDeParticipacao__c : 0;
                
                if (mapExistingTipoParticipante.containsKey(participante.Id)) {
                    total -= mapExistingTipoParticipante.get(participante.Id).PorcentagemDeParticipacao__c != null ? mapExistingTipoParticipante.get(participante.Id).PorcentagemDeParticipacao__c : 0;
                }
                
                Decimal newTotal = total + currentParticipation;
                
                if (newTotal > 100) {
                    participante.addError('O Total de participação não pode exceder 100%');
                } else {
                    opportunityPercentages.put(participante.Oportunidade__c, newTotal);
                }
            }
        }
    }
    
    public static void validarCompradorDuplicado(List<Comprador__c> compradores) {
        if (compradores == null || compradores.isEmpty()) {
            return;
        }

        for (Comprador__c comprador : compradores) {
            if ((comprador.Conta__c == null) || (comprador.Oportunidade__c == null)) {
                continue;
            }
            
            List<Comprador__c> duplicados = CompradorSelector.obterCompradorPorIdConta(comprador.Conta__c, comprador.Oportunidade__c);
            
            if (duplicados.isEmpty()) {
                continue;
            }

            for (Comprador__c duplicado : duplicados) {
                if ((duplicado != null) && ObjectHelper.isEqualField(comprador, duplicado, 'Conta__c') && ObjectHelper.isEqualField(comprador, duplicado, 'Oportunidade__c') && !ObjectHelper.isEqualField(comprador, duplicado, 'Id')) {
                    comprador.addError('Já existe um comprador para essa conta.');
                }
            }
        }
    }
    
    public static void validarCompradorPrincipal(List<Comprador__c> compradores) {
        if (compradores == null || compradores.isEmpty()) {
            return;
        }
        
        Set<Id> setIdOportunidades = new Set<Id>();
        for (Comprador__c comprador : compradores) {
            if (comprador.CompradorPrincipal__c != 'Sim') {
                continue;
            }
            
            setIdOportunidades.add(comprador.Oportunidade__c);
        }   
        
        if (!setIdOportunidades.isEmpty()) {

            List<Comprador__c> compradoresExistentes = CompradorSelector.obterCompradoresPrincipaisPorOportunidades(setIdOportunidades);

            Map<Id, Comprador__c> mapCompradoresOportunidade = new Map<Id, Comprador__c>();
            Map<Id, Comprador__c> mapCompradoresId = new Map<Id, Comprador__c>();

            for (Comprador__c compradorExistente : compradoresExistentes) {
                mapCompradoresOportunidade.put(compradorExistente.Oportunidade__c, compradorExistente);
                mapCompradoresId.put(compradorExistente.Id, compradorExistente);
            }

            for (Comprador__c comprador : compradores) {                
                if (comprador.Oportunidade__c != null && mapCompradoresOportunidade.containsKey(comprador.Oportunidade__c) && (mapCompradoresId.get(comprador.Id) == null || !ObjectHelper.isEqualField(comprador, mapCompradoresId.get(comprador.Id), 'CompradorPrincipal__c'))) {
                    comprador.addError('Já possui um comprador principal');
                }
            }
        }
    }
    
    public static void getOpportunityType(List<Comprador__c> compradores) {
        
            if (compradores == null || compradores.isEmpty()) {
                    return;
            }

            Set<Id> setAccountId = new Set<Id>();
            for (Comprador__c comprador : compradores) {
                setAccountId.add(comprador.Conta__c);
            }

            Map<Id, Account> mapAccountId = new Map<Id, Account>([SELECT Id, RecordType.DeveloperName FROM Account WHERE Id IN :setAccountId]);
        
            for (Comprador__c participante : compradores) {
                String accountType = mapAccountId.get(participante.Conta__c).RecordType.DeveloperName;

                if (accountType == 'PessoaFisicaPF' && participante.TipoParticipante__c == 'Sócio') {
                    participante.addError('Não é permitido definir "Sócio" para oportunidades com Conta Pessoal (PF).');
                }
                
                if (accountType == 'PessoaJuridicaPJ' && participante.TipoParticipante__c == 'Comprador') {
                    participante.addError('Não é permitido definir "Comprador" para oportunidades com Conta Jurídica (PJ).');
                }
            }
    }
    
    public static void getEstadoCivil(List<Comprador__c> compradores) {
        if (compradores == null || compradores.isEmpty()) {
            return;
        }
    
        Set<Id> opportunityIds = new Set<Id>();
        for (Comprador__c participante : compradores) {
            if (participante.Oportunidade__c != null) {
                opportunityIds.add(participante.Oportunidade__c);
            }
        }
    
        Map<Id, Integer> conjugeCountMap = new Map<Id, Integer>();
        Map<Id, Comprador__c> mapExistingTipoParticipante = new Map<Id, Comprador__c>();
        List<Comprador__c> existingTipoParticipantes = [
            SELECT Id, Oportunidade__c, TipoParticipante__c 
            FROM Comprador__c 
            WHERE Oportunidade__c IN :opportunityIds
        ];
    
        for (Comprador__c existingTipoParticipante : existingTipoParticipantes) {
            if (existingTipoParticipante.TipoParticipante__c == 'Cônjuge/Companheiro') {
                if (!conjugeCountMap.containsKey(existingTipoParticipante.Oportunidade__c)) {
                    conjugeCountMap.put(existingTipoParticipante.Oportunidade__c, 0);
                }
                conjugeCountMap.put(existingTipoParticipante.Oportunidade__c, conjugeCountMap.get(existingTipoParticipante.Oportunidade__c) + 1);
            }
            mapExistingTipoParticipante.put(existingTipoParticipante.Id, existingTipoParticipante);
        }
    
        for (Comprador__c participante : compradores) {

            if(participante.CompradorPrincipal__c == 'Sim' && participante.PorcentagemDeParticipacao__c == null ){
                participante.PorcentagemDeParticipacao__c = 50;
            }

            if (participante.TipoParticipante__c == 'Cônjuge/Companheiro') {
                Integer totalConjuges = conjugeCountMap.get(participante.Oportunidade__c) != null ? conjugeCountMap.get(participante.Oportunidade__c) : 0;
    
                totalConjuges++;
    
                if (totalConjuges > 1) {
                    if (mapExistingTipoParticipante.containsKey(participante.Id) && mapExistingTipoParticipante.get(participante.Id).TipoParticipante__c == participante.TipoParticipante__c) {
                        continue;
                    }
                    participante.addError('O papel "' + participante.TipoParticipante__c + '" só pode ser associado uma vez por oportunidade.');
                } else {
                    conjugeCountMap.put(participante.Oportunidade__c, totalConjuges);
                    if (participante.PorcentagemDeParticipacao__c == null) {
                        participante.PorcentagemDeParticipacao__c = 50;
                    }
                }
            }
        }
    }

    
    
}