force-app/main/default/objects/Product2/fields/ValorDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>ValorDaUnidade__c</fullName>
    <formula>Bloco__r.Empreendimento__r.ValorMetroQuadrado__c * MetragemDaUnidadeM__c +  ValorDeAcrescimo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor da Unidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ValorVaga__c.field-meta.xml
<CustomField>
    <fullName>ValorVaga__c</fullName>
    <label>Valor Vaga</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Vaga.recordType-meta.xml
<RecordType>
    <fullName>Vaga</fullName>
    <active>true</active>
    <label>Vaga</label>
</RecordType>

force-app/main/default/classes/Product2Helper.cls
public with sharing class Product2Helper {
    private static final Id VAGA_RECORD_TYPE_ID = Schema.SObjectType.Product2.getRecordTypeInfosByName()
    .get('Vaga')
    .getRecordTypeId();

    public static void handleAfterInsert(List<Product2> products) {
        createStandardPricebookEntries(products);
    }

    private static void createStandardPricebookEntries(List<Product2> products) {
        List<PricebookEntry> standardPricebookEntries = new List<PricebookEntry>();
        Id standardPricebookId = getStandardPricebookId();

        for (Product2 iProduct : products) {
            standardPricebookEntries.add(new PricebookEntry(
                Product2Id = iProduct.Id,
                UnitPrice = iProduct.RecordTypeId == VAGA_RECORD_TYPE_ID 
                                                        ? (iProduct.ValorVaga__c != null
                                                            ? iProduct.ValorVaga__c 
                                                            : 0.0)
                                                        : iProduct.ValorDaUnidade__c,
                Pricebook2Id = standardPricebookId,
                IsActive = true
            ));
        }

        insert standardPricebookEntries;
    }

    public static Id getStandardPricebookId() {
        return Test.isRunningTest() 
            ? Test.getStandardPricebookId() 
            : [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1].Id;
    }
}