force-app/main/default/objects/Account/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <label>Cidade</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DDITelefone__c.field-meta.xml
<CustomField>
    <fullName>DDITelefone__c</fullName>
    <label>DDI Telefone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EmailPJ__c.field-meta.xml
<CustomField>
    <fullName>EmailPJ__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PreferenciaDeContato__c.field-meta.xml
<CustomField>
    <fullName>PreferenciaDeContato__c</fullName>
    <label>Preferência de Contato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PreferenciaContato</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PrimeiraCompra__c.field-meta.xml
<CustomField>
    <fullName>PrimeiraCompra__c</fullName>
    <label>Primeira compra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Uf__c.field-meta.xml
<CustomField>
    <fullName>Uf__c</fullName>
    <label>UF</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/WhatsApp__c.field-meta.xml
<CustomField>
    <fullName>WhatsApp__c</fullName>
    <label>WhatsApp</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/AccountHelperTest.cls
@isTest
private class AccountHelperTest {

    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData(){
        List<Account> accounts = new List<Account>{
            new Account(
                Name = 'Test Account',
                CNPJ__c = '45246904000130',
                Type = 'Consulta',
                PrimeiraCompra__c = 'SIM',
                EmailPJ__c = 'teste@email.com',
                WhatsApp__c = '113478374879',
                PreferenciaDeContato__c = 'E-mail',
                Bairro__c = 'Teste',
                Numero__c = 123,
                Cep__c = '01001-000',
                DDICelular__c = null,
                DDITelefone__c = null
            )
        };
        insert accounts;
    }

    @IsTest
    static void testUpdateAccountWithCEP() {
        // Simular resposta válida do ViaCEP
        ViaCEPResponse viaCEPResponse = new ViaCEPResponse('01001-000', 'Praça da Sé', 'lado ímpar', 'Sé', 'São Paulo', 'SP', '3550308', '1004', '11', '7107');
        
        // Chamar o método de atualização da conta
        AccountHelper.updateAccountWithCEP('01001-000', viaCEPResponse);

        // Verificar se os dados da conta foram atualizados corretamente
        Account updatedAccount = [SELECT Bairro__c, Cidade__c, Uf__c, Logradouro__c FROM Account WHERE Cep__c = '01001-000'];
        System.assertEquals('Sé', updatedAccount.Bairro__c);
        System.assertEquals('São Paulo', updatedAccount.Cidade__c);
        System.assertEquals('SP', updatedAccount.Uf__c);
        System.assertEquals('Praça da Sé', updatedAccount.Logradouro__c);
    }

    @IsTest
    static void testGetCEPDataAsync() {
        // Simular a chamada externa com HttpCalloutMock
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        // Chamar o método assíncrono diretamente
        Test.startTest();
        AccountHelper.getCEPDataAsync('01001-000');
        Test.stopTest();

        // Verificar se os dados da conta foram atualizados corretamente
        Account updatedAccount = [SELECT Bairro__c, Cidade__c, Uf__c, Logradouro__c FROM Account WHERE Cep__c = '01001-000'];
        System.assertEquals('Sé', updatedAccount.Bairro__c);
        System.assertEquals('São Paulo', updatedAccount.Cidade__c);
        System.assertEquals('SP', updatedAccount.Uf__c);
        System.assertEquals('Praça da Sé', updatedAccount.Logradouro__c);
    }

    @IsTest
    static void testGetCEPDataAsyncFuture() {
        // Simular a chamada externa com HttpCalloutMock
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        // Chamar o método @future
        Test.startTest();
        AccountHelper.getCEPDataAsyncFuture('01001-000');
        Test.stopTest();

        // Verificar se os dados da conta foram atualizados corretamente
        Account updatedAccount = [SELECT Bairro__c, Cidade__c, Uf__c, Logradouro__c FROM Account WHERE Cep__c = '01001-000'];
        System.assertEquals('Sé', updatedAccount.Bairro__c);
        System.assertEquals('São Paulo', updatedAccount.Cidade__c);
        System.assertEquals('SP', updatedAccount.Uf__c);
        System.assertEquals('Praça da Sé', updatedAccount.Logradouro__c);
    }
}