force-app/main/default/objects/Account/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <label>Cidade</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Uf__c.field-meta.xml
<CustomField>
    <fullName>Uf__c</fullName>
    <label>UF</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountHelper.cls
public with sharing class AccountHelper {

    @future(callout=true)
    public static void getCEPDataAsyncFuture(String cep) {
        getCEPDataAsync(cep);
    }
    public static void getCEPDataAsync(String cep) {
        ViaCEPResponse cepResponse = null;
        try {
            String baseURL = 'https://viacep.com.br/ws/';
            String requestURL = baseURL + cep + '/json/';

            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(requestURL);
            request.setMethod('GET');

            HttpResponse response = http.send(request);

            if (response.getStatusCode() == 200) cepResponse = (ViaCEPResponse)JSON.deserialize(response.getBody(), ViaCEPResponse.class);
        } catch (Exception e) {
            System.debug(e);
        }

        if (cepResponse != null) {
            updateAccountWithCEP(cep, cepResponse);
        }
    }

    public static void updateAccountWithCEP(String cep, ViaCEPResponse cepResponse) {
        List<Account> accountsToUpdate = [SELECT Id, Bairro__c
                                          FROM Account
                                          WHERE Cep__c = :cep];

        for (Account acc : accountsToUpdate) {
            acc.Bairro__c = cepResponse.bairro;
            acc.Cidade__c = cepResponse.localidade;
            acc.Uf__c = cepResponse.uf;
            acc.Logradouro__c = cepResponse.logradouro;
        }

        update accountsToUpdate;
    }
}