force-app/main/default/objects/Account/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DataDeNascimento__c.field-meta.xml
<CustomField>
    <fullName>DataDeNascimento__c</fullName>
    <label>Data de Nascimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/DDITelefone__c.field-meta.xml
<CustomField>
    <fullName>DDITelefone__c</fullName>
    <label>DDI Telefone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EmailPJ__c.field-meta.xml
<CustomField>
    <fullName>EmailPJ__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroDoDocumento__c.field-meta.xml
<CustomField>
    <fullName>NumeroDoDocumento__c</fullName>
    <label>Número do Documento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/PreferenciaDeContato__c.field-meta.xml
<CustomField>
    <fullName>PreferenciaDeContato__c</fullName>
    <label>Preferência de Contato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PreferenciaContato</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PrimeiraCompra__c.field-meta.xml
<CustomField>
    <fullName>PrimeiraCompra__c</fullName>
    <label>Primeira compra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WhatsApp__c.field-meta.xml
<CustomField>
    <fullName>WhatsApp__c</fullName>
    <label>WhatsApp</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/PessoaJuridicaPJ.recordType-meta.xml
<RecordType>
    <fullName>PessoaJuridicaPJ</fullName>
    <active>true</active>
    <label>Pessoa Jurídica (PJ)</label>
</RecordType>

force-app/main/default/objects/AnaliseDeCredito__c/AnaliseDeCredito__c.object-meta.xml
<CustomObject>
    <label>Análise de Crédito</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Análises de Crédito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnaliseDeCredito__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>AnlisesDeCredito</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comprador__c/Comprador__c.object-meta.xml
<CustomObject>
    <label>Comprador</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Comprador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compradores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comprador__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Jurídica (PJ), Pessoa Física (PF), Imobiliária</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comprador__c/recordTypes/Comprador.recordType-meta.xml
<RecordType>
    <fullName>Comprador</fullName>
    <active>true</active>
    <label>Comprador</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ResponsavelPeloLead__c.field-meta.xml
<CustomField>
    <fullName>ResponsavelPeloLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsável pelo Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountControllerTest.cls
@isTest
public class AccountControllerTest {
    
    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData() {
        Id pjRecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PessoaJuridicaPJ' LIMIT 1].Id;

        List<Account> accounts = new List<Account>{
            new Account(
                Name = 'Conta teste1',
                RecordTypeId = pjRecordTypeId,
                CNPJ__c = '45246904000130',
                Type = 'Consulta',
                PrimeiraCompra__c = 'SIM',
                EmailPJ__c = 'teste@email.com',
                WhatsApp__c = '113478374879',
                PreferenciaDeContato__c = 'E-mail',
                Bairro__c = 'Teste',
                Numero__c = 123,
                Cep__c = '01001-000',
                DDICelular__c = null,
                DDITelefone__c = null
            ),

            new Account(
                Name = 'Conta teste2',
                RecordTypeId = pjRecordTypeId,
                CNPJ__c = '45246904000130',
                Type = 'Consulta',
                PrimeiraCompra__c = 'SIM',
                EmailPJ__c = 'teste@email.com',
                WhatsApp__c = '113478374879',
                PreferenciaDeContato__c = 'E-mail',
                Bairro__c = 'Teste',
                Numero__c = 123,
                Cep__c = '01001-000',
                DDICelular__c = null,
                DDITelefone__c = null,
                DataDeNascimento__c = Date.today()
            ),

            new Account(
                Name = 'Conta teste3',
                RecordTypeId = pjRecordTypeId,
                CNPJ__c = '45246904000130',
                Type = 'Consulta',
                PrimeiraCompra__c = 'SIM',
                EmailPJ__c = 'teste@email.com',
                WhatsApp__c = '113478374879',
                PreferenciaDeContato__c = 'E-mail',
                Bairro__c = 'Teste',
                Numero__c = 123,
                Cep__c = '01001-000',
                DDICelular__c = null,
                DDITelefone__c = null
            ),

            new Account(
                Name = 'Conta teste4',
                RecordTypeId = pjRecordTypeId,
                CNPJ__c = '45246904000130',
                Type = 'Consulta',
                PrimeiraCompra__c = 'SIM',
                EmailPJ__c = 'teste@email.com',
                WhatsApp__c = '113478374879',
                PreferenciaDeContato__c = 'E-mail',
                Bairro__c = 'Teste',
                Numero__c = 123,
                Cep__c = '01001-000',
                DDICelular__c = null,
                DDITelefone__c = null
            )
        };

        insert accounts;

        Profile profile = [SELECT Id FROM Profile WHERE (Name = 'Usuário Padrão') OR (Name = 'Standard User') LIMIT 1];

        UserRole papelGerente = [SELECT Id FROM UserRole WHERE Name = 'Gerente' LIMIT 1];
        UserRole papelDiretor = [SELECT Id FROM UserRole WHERE Name = 'Diretor Comercial' LIMIT 1];

        List<User> users = new List<User>{
            new User(
                Alias = 'user1',
                Email = 'test@email.com',
                EmailEncodingKey = 'ISO-8859-1',
                LastName = 'User',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                TimeZoneSidKey = 'America/New_York',
                UserName = 'test240920241005y@email.com',
                profileId = profile.Id
            ),
            new User(
                Alias = 'user2',
                Email = 'test2@email.com',
                EmailEncodingKey = 'ISO-8859-1',
                LastName = 'User',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                TimeZoneSidKey = 'America/New_York',
                UserName = 'test270920241517z@email.com',
                profileId = profile.Id
            )
        };

        insert users;

        assignUserRole(users[0].Id, papelGerente.Id);
        assignUserRole(users[1].Id, papelDiretor.Id);
    }

    @isTest
    private static void obterInfoContaPorAnaliseCreditoTest() {
        Test.startTest();
        Test.stopTest();

        List<Account> accounts = [SELECT Id FROM Account];

        Opportunity opp = new Opportunity(
            Name = 'Oportunidade 1',
            StageName = 'Proposta',
            CloseDate = System.today().addMonths(1),
            AccountId = accounts.get(3).Id,
            ResponsavelPeloLead__c = [SELECT Id FROM User WHERE Alias = 'user1' LIMIT 1].Id
        );

        insert opp;

        AnaliseDeCredito__c analise = new AnaliseDeCredito__c(
            Oportunidade__c = opp.Id
        );

        insert analise;

        insert new List<Comprador__c> {
            new Comprador__c(
                Conta__c = accounts.get(0).Id,
                Oportunidade__c = opp.Id
            ),
            new Comprador__c(
                Conta__c = accounts.get(1).Id,
                Oportunidade__c = opp.Id
            ),
            new Comprador__c(
                Conta__c = accounts.get(2).Id,
                Oportunidade__c = opp.Id
            )
        };

        AnaliseDeCredito__c analiseCredito = [SELECT Id, Oportunidade__c FROM AnaliseDeCredito__c LIMIT 1];

        Map<String,Account> accountInfo = AccountController.obterInfoContaPorAnaliseCredito(analiseCredito.Id);

        Map<String,Account> expectedAccountInfo = new Map<String,Account>();

        List<Comprador__c> compradores = CompradorSelector.obterCompradoresPorOportunidade(analiseCredito.Oportunidade__c);

        for(Comprador__c comprador : compradores) {
            expectedAccountInfo.put(comprador.Conta__r.Name, AccountSelector.obterInfoContaPorId(comprador.Conta__r.Id));
        }

        for (String name : accountInfo.keySet()) {
            Assert.areEqual(accountInfo.get(name), expectedAccountInfo.get(name));
        }
    }

    @isTest
    private static void atualizarValoresContaTest() {
        Test.startTest();
        Test.stopTest();

        List<Account> accounts = [SELECT Id FROM Account];

        Opportunity opp = new Opportunity(
            Name = 'Oportunidade 1',
            StageName = 'Proposta',
            CloseDate = System.today().addMonths(1),
            AccountId = accounts.get(3).Id,
            ResponsavelPeloLead__c = [SELECT Id FROM User WHERE Alias = 'user1' LIMIT 1].Id
        );

        insert opp;

        AnaliseDeCredito__c analise = new AnaliseDeCredito__c(
            Oportunidade__c = opp.Id
        );

        insert analise;

        insert new List<Comprador__c> {
            new Comprador__c(
                Conta__c = accounts.get(0).Id,
                Oportunidade__c = opp.Id
            ),
            new Comprador__c(
                Conta__c = accounts.get(1).Id,
                Oportunidade__c = opp.Id
            ),
            new Comprador__c(
                Conta__c = accounts.get(2).Id,
                Oportunidade__c = opp.Id
            )
        };

        Set<String> fields = Schema.getGlobalDescribe().get('Account').getDescribe().fields.getMap().keySet();

        Account account = Database.query(String.format(
            'SELECT {0} FROM Account LIMIT 1',
            new String[]{String.join(new List<String>(fields), ',')}
        ));

        Map<String,String> camposValores = new Map<String,String> {
            'Name' => 'Teste alterado',
            'NumeroDoDocumento__c' => '123',
            'DataDeNascimento__c' => Date.today().addDays(1).toString()
        };

        Id idAccount = account.Id;

        AccountController.atualizarValoresConta(camposValores, idAccount);

        Account updatedAccount = Database.query(String.format(
            'SELECT {0} FROM Account WHERE Id = :idAccount LIMIT 1',
            new String[]{String.join(new List<String>(fields), ',')}
        ));

        for(String campo : camposValores.keySet()) {
            Assert.areNotEqual(account.get(campo), updatedAccount.get(campo));
        }
    }

    @Future
    private static void assignUserRole(Id userId, Id userRoleId) {
        User user = [SELECT Id FROM User WHERE Id = :userId LIMIT 1];
        UserRole userRole = [SELECT Id FROM UserRole WHERE Id = :userRoleId];
        
        user.UserRoleId = userRole.Id;
        update user;
    }
}