force-app/main/default/objects/Account/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EmailPJ__c.field-meta.xml
<CustomField>
    <fullName>EmailPJ__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PreferenciaDeContato__c.field-meta.xml
<CustomField>
    <fullName>PreferenciaDeContato__c</fullName>
    <label>Preferência de Contato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PreferenciaContato</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PrimeiraCompra__c.field-meta.xml
<CustomField>
    <fullName>PrimeiraCompra__c</fullName>
    <label>Primeira compra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/WhatsApp__c.field-meta.xml
<CustomField>
    <fullName>WhatsApp__c</fullName>
    <label>WhatsApp</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/PessoaJuridicaPJ.recordType-meta.xml
<RecordType>
    <fullName>PessoaJuridicaPJ</fullName>
    <active>true</active>
    <label>Pessoa Jurídica (PJ)</label>
</RecordType>

force-app/main/default/classes/AccountTriggerHandlerTest.cls
@isTest
private class AccountTriggerHandlerTest {
    @isTest static void testBeforeInsert() {

        // Obter o RecordType para Account (usando o nome do tipo de registro)
        RecordType accountRecordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'PessoaJuridicaPJ' AND SObjectType = 'Account' LIMIT 1];

        // Verifica se o tipo de registro foi encontrado
        System.assertNotEquals(null, accountRecordType, 'O tipo de registro "Pessoa Jurídica (PJ)" não foi encontrado.');
 
        List<Account> accounts = new List<Account>{
            new Account(
                Name = 'Test Account', // O objeto Account usa "Name" ao invés de "FirstName" e "LastName"
                CNPJ__c = '45246904000130',
                Type = 'Consulta',
                PrimeiraCompra__c = 'SIM',
                EmailPJ__c = 'teste@email.com',
                WhatsApp__c = '113478374879',
                PreferenciaDeContato__c = 'E-mail',
                Cep__c = '60710-180',
                RecordTypeId = accountRecordType.Id // Associando o RecordTypeId correto
            )
        };

        Test.startTest();
        insert accounts;
        Test.stopTest();
    }

    @isTest static void testBeforeUpdate() {

        // Obter o RecordType para Account (usando o nome do tipo de registro)
        RecordType accountRecordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'PessoaJuridicaPJ' AND SObjectType = 'Account' LIMIT 1];

        // Verifica se o tipo de registro foi encontrado
        System.assertNotEquals(null, accountRecordType, 'O tipo de registro "Pessoa Jurídica (PJ)" não foi encontrado.');

        List<Account> accounts = new List<Account>{
            new Account(
                Name = 'Test Account', // O objeto Account usa "Name" ao invés de "FirstName" e "LastName"
                CNPJ__c = '45246904000130',
                Type = 'Consulta',
                PrimeiraCompra__c = 'SIM',
                EmailPJ__c = 'teste@email.com',
                WhatsApp__c = '113478374879',
                PreferenciaDeContato__c = 'E-mail',
                Cep__c = '60710-180',
                RecordTypeId = accountRecordType.Id // Associando o RecordTypeId correto
            )
        };

        insert accounts;

        // Atualizando o campo EmailPJ__c
        for(Account acc : accounts) {
            acc.EmailPJ__c = 'email@example.com';
        }

        Test.startTest();
        update accounts;
        Test.stopTest();
    }
}