force-app/main/default/objects/Account/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DataDeNascimento__c.field-meta.xml
<CustomField>
    <fullName>DataDeNascimento__c</fullName>
    <label>Data de Nascimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/DDITelefone__c.field-meta.xml
<CustomField>
    <fullName>DDITelefone__c</fullName>
    <label>DDI Telefone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EmailPJ__c.field-meta.xml
<CustomField>
    <fullName>EmailPJ__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/OrgaoEmissor__c.field-meta.xml
<CustomField>
    <fullName>OrgaoEmissor__c</fullName>
    <inlineHelpText>Órgão emissor é a instituição responsável por emitir um documento.</inlineHelpText>
    <label>Orgão Emissor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CNIG - Conselho Nacional de Imigração</fullName>
            </value>
            <value>
                <fullName>CRECI - Conselho Regional de Corretores de Imóveis</fullName>
            </value>
            <value>
                <fullName>CRESS - Conselho Regional de Serviço Socia</fullName>
            </value>
            <value>
                <fullName>Detran</fullName>
            </value>
            <value>
                <fullName>MTE - Ministério do Trabalho e Emprego</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
            <value>
                <fullName>Polícia Federal</fullName>
            </value>
            <value>
                <fullName>SSP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PreferenciaDeContato__c.field-meta.xml
<CustomField>
    <fullName>PreferenciaDeContato__c</fullName>
    <label>Preferência de Contato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PreferenciaContato</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PrimeiraCompra__c.field-meta.xml
<CustomField>
    <fullName>PrimeiraCompra__c</fullName>
    <label>Primeira compra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Uf__c.field-meta.xml
<CustomField>
    <fullName>Uf__c</fullName>
    <label>UF</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/WhatsApp__c.field-meta.xml
<CustomField>
    <fullName>WhatsApp__c</fullName>
    <label>WhatsApp</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Cep__c.field-meta.xml
<CustomField>
    <fullName>Cep__c</fullName>
    <label>Cep</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CidadeEndereco__c.field-meta.xml
<CustomField>
    <fullName>CidadeEndereco__c</fullName>
    <label>Cidade</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DataDeNascimento__c.field-meta.xml
<CustomField>
    <fullName>DataDeNascimento__c</fullName>
    <inlineHelpText>DD/MM/AAAA</inlineHelpText>
    <label>Data de Nascimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DDICelular__c.field-meta.xml
<CustomField>
    <fullName>DDICelular__c</fullName>
    <label>DDI Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/DDITelefone__c.field-meta.xml
<CustomField>
    <fullName>DDITelefone__c</fullName>
    <label>DDI Telefone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/DocumentodeIdentificao__c.field-meta.xml
<CustomField>
    <fullName>DocumentodeIdentificao__c</fullName>
    <label>Documento de Identificação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipodeDocumentodeIdentiicacao</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Numero__c.field-meta.xml
<CustomField>
    <fullName>Numero__c</fullName>
    <label>Número</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NumerodoCreci__c.field-meta.xml
<CustomField>
    <fullName>NumerodoCreci__c</fullName>
    <label>Número do Creci</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/OrgaoEmissor__c.field-meta.xml
<CustomField>
    <fullName>OrgaoEmissor__c</fullName>
    <label>Órgão Emissor</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/PreferenciadeContato__c.field-meta.xml
<CustomField>
    <fullName>PreferenciadeContato__c</fullName>
    <label>Preferência de Contato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PreferenciaContato</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UF__c.field-meta.xml
<CustomField>
    <fullName>UF__c</fullName>
    <label>UF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/WhatsApp__c.field-meta.xml
<CustomField>
    <fullName>WhatsApp__c</fullName>
    <label>WhatsApp Contato</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/ContactHelperTest.cls
@isTest
private class ContactHelperTest {
    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData(){
        List<Account> accounts = new List<Account>{
            new Account(
                Name = 'Test Account',
                CNPJ__c = '45246904000130',
                Type = 'Consulta',
                PrimeiraCompra__c = 'SIM',
                EmailPJ__c = 'teste@email.com',
                WhatsApp__c = '113478374879',
                PreferenciaDeContato__c = 'E-mail',
                DDICelular__c = null,
                DDITelefone__c = null
            )
        };

        insert accounts;


        List <Contact> contacts = new List <Contact>{
            new Contact (
                FirstName = 'Test Contact',
                LastName = 'Test',	
                Bairro__c = 'Teste',
                Numero__c = 123,
                Logradouro__c = 'Logradouro',
                UF__c = 'RJ',
                CidadeEndereco__c = 'Cidade Maravilhosa',
                Cep__c = '01001-000',
                DataDeNascimento__c = Date.valueOf('2000-07-23'),
                CPF__c = '75230388080',
                DocumentodeIdentificao__c = 'RG', 
                OrgaoEmissor__c = 'SSP', 
                Email = 'email@example.com',
                WhatsApp__c = '12123456789', 
                NumerodoCreci__c = 1232486728,
                DDICelular__c = null,
                DDITelefone__c = null,
                AccountId = accounts.get(0).Id
            )   
        };
        
        insert contacts;
    }

    @isTest
    private static void getCEPDataAsyncTest() {
        Test.startTest();
            ContactHelper.getCEPDataAsync('01001000');
        Test.stopTest();
    }

    @isTest
    private static void updateContactWithCEPTest() {
        ViaCEPResponse viaCEPResponse = new ViaCEPResponse( '01001-000', 'Praça da Sé', 'lado ímpar', 'Sé', 'São Paulo', 'SP', '3550308', '1004', '11', '7107');

        Contact contatoAntiga = [SELECT Id, Bairro__c, CidadeEndereco__c, UF__c, Logradouro__c FROM Contact LIMIT 1];

        Test.startTest();
            ContactHelper.updateContactWithCEP('01001-000', viaCEPResponse);
        Test.stopTest();

        Contact contatoAtualizada = [SELECT Id, Bairro__c, CidadeEndereco__c, UF__c, Logradouro__c FROM Contact LIMIT 1];

        Assert.areNotEqual(contatoAntiga.Bairro__c, contatoAtualizada.Bairro__c);
        Assert.areNotEqual(contatoAntiga.CidadeEndereco__c, contatoAtualizada.CidadeEndereco__c);
        Assert.areNotEqual(contatoAntiga.UF__c, contatoAtualizada.UF__c);
        Assert.areNotEqual(contatoAntiga.Logradouro__c, contatoAtualizada.Logradouro__c);
    }
}