force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Data_de_Casamento__c.field-meta.xml
<CustomField>
    <fullName>Data_de_Casamento__c</fullName>
    <label>Data de Casamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/DataDeEmissao__c.field-meta.xml
<CustomField>
    <fullName>DataDeEmissao__c</fullName>
    <label>Data de Emissão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/DataDeNascimento__c.field-meta.xml
<CustomField>
    <fullName>DataDeNascimento__c</fullName>
    <label>Data de Nascimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Estado_de_Nascimento__c.field-meta.xml
<CustomField>
    <fullName>Estado_de_Nascimento__c</fullName>
    <label>Estado de Nascimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acre (AC)</fullName>
            </value>
            <value>
                <fullName>Alagoas (AL)</fullName>
            </value>
            <value>
                <fullName>Amapá (AP)</fullName>
            </value>
            <value>
                <fullName>Amazonas (AM)</fullName>
            </value>
            <value>
                <fullName>Bahia (BA)</fullName>
            </value>
            <value>
                <fullName>Ceará (CE)</fullName>
            </value>
            <value>
                <fullName>Distrito Federal (DF)</fullName>
            </value>
            <value>
                <fullName>Espírito Santo (ES)</fullName>
            </value>
            <value>
                <fullName>Goiás (GO)</fullName>
            </value>
            <value>
                <fullName>Maranhão (MA)</fullName>
            </value>
            <value>
                <fullName>Mato Grosso (MT)</fullName>
            </value>
            <value>
                <fullName>Mato Grosso do Sul (MS)</fullName>
            </value>
            <value>
                <fullName>Minas Gerais (MG)</fullName>
            </value>
            <value>
                <fullName>Pará (PA)</fullName>
            </value>
            <value>
                <fullName>Paraíba (PB)</fullName>
            </value>
            <value>
                <fullName>Paraná (PR)</fullName>
            </value>
            <value>
                <fullName>Pernambuco (PE)</fullName>
            </value>
            <value>
                <fullName>Piauí (PI)</fullName>
            </value>
            <value>
                <fullName>Rio de Janeiro (RJ)</fullName>
            </value>
            <value>
                <fullName>Rio Grande do Norte (RN)</fullName>
            </value>
            <value>
                <fullName>Rio Grande do Sul (RS)</fullName>
            </value>
            <value>
                <fullName>Rondônia (RO)</fullName>
            </value>
            <value>
                <fullName>Roraima (RR)</fullName>
            </value>
            <value>
                <fullName>Santa Catarina (SC)</fullName>
            </value>
            <value>
                <fullName>São Paulo (SP)</fullName>
            </value>
            <value>
                <fullName>Sergipe (SE)</fullName>
            </value>
            <value>
                <fullName>Tocantins (TO)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EstadoCivil__c.field-meta.xml
<CustomField>
    <fullName>EstadoCivil__c</fullName>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EstadoCivil</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EstadoEmissor__c.field-meta.xml
<CustomField>
    <fullName>EstadoEmissor__c</fullName>
    <label>Estado Emissor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nacionalidade__c.field-meta.xml
<CustomField>
    <fullName>Nacionalidade__c</fullName>
    <label>Nacionalidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Alemão(a)</fullName>
            </value>
            <value>
                <fullName>Argentino(a)</fullName>
            </value>
            <value>
                <fullName>Australiano(a)</fullName>
            </value>
            <value>
                <fullName>Austríaco(a)</fullName>
            </value>
            <value>
                <fullName>Belga(o)</fullName>
            </value>
            <value>
                <fullName>Bolíviano(a)</fullName>
            </value>
            <value>
                <fullName>Brasileiro(a)</fullName>
                <default>true</default>
                <label>Brasileiro(a)</label>
            </value>
            <value>
                <fullName>Búlgaro(a)</fullName>
            </value>
            <value>
                <fullName>Cambojano(a)</fullName>
            </value>
            <value>
                <fullName>Canadense</fullName>
            </value>
            <value>
                <fullName>Chadiano(a)</fullName>
            </value>
            <value>
                <fullName>Checo(a)</fullName>
            </value>
            <value>
                <fullName>Chinês(a)</fullName>
            </value>
            <value>
                <fullName>Colombiano(a)</fullName>
            </value>
            <value>
                <fullName>Coreano(a)</fullName>
            </value>
            <value>
                <fullName>Croata(o)</fullName>
            </value>
            <value>
                <fullName>Cubano(a)</fullName>
            </value>
            <value>
                <fullName>Dinamarquês(a)</fullName>
            </value>
            <value>
                <fullName>Equatoriano(a)</fullName>
            </value>
            <value>
                <fullName>Esloveno(a)</fullName>
            </value>
            <value>
                <fullName>Espanhol(a)</fullName>
            </value>
            <value>
                <fullName>Finlandês(a)</fullName>
            </value>
            <value>
                <fullName>Francês(a)</fullName>
            </value>
            <value>
                <fullName>Grego(a)</fullName>
            </value>
            <value>
                <fullName>Guatemalteco(a)</fullName>
            </value>
            <value>
                <fullName>Haitiano(a)</fullName>
            </value>
            <value>
                <fullName>Holandês(a)</fullName>
            </value>
            <value>
                <fullName>Hondurenho(a)</fullName>
            </value>
            <value>
                <fullName>Húngaro(a)</fullName>
            </value>
            <value>
                <fullName>Indiano(a)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Naturalidade__c.field-meta.xml
<CustomField>
    <fullName>Naturalidade__c</fullName>
    <inlineHelpText>A naturalidade refere-se ao estado de nascimento.</inlineHelpText>
    <label>Naturalidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_da_Mae__c.field-meta.xml
<CustomField>
    <fullName>Nome_da_Mae__c</fullName>
    <description>Deve ser preenchido com o nome da mãe do usuário.</description>
    <label>Nome da Mãe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_do_Pai__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Pai__c</fullName>
    <description>Deve ser preenchido com o nome do pai do usuário.</description>
    <label>Nome do Pai</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NumeroDoDocumento__c.field-meta.xml
<CustomField>
    <fullName>NumeroDoDocumento__c</fullName>
    <label>Número do Documento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/OrgaoEmissor__c.field-meta.xml
<CustomField>
    <fullName>OrgaoEmissor__c</fullName>
    <inlineHelpText>Órgão emissor é a instituição responsável por emitir um documento.</inlineHelpText>
    <label>Orgão Emissor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CNIG - Conselho Nacional de Imigração</fullName>
            </value>
            <value>
                <fullName>CRECI - Conselho Regional de Corretores de Imóveis</fullName>
            </value>
            <value>
                <fullName>CRESS - Conselho Regional de Serviço Socia</fullName>
            </value>
            <value>
                <fullName>Detran</fullName>
            </value>
            <value>
                <fullName>MTE - Ministério do Trabalho e Emprego</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
            <value>
                <fullName>Polícia Federal</fullName>
            </value>
            <value>
                <fullName>SSP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountSelector.cls
public class AccountSelector {
    public static Account obterInfoContaPorId(Id idConta) {
        return [SELECT 
            Name, FirstName, LastName, CNPJ__c, Nome_da_Mae__c,
            CPF__c, EstadoEmissor__c, Nacionalidade__c, Naturalidade__c,
            Nome_do_Pai__c, DataDeNascimento__c, DataDeEmissao__c, OrgaoEmissor__c,
            EstadoCivil__c, Data_de_Casamento__c, Conjuge__pc, RecordType.DeveloperName,
            Estado_de_Nascimento__c, NumeroDoDocumento__c, Celular__c FROM Account WHERE Id = :idConta];
    }

    public static Account obterContaPorId(Id idConta) {
        return [SELECT Id FROM Account WHERE Id = :idConta];
    }
}