force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <description>Agrupa as unidades cadastradas por empreendimento.</description>
    <label>Torre</label>
    <nameField>
        <label>Nome da torre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Blocos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indique se o empreendimento está disponível para venda de unidades.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <formula>ValorBase__c * Coeficiente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <referenceTo>UnidadeTabelaVendas__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ValorDeAcrescimo__c.field-meta.xml
<CustomField>
    <fullName>ValorDeAcrescimo__c</fullName>
    <label>Valor de Acréscimo Vigente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Unidade.recordType-meta.xml
<RecordType>
    <fullName>Unidade</fullName>
    <active>true</active>
    <label>Unidade</label>
</RecordType>

force-app/main/default/objects/SerieDePagamento__c/SerieDePagamento__c.object-meta.xml
<CustomObject>
    <label>Série de Pagamento DESATIVAR</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Série de Pagamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Séries de Pagamento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SerieDePagamento__c/fields/DataPrimeiroVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataPrimeiroVencimento__c</fullName>
    <label>Data Primeiro Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SerieDePagamento__c/fields/Entrada__c.field-meta.xml
<CustomField>
    <fullName>Entrada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Entrada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SerieDePagamento__c/fields/Fixa__c.field-meta.xml
<CustomField>
    <fullName>Fixa__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fixa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SerieDePagamento__c/fields/Juros__c.field-meta.xml
<CustomField>
    <fullName>Juros__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Juros</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SerieDePagamento__c/fields/Parcelas__c.field-meta.xml
<CustomField>
    <fullName>Parcelas__c</fullName>
    <label>Parcelas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SerieDePagamento__c/fields/PercentualValorUnidade__c.field-meta.xml
<CustomField>
    <fullName>PercentualValorUnidade__c</fullName>
    <label>Percentual Valor Unidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SerieDePagamento__c/fields/Periodicidade__c.field-meta.xml
<CustomField>
    <fullName>Periodicidade__c</fullName>
    <label>Periodicidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Única</fullName>
            </value>
            <value>
                <fullName>Mensal</fullName>
            </value>
            <value>
                <fullName>Semestral</fullName>
            </value>
            <value>
                <fullName>Anual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SerieDePagamento__c/fields/TabelaDeVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaDeVenda__c</fullName>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipName>SerieDePagamentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SerieDePagamento__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dação</fullName>
            </value>
            <value>
                <fullName>Permuta</fullName>
            </value>
            <value>
                <fullName>Crédito de Distrato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Clonado__c.field-meta.xml
<CustomField>
    <fullName>Clonado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clonado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/IdDeOrigem__c.field-meta.xml
<CustomField>
    <fullName>IdDeOrigem__c</fullName>
    <label>ID de Origem</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PercentualDeAcrescimo__c.field-meta.xml
<CustomField>
    <fullName>PercentualDeAcrescimo__c</fullName>
    <inlineHelpText>Percentual (%) que será acrescido no valor das Unidades</inlineHelpText>
    <label>Percentual de acréscimo (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/ValorDeAcrescimo__c.field-meta.xml
<CustomField>
    <fullName>ValorDeAcrescimo__c</fullName>
    <inlineHelpText>Valor nominal que será acrescido no valor das Unidades</inlineHelpText>
    <label>Valor de acréscimo Nominal (Moeda)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/ValorDeLista__c.field-meta.xml
<CustomField>
    <fullName>ValorDeLista__c</fullName>
    <label>Valor De Lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/ValorDeVenda__c.field-meta.xml
<CustomField>
    <fullName>ValorDeVenda__c</fullName>
    <label>Valor de venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/VigenciaFim__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFim__c</fullName>
    <label>Vigência fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/VigenciaInicio__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicio__c</fullName>
    <label>Vigência início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/UnidadeTabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Entrada de Preço</label>
    <nameField>
        <label>Nome de Unidade da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entrada de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/CoeficienteTabela__c.field-meta.xml
<CustomField>
    <fullName>CoeficienteTabela__c</fullName>
    <label>Coeficiente na Tabela</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/MetragemUnidade__c.field-meta.xml
<CustomField>
    <fullName>MetragemUnidade__c</fullName>
    <label>Metragem da Unidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipName>Unidades_da_Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entrada de Preços</relationshipLabel>
    <relationshipName>UnidadesTabelaVendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TabelaVendasHelperTest.cls
@isTest
private class TabelaVendasHelperTest {

    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData() {
        List<Empreendimento__c> empreendimentos = new List<Empreendimento__c> {
            TestDataFactory.gerarEmpreendimento(),
            TestDataFactory.gerarEmpreendimento()
        };

        insert empreendimentos;

        TabelaVendas__c tabela1 = TestDataFactory.gerarTabelaVendas();
        tabela1.Empreendimento__c = empreendimentos.get(0).Id;
        insert tabela1;

        TabelaVendas__c tabela2 = TestDataFactory.gerarTabelaVendas();
        tabela2.Empreendimento__c = empreendimentos.get(1).Id;
        insert tabela2;

        Product2 produto1 = TestDataFactory.gerarProduto();
        produto1.Empreendimento__c = empreendimentos.get(1).Id;
        insert produto1;

        Product2 produto2 = TestDataFactory.gerarProduto();
        produto2.Empreendimento__c = empreendimentos.get(0).Id;
        insert produto2;

        UnidadeTabelaVendas__c unidadeTabela = TestDataFactory.gerarUnidadeTabelaVendas(tabela2.id);
        unidadeTabela.Unidade__c = produto1.Id;
        insert unidadeTabela;

        insert TestDataFactory.gerarUnidadeTabelaVendas(tabela2.id);

        Map<String, RecordType> recordTypes = new Map<String, RecordType>();
        Set<String> recordTypeTypes = new Set<String>{'Account', 'Contact'};

        Profile profile = [SELECT Id FROM Profile WHERE (Name = 'Usuário Padrão') OR (Name = 'Standard User') LIMIT 1];

        User user = new User(
            Alias = 'user1',
            Email = 'test@email.com',
            EmailEncodingKey = 'ISO-8859-1',
            LastName = 'User',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'America/New_York',
            UserName = 'test240920241005y@email.com',
            profileId = profile.Id
        );

        insert user;

        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Empreendimento Teste',
            CNPJ__c = '10155540000106'
        );

        insert empreendimento;

        Bloco__c bloco = new Bloco__c(
            Name = 'Torre A',
            Empreendimento__c = empreendimento.Id
        );

        insert bloco;

        Product2 unidade = new Product2(
            Name = 'Unidade',
            Bloco__c = bloco.Id,
            NumeroDaUnidade__c = 1
        );

        insert unidade;

        TabelaVendas__c tabelaVendas = new TabelaVendas__c(
            Name = 'Tabela Teste',
            Clonado__c = false

        );
        
        insert tabelaVendas;

        SerieDePagamento__c serieOrigem = new SerieDePagamento__c(
            TabelaDeVenda__c = tabelaVendas.Id,
            Periodicidade__c = 'Mensal',
            DataPrimeiroVencimento__c = Date.newInstance(2024, 11, 1),
            Entrada__c = true,
            Fixa__c = true,
            Juros__c = true,
            Parcelas__c = 12,
            PercentualValorUnidade__c = 10
        );
        
        insert serieOrigem;

      
    }

    @isTest
    public static void validateDuplicatesTest() {
        Empreendimento__c empreendimento = [SELECT Id FROM Empreendimento__c LIMIT 1];
    
        TabelaVendas__c tabelaVenda = new TabelaVendas__c(
            Name = 'Tabela Teste 2',
            Clonado__c = false,
            Empreendimento__c = empreendimento.Id,
            VigenciaInicio__c = Date.newInstance(2024, 10, 1),
            VigenciaFim__c = Date.newInstance(2024, 11, 1)
        );
    
        insert tabelaVenda;
    
        TabelaVendas__c tabelaVendaDuplicada = new TabelaVendas__c(
            Name = 'Tabela Teste 2',
            Clonado__c = false,
            Empreendimento__c = empreendimento.Id,
            VigenciaInicio__c = Date.newInstance(2024, 10, 1),
            VigenciaFim__c = Date.newInstance(2024, 11, 1)
        );
    
        TabelaVendas__c tabelaVendaTeste = new TabelaVendas__c(
            Name = 'Tabela Teste 3',
            Clonado__c = null,
            Empreendimento__c = empreendimento.Id,
            VigenciaInicio__c = Date.newInstance(2024, 10, 1),
            VigenciaFim__c = Date.newInstance(2024, 11, 1)
        );
    
        TabelaVendas__c tabelaVendaSobreposta = new TabelaVendas__c(
            Name = 'Tabela Teste 4',
            Clonado__c = false,
            Empreendimento__c = empreendimento.Id,
            VigenciaInicio__c = Date.newInstance(2024, 10, 15), 
            VigenciaFim__c = Date.newInstance(2024, 11, 15)
        );
    
        Test.startTest();
        try {
            TabelaVendasHelper.validateDuplicates(new List<TabelaVendas__c> { tabelaVendaDuplicada });
            insert tabelaVendaDuplicada; 
            System.assert(false, 'Deveria ter lançado uma exceção ao inserir um registro duplicado');
        } catch (DmlException e) {
            System.assert(e.getMessage().contains('Não é possível criar uma tabela de vendas com dados repetidos: mesmo empreendimento, datas e percentual.'), 'A mensagem de erro deve ser a correta.');
        }
    
        try {
            TabelaVendasHelper.validateDuplicates(new List<TabelaVendas__c> { tabelaVendaTeste });
            insert tabelaVendaTeste;
            System.assert(false, 'Deveria ter lançado uma exceção ao não informar se é uma tabela clonada ou não.');
        } catch (DmlException e) {
            System.assert(e.getMessage().contains('Informe se é uma tabela clonada ou não.'), 'A mensagem de erro deve ser a correta.');
        }
    
        try {
            TabelaVendasHelper.validateDuplicates(new List<TabelaVendas__c> { tabelaVendaSobreposta });
            insert tabelaVendaSobreposta; 
            System.assert(false, 'Deveria ter lançado uma exceção ao inserir uma tabela com datas sobrepostas');
        } catch (DmlException e) {
            System.assert(e.getMessage().contains('As datas de vigência não podem se sobrepor às datas de uma tabela existente para o mesmo empreendimento.'), 'A mensagem de erro deve ser a correta.');
        }
    

        Test.stopTest();
    }
    

    @isTest
    public static void updateAtivoTest(){

        Empreendimento__C empreendimento = [SELECT Id FROM Empreendimento__C LIMIT 1];

        TabelaVendas__c tabelaVenda = new TabelaVendas__c(
            Name = 'Tabela Teste 3',
            Clonado__c = false,
            
            VigenciaInicio__c = Date.newInstance(2024, 10, 14),
            VigenciaFim__c = Date.newInstance(2024, 10, 15), 
            Ativo__c = false

        );
        insert tabelaVenda;

        Test.startTest();

        TabelaVendasHelper.updateAtivo(new List<TabelaVendas__c> { tabelaVenda });
        
        tabelaVenda.Empreendimento__c = empreendimento.Id;
        
        tabelaVenda.Ativo__c = true;
        update tabelaVenda;
        
        Test.stopTest();
    }

    @isTest
    public static void ValidateIdDeOrigemTest() {
        TabelaVendas__c tabelaOrigem = new TabelaVendas__c(
            Name = 'Tabela Origem',
            Clonado__c = false,
            VigenciaInicio__c = Date.newInstance(2024, 10, 1),
            VigenciaFim__c = Date.newInstance(2024, 10, 31),
            Ativo__c = false
        );

        insert tabelaOrigem;

        TabelaVendas__c tabelaReferencia = new TabelaVendas__c(
            Name = 'Tabela Referência',
            Clonado__c = false,
            VigenciaInicio__c = Date.newInstance(2024, 11, 1),
            VigenciaFim__c = Date.newInstance(2024, 11, 30),
            Ativo__c = false,
            IdDeOrigem__c = tabelaOrigem.Id
        );

        insert tabelaReferencia;

        Map<Id, List<SerieDePagamento__c>> tabelaToSeriesMap = new Map<Id, List<SerieDePagamento__c>>();
        List<SerieDePagamento__c> seriesPagamentoList = new List<SerieDePagamento__c> {
            new SerieDePagamento__c(TabelaDeVenda__c = tabelaOrigem.Id, Periodicidade__c = 'Mensal'),
            new SerieDePagamento__c(TabelaDeVenda__c = tabelaOrigem.Id, Periodicidade__c = 'Única')
        };
        insert seriesPagamentoList;

        tabelaToSeriesMap.put(tabelaOrigem.Id, seriesPagamentoList);

        Test.startTest();
        TabelaVendasHelper.cloneRecords(new List<TabelaVendas__c> { tabelaReferencia });
        Test.stopTest();

        List<SerieDePagamento__c> novasSeries = [SELECT Id, TabelaDeVenda__c, Periodicidade__c, Type__c 
            FROM SerieDePagamento__c WHERE TabelaDeVenda__c = :tabelaReferencia.Id];

        System.assertEquals(2, novasSeries.size(), 'Duas séries de pagamento devem ser clonadas.');
        System.assertEquals('Mensal', novasSeries[0].Periodicidade__c, 'A periodicidade da série clonada deve ser igual.');
    }
    @isTest
    public static void calculateValuesTest() {
        Empreendimento__c empreendimento2 = new Empreendimento__c(
            Name = 'Empreendimento Teste2',
            CNPJ__c = '10155540000106'
        );
        insert empreendimento2;

        TabelaVendas__c tabelaAnterior = new TabelaVendas__c(
            Name = 'Tabela Anterior',
            Clonado__c = false,
            Empreendimento__c = empreendimento2.Id,
            ValorDeLista__c = 1000,
            ValorDeVenda__c = 1000,
            PercentualDeAcrescimo__c = 0,
            VigenciaInicio__c = Date.newInstance(2024, 10, 1),
            VigenciaFim__c = Date.newInstance(2024, 10, 15)
        );
        insert tabelaAnterior;

        TabelaVendas__c tabelaClonada = new TabelaVendas__c(
            Name = 'Tabela Clonada',
            Clonado__c = true,
            Empreendimento__c = tabelaAnterior.Empreendimento__c,
            ValorDeLista__c = 1000,
            PercentualDeAcrescimo__c = 20,
            VigenciaInicio__c = Date.newInstance(2024, 10, 16),
            VigenciaFim__c = Date.newInstance(2024, 10, 31)
        );

        Test.startTest();
        TabelaVendasHelper.validateDuplicates(new List<TabelaVendas__c> { tabelaClonada });
        insert tabelaClonada; 
        Test.stopTest();

        tabelaClonada = [SELECT ValorDeVenda__c, ValorDeAcrescimo__c,PercentualDeAcrescimo__c FROM TabelaVendas__c WHERE Id = :tabelaClonada.Id];
        Decimal esperadoValorAcrescimo = tabelaAnterior.ValorDeVenda__c * (tabelaClonada.PercentualDeAcrescimo__c / 100); 
        Decimal esperadoValorVenda = tabelaAnterior.ValorDeVenda__c + esperadoValorAcrescimo; 

        System.assertEquals(esperadoValorAcrescimo, tabelaClonada.ValorDeAcrescimo__c, 'O valor de acréscimo deve ser calculado corretamente.');
        System.assertEquals(esperadoValorVenda, tabelaClonada.ValorDeVenda__c, 'O valor de venda deve ser calculado corretamente.');
    }

    @isTest
    private static void inserirUnidadesTabelasInsertTest() {
        Set<Id> idsTabelasComUnidade = ObjectHelper.getLookUpId(
            [SELECT TabelaVenda__c FROM UnidadeTabelaVendas__c WHERE TabelaVenda__c != null],
            'TabelaVenda__c'
        );

        List<TabelaVendas__c> tabelas = [
            SELECT
                Id,
                Empreendimento__c
            FROM TabelaVendas__c WHERE Id NOT IN :idsTabelasComUnidade
        ];

        Test.startTest();
        TabelaVendasHelper.inserirUnidadesTabelas(tabelas);
        Test.stopTest();

        List<UnidadeTabelaVendas__c> unidadesTabelas = [
            SELECT 
                Id
            FROM UnidadeTabelaVendas__c
            WHERE TabelaVenda__c IN :(new Map<Id,TabelaVendas__c>(tabelas).keySet())
        ];

        Assert.isFalse(unidadesTabelas.isEmpty());
    }

    @isTest
    private static void inserirUnidadesTabelasUpdateTest() {
        Set<Id> idsTabelasComUnidade = ObjectHelper.getLookUpId(
            [SELECT TabelaVenda__c FROM UnidadeTabelaVendas__c WHERE TabelaVenda__c != null],
            'TabelaVenda__c'
        );

        List<TabelaVendas__c> tabelas = [
            SELECT
                Id,
                Empreendimento__c
            FROM TabelaVendas__c WHERE Id IN :idsTabelasComUnidade
        ];

        UnidadeTabelaVendas__c unidadesTabela = [
            SELECT 
                Id,
                Name,
                PrecoLista__c,
                CoeficienteTabela__c,
                MetragemUnidade__c,
                Unidade__c,
                TabelaVenda__c
            FROM UnidadeTabelaVendas__c
            WHERE TabelaVenda__c IN :idsTabelasComUnidade
            LIMIT 1
        ];

        Test.startTest();
        TabelaVendasHelper.inserirUnidadesTabelas(tabelas);
        Test.stopTest();

        UnidadeTabelaVendas__c unidadesTabelaUpdated = [
            SELECT 
                Id,
                Name,
                PrecoLista__c,
                CoeficienteTabela__c,
                MetragemUnidade__c,
                Unidade__c,
                TabelaVenda__c
            FROM UnidadeTabelaVendas__c
            WHERE TabelaVenda__c IN :idsTabelasComUnidade
            LIMIT 1
        ];

        Assert.areNotEqual(unidadesTabela, unidadesTabelaUpdated);
    }
}