force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DDDTelefone__c.field-meta.xml
<CustomField>
    <fullName>DDDTelefone__c</fullName>
    <label>DDD Telefone</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DDITelefone__c.field-meta.xml
<CustomField>
    <fullName>DDITelefone__c</fullName>
    <label>DDI Telefone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDDCelular__c.field-meta.xml
<CustomField>
    <fullName>DDDCelular__c</fullName>
    <label>DDD Celular</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDICelular__c.field-meta.xml
<CustomField>
    <fullName>DDICelular__c</fullName>
    <label>DDI Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <description>Empreendimento Interessado</description>
    <label>Empreendimento</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FaixaInvestimento__c.field-meta.xml
<CustomField>
    <fullName>FaixaInvestimento__c</fullName>
    <label>Faixa de Investimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R$ 300 Mil a R$ 999 Mil</fullName>
            </value>
            <value>
                <fullName>R$ 1 Milhão a R$ 1,9 Milhões</fullName>
            </value>
            <value>
                <fullName>R$ 2 Milhões a R$ 3,9 Milhões</fullName>
            </value>
            <value>
                <fullName>R$ 4 Milhões a R$ 5,9 Milhões</fullName>
            </value>
            <value>
                <fullName>Acima de R$ 6 Milhões</fullName>
            </value>
            <value>
                <fullName>Não definido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaAtual__c.field-meta.xml
<CustomField>
    <fullName>MidiaAtual__c</fullName>
    <label>Mídia Atual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Midia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventHelperTest.cls
@isTest
private class EventHelperTest {
    @TestSetup
    static void makeData() {
        doMakeData();
    }

    private static void doMakeData(){
        Empreendimento__c empreendimento = new Empreendimento__c();
        empreendimento.Name = 'Empreendimento de Teste';
        empreendimento.CNPJ__c = '21268544000109';
        
        insert empreendimento;

        List<Lead> leads = new List<Lead>{
            new Lead(
                LastName = 'teste1',
                Company = 'Chave',
                Email = 'e@e.com',
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '16',
                Phone = '18845-6789',
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '16',
                Celular__c = '18845-6789',
                CPF__c = '87657837861',
                LeadSource = 'Outros',
                FaixaInvestimento__c = 'R$ 300 Mil a R$ 999 Mil',
                Status = 'Scheduled',
                MidiaAtual__c = 'Facebook Ads',
                EmpreendimentoInteresse__c = empreendimento.Id
            ),

            new Lead(
                LastName = 'teste1',
                Company = 'Chave',
                Email = 'e@4.com',
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '16',
                Phone = '28845-6789',
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '16',
                Celular__c = '28845-6789',
                LeadSource = 'Outros',
                CPF__c = '41445446723',
                Status = 'Scheduled',
                MidiaAtual__c = 'Facebook Ads',
                FaixaInvestimento__c = 'R$ 300 Mil a R$ 999 Mil',
                EmpreendimentoInteresse__c = empreendimento.Id
            ),
            
            new Lead(
                LastName = 'teste fail',
                Company = 'dhrefjikdoc',
                LeadSource = 'Outros',
                MidiaAtual__c = 'Facebook Ads',
                Email = 'e@ase.com',
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '16',
                Phone = '38845-6789',
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '16',
                Celular__c = '38845-6789',
                CPF__c = '51273233204'
            )
        };
     
        TriggerHandler.bypass('LeadTriggerHandler');
        insert leads;
        TriggerHandler.clearBypass('LeadTriggerHandler');

        Account contaPF = new Account(
            FirstName = 'Conta',
            LastName = 'PF',
            PersonEmail = 'conta@teste.com'
        );
        insert contaPF;
        
        insert new Opportunity(
            Name = 'Oportunidade Teste',
            StageName = 'Proposta',
            CloseDate = Date.today().addDays(30),
            AccountId = contaPF.Id
        );
    }   

    @isTest
    private static void validateEventLookupTest(){
        List<Lead> leads = [SELECT Id FROM Lead];
        Id oppId = [SELECT Id FROM Opportunity WHERE Name = 'Oportunidade Teste' LIMIT 1].id;

        List<Event> events = new List<Event>{
            new Event(
                WhoId = leads[0].Id,
                Type = 'Visita',
                Subject = 'E-mail',
                StatusVisita__c = 'Done',
                DurationInMinutes = 30,
                ActivityDateTime = Datetime.now()
            ),

            new Event(
                WhoId = leads[1].Id,
                Type = 'Visita',
                StatusVisita__c = 'Done',
                DurationInMinutes = 30,
                ActivityDateTime = Datetime.now()
            ),

            new Event(
                WhoId = leads[2].Id,
                Type = 'Visita',
                StatusVisita__c = 'Done',
                DurationInMinutes = 30,
                ActivityDateTime = Datetime.now()
            ),

            new Event(
                Subject = 'Visita',
                StatusVisita__c = 'Done',
                DurationInMinutes = 30,
                ActivityDateTime = Datetime.now().addDays(15),
                WhatId = oppId
            ),

            new Event(
                Subject = 'Reunião online',
                StatusVisita__c = 'Done',
                DurationInMinutes = 30,
                ActivityDateTime = Datetime.now().addDays(15),
                WhatId = oppId
            ),

            new Event(
                Subject = 'Reunião Presencial',
                StatusVisita__c = 'Done',
                DurationInMinutes = 30,
                ActivityDateTime = Datetime.now().addDays(15),
                WhatId = oppId
            )
        };
    
        Test.startTest();
            EventHelper.validateEventLookup(events);
        Test.stopTest();

        Assert.isNotNull(events[0].EmpreendimentoInteresse__c);
        Assert.isNotNull(events[1].EmpreendimentoInteresse__c);
        Assert.isNull(events[2].EmpreendimentoInteresse__c);

        Assert.areNotEqual(events[0].Subject, events[0].Type);
    }
}