force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DDDTelefone__c.field-meta.xml
<CustomField>
    <fullName>DDDTelefone__c</fullName>
    <label>DDD Telefone</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DDITelefone__c.field-meta.xml
<CustomField>
    <fullName>DDITelefone__c</fullName>
    <label>DDI Telefone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <description>Agrupa as unidades cadastradas por empreendimento.</description>
    <label>Torre</label>
    <nameField>
        <label>Nome da torre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Blocos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A Unidade deve estar relacionada ao Empreendimento de Interesse</errorMessage>
        <filterItems>
            <field>$Source.EmpreendimentodeInteresse__c</field>
            <operation>equals</operation>
            <valueField>Product2.Empreendimento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Oportunidades.recordType-meta.xml
<RecordType>
    <fullName>Oportunidades</fullName>
    <active>true</active>
    <businessProcess>Processo de Vendas Oportunidade</businessProcess>
    <label>Oportunidades</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <referenceTo>UnidadeTabelaVendas__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Unidade.recordType-meta.xml
<RecordType>
    <fullName>Unidade</fullName>
    <active>true</active>
    <label>Unidade</label>
</RecordType>

force-app/main/default/classes/OpportunityDATest.cls
@isTest
private class OpportunityDATest {

    @TestSetup
    static void makeData() {
        doCreateData();
    }
    
    private static void doCreateData() {

        // Criando a Account com campos obrigatórios
        Account account = new Account(
            Name = 'Account',
            CNPJ__c = '10155540000106',
            DDICelular__c = 'Brasil (+55)',
            DDDCelular__c = '12',
            Celular__c = '12345-7789',   
            DDITelefone__c = 'Brasil (+55)',
            DDDTelefone__c = '16',
            Phone = '12345-6789'   
        );
        
        insert account;

        // Criando o Empreendimento
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Empreendimento Teste',
            CNPJ__c = '10155540000106'
        );

        insert empreendimento;

        // Criando o Bloco
        Bloco__c bloco = new Bloco__c(
            Name = 'Torre A',
            Empreendimento__c = empreendimento.Id
        );

        insert bloco;

        // Criando o Produto (Unidade)
        Product2 unidade1 = new Product2(
            Name = 'Unidade 1',
            Bloco__c = bloco.Id,
            NumeroDaUnidade__c = 1
        );

        Product2 unidade2 = new Product2(
            Name = 'Unidade 2',
            Bloco__c = bloco.Id,
            NumeroDaUnidade__c = 2
        );

        insert new List<Product2>{unidade1, unidade2};

        // Criando as oportunidades associadas (uma para cada unidade)
        List<Opportunity> opportunities = new List<Opportunity>{
            new Opportunity(
                Name = 'Oportunidade 1',
                StageName = 'Proposta',
                CloseDate = System.today().addMonths(1),
                AccountId = account.Id,   // Associando à Account
                Unidade__c = unidade1.Id   // Associando à Unidade 1
            ),
            new Opportunity(
                Name = 'Oportunidade 2',
                StageName = 'Proposta',
                CloseDate = System.today().addMonths(2),
                AccountId = account.Id,
                Unidade__c = unidade2.Id
            )
        };

        insert opportunities;
    }

    @isTest
    public static void getOpportunityByAccountProductTest() {
        // Consultando o produto e a conta criados no TestSetup
        Product2 produto = [SELECT Id FROM Product2 WHERE Name = 'Unidade 1' LIMIT 1];
        Account account = [SELECT Id FROM Account LIMIT 1];
        
        // Testando a função OpportunityDA.getOpportunityByAccountProduct
        List<Opportunity> opps = OpportunityDA.getOpportunityByAccountProduct(account.Id, produto.Id, null, null);
        
        // Debug para verificar o número de oportunidades retornadas
        System.debug('Número de oportunidades retornadas: ' + opps.size());

        // Verificando se o tamanho da lista é 1 (apenas 1 oportunidade com a Unidade 1)
        Assert.isTrue(opps.size() == 1, 'Esperava 1 oportunidade, mas foi retornado: ' + opps.size());
    }
}