force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DDDTelefone__c.field-meta.xml
<CustomField>
    <fullName>DDDTelefone__c</fullName>
    <label>DDD Telefone</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DDITelefone__c.field-meta.xml
<CustomField>
    <fullName>DDITelefone__c</fullName>
    <label>DDI Telefone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bloco__c/Bloco__c.object-meta.xml
<CustomObject>
    <description>Agrupa as unidades cadastradas por empreendimento.</description>
    <label>Torre</label>
    <nameField>
        <label>Nome da torre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torres</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bloco__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipName>Blocos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Celular__c.field-meta.xml
<CustomField>
    <fullName>Celular__c</fullName>
    <label>Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DDDCelular__c.field-meta.xml
<CustomField>
    <fullName>DDDCelular__c</fullName>
    <label>DDD Celular</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DDDTelefone__c.field-meta.xml
<CustomField>
    <fullName>DDDTelefone__c</fullName>
    <label>DDD Telefone</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DDICelular__c.field-meta.xml
<CustomField>
    <fullName>DDICelular__c</fullName>
    <label>DDI Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/DDITelefone__c.field-meta.xml
<CustomField>
    <fullName>DDITelefone__c</fullName>
    <label>DDI Telefone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Corretor.recordType-meta.xml
<RecordType>
    <fullName>Corretor</fullName>
    <active>true</active>
    <description>Tipo de Registro criado para controlar o cadastro dos corretores parceiros</description>
    <label>Corretor</label>
</RecordType>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Corretor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResponsavelPeloLead__c.field-meta.xml
<CustomField>
    <fullName>ResponsavelPeloLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsável pelo Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A Unidade deve estar relacionada ao Empreendimento de Interesse</errorMessage>
        <filterItems>
            <field>$Source.EmpreendimentodeInteresse__c</field>
            <operation>equals</operation>
            <valueField>Product2.Empreendimento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bloco__c.field-meta.xml
<CustomField>
    <fullName>Bloco__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bloco</label>
    <referenceTo>Bloco__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <referenceTo>UnidadeTabelaVendas__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Unidade.recordType-meta.xml
<RecordType>
    <fullName>Unidade</fullName>
    <active>true</active>
    <label>Unidade</label>
</RecordType>

force-app/main/default/classes/OpportunityTeamMemberDomainTest.cls
@isTest
private class OpportunityTeamMemberDomainTest {
    
    @TestSetup
    static void makeData() {
        doCreateData();
    }

    private static void doCreateData() {

        Map<String, RecordType> recordTypes = new Map<String, RecordType>();
        Set<String> recordTypeTypes = new Set<String>{'Account', 'Contact'};

        Profile profile = [SELECT Id FROM Profile WHERE (Name = 'Administrador do sistema') OR (Name = 'System Administrator') LIMIT 1];
        Id roleId = [SELECT Id FROM UserRole WHERE DeveloperName = 'Atendente_de_Vendas_BC' LIMIT 1].Id;

        User user = new User(
            Alias = 'TestUser',
            Email = 'test@email.com',
            EmailEncodingKey = 'ISO-8859-1',
            LastName = 'User',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            TimeZoneSidKey = 'America/New_York',
            UserName = 'test240920241005@email.com',
            profileId = profile.Id
        );
        insert user;

        atualizarRoleUsuario(user.Id, roleId);

        for (RecordType rt : [SELECT DeveloperName FROM RecordType WHERE SobjectType IN :recordTypeTypes]) {
            recordTypes.put(rt.DeveloperName, rt);
        }

        List<Account> accounts = new List<Account>{
            new Account(
                Name = 'Account',
                CNPJ__c = '45246904000130',
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '16',
                Celular__c = '18845-6789',
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '11',
                Phone = '12345-6789'   
            ),
            new Account(
                Name = 'Corretor 1',
                CNPJ__c = '55181736000103',
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '16',
                Celular__c = '18805-6789',
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '15',
                Phone = '36259-6789'   
            ),
            new Account(
                Name = 'Corretor 2',
                CNPJ__c = '35635456000102',
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '16',
                Celular__c = '18845-0089',
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '12',
                Phone = '96857-6789'   
            )
        };
        
        insert accounts;

        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Empreendimento Teste',
            CNPJ__c = '10155540000106'
        );

        insert empreendimento;

        Bloco__c bloco = new Bloco__c(
            Name = 'Torre A',
            Empreendimento__c = empreendimento.Id
        );

        insert bloco;

        Product2 unidade = new Product2(
            Name = 'Unidade',
            Bloco__c = bloco.Id,
            NumeroDaUnidade__c = 1
        );

        insert unidade;

        List<Contact> corretores = new List<Contact>{
            new Contact(
                FirstName = 'Corretor',
                LastName = 'A',
                RecordTypeId = recordTypes.get('Corretor').Id,
                AccountId = accounts.get(1).Id,
                Celular__c = '36251-6363',      
                DDDCelular__c = '11',          
                DDICelular__c = 'Brasil (+55)',
                Phone = '78747-5252',           
                DDDTelefone__c = '21',          
                DDITelefone__c = 'Brasil (+55)'
            ),
            new Contact(
                FirstName = 'Corretor',
                LastName = 'B',
                RecordTypeId = recordTypes.get('Corretor').Id,
                AccountId = accounts.get(1).Id,
                Celular__c = '85856-6363',      
                DDDCelular__c = '11',          
                DDICelular__c = 'Brasil (+55)',
                Phone = '74145-3524',           
                DDDTelefone__c = '21',          
                DDITelefone__c = 'Brasil (+55)'
            )
        };
    
        insert corretores;
        
        List<Opportunity> opportunities = new List<Opportunity>{
            new Opportunity(
                Name = 'Oportunidade 1',
                StageName = 'Proposta',
                CloseDate = System.today().addMonths(1),
                AccountId = accounts.get(1).Id,
                ResponsavelPeloLead__c = user.Id
            ),
            new Opportunity(
                Name = 'Oportunidade 2',
                StageName = 'Proposta',
                CloseDate = System.today().addMonths(2),
                Unidade__c = unidade.Id,
                AccountId = accounts.get(0).Id,
                Corretor__c = corretores.get(0).Id,
                ResponsavelPeloLead__c = user.Id
            )
        };

        insert opportunities;
    }

    @isTest
    static void divideOppTeamMembersByOpportunityTest() {
        Test.startTest();
        OpportunityTeamMemberDomain.divideOppTeamMembersByOpportunity([SELECT Id, Name, OpportunityId FROM OpportunityTeamMember WHERE OpportunityId = :[SELECT Id FROM Opportunity WHERE Name = 'Oportunidade 1' LIMIT 1].Id]);
        Test.stopTest();
    }

    @isTest
    static void checkUserRoleOnModificationTest() {

        Id opportunityId = [SELECT Id FROM Opportunity WHERE Name = 'Oportunidade 1' LIMIT 1].Id;
        User user = [SELECT Id FROM User WHERE Alias = 'TestUser' LIMIT 1];

        OpportunityTeamMember opportunityTeamMember = new OpportunityTeamMember(
            OpportunityId = opportunityId,
            UserId = user.Id
        );

        System.runAs(user) {
            Database.SaveResult resultInsert = Database.insert(opportunityTeamMember, false);
            System.assert(!resultInsert.isSuccess());
        }
        
    }

    @Future
    private static void atualizarRoleUsuario(Id userId, Id roleId) {
        User user = new User(   
            Id = userId,
            UserRoleId = roleId
        );

        update user;
    }
}