force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NumeroDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>NumeroDaUnidade__c</fullName>
    <label>Número da Unidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <formula>ValorBase__c * Coeficiente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/SeriePagamentos__c.object-meta.xml
<CustomObject>
    <label>Série de Pagamentos</label>
    <nameField>
        <label>Nome de Série de Pagamentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series de Pagamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SeriePagamentos__c/fields/InicioPagamento__c.field-meta.xml
<CustomField>
    <fullName>InicioPagamento__c</fullName>
    <inlineHelpText>Numeral, em meses. Se for &quot;0&quot;, significa hoje. Se for &quot;40&quot;, significa &quot;daqui a 40 meses&quot; a partir de hoje</inlineHelpText>
    <label>Início de Pagamento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/QuantidadeParcelas__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeParcelas__c</fullName>
    <label>Quantidade de Parcelas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Series de Pagamentos</relationshipLabel>
    <relationshipName>SeriesPagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/TipoCondicao__c.field-meta.xml
<CustomField>
    <fullName>TipoCondicao__c</fullName>
    <label>Tipo de Condição</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TiposCondicoes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/ValorTotal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotal__c</fullName>
    <label>Valor total (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcela__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcela__c</fullName>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Mensal</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Semestral</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Anual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcelaPos__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcelaPos__c</fullName>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/UnidadeTabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Entrada de Preço</label>
    <nameField>
        <label>Nome de Unidade da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entrada de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipName>Unidades_da_Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/TiposCondicoes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ato</fullName>
    </customValue>
    <customValue>
        <fullName>Sinal</fullName>
    </customValue>
    <customValue>
        <fullName>Mensais</fullName>
    </customValue>
    <customValue>
        <fullName>Semestrais</fullName>
    </customValue>
    <customValue>
        <fullName>Anuais</fullName>
    </customValue>
    <customValue>
        <fullName>Única</fullName>
    </customValue>
    <customValue>
        <fullName>Financiamento</fullName>
    </customValue>
    <customValue>
        <fullName>Periódica</fullName>
    </customValue>
    <customValue>
        <fullName>Bimestral</fullName>
    </customValue>
    <customValue>
        <fullName>Trimestral</fullName>
    </customValue>
    <masterLabel>Tipos de Condições</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactoryTest.cls
@isTest
private class TestDataFactoryTest {

    @TestSetup
    static void makeData() {
        Product2 produto = new Product2();
        produto.Name = 'Produto de Teste';
        produto.ProductCode = 'Teste-1';
        produto.isActive = true;
        produto.NumeroDaUnidade__c = 777;
        insert produto;

        TabelaVendas__c tabelaVendas = new TabelaVendas__c();
        tabelaVendas.Name = 'Teste'; 
        tabelaVendas.PeriodicidadeParcelaPos__c = 1;
        tabelaVendas.PeriodicidadeParcela__c = '1';
        insert tabelaVendas;
    }
    
    @isTest
    private static void gerarContaTest(){
        Account expectedAccount = new Account();
        expectedAccount.Name = 'Conta de Teste';

        Test.startTest();
        Account actualAccount = TestDataFactory.gerarConta();
        Test.stopTest();

        Assert.areEqual(expectedAccount, actualAccount);
    }

    @isTest
    private static void gerarProdutoTest(){
        Product2 produto = new Product2();
        produto.Name = 'Produto de Teste';
        produto.ProductCode = 'Teste-1';
        produto.isActive = true;
        produto.NumeroDaUnidade__c = 777;

        Test.startTest();
        Product2 actualProduct = TestDataFactory.gerarProduto();
        Test.stopTest();

        Assert.areEqual(produto, actualProduct);
    }

    @isTest
    private static void gerarPricebookEntryTest() {
        Id idProduto = [SELECT Id FROM Product2 LIMIT 1].Id;

        PricebookEntry pricebookEntry = new PricebookEntry();
        pricebookEntry.Pricebook2Id = Test.getStandardPricebookId();
        pricebookEntry.Product2Id = idProduto;
        pricebookEntry.UseStandardPrice = false;
        pricebookEntry.UnitPrice = 100;
        pricebookEntry.IsActive = true;

        Test.startTest();
        PricebookEntry actual = TestDataFactory.gerarPricebookEntry(idProduto);
        Test.stopTest();

        Assert.areEqual(pricebookEntry, actual);
    }

    @isTest
    private static void gerarEmpreendimentoTest() {
        Empreendimento__c empreendimento = new Empreendimento__c();
        empreendimento.Name = 'Empreendimento de Teste';
        empreendimento.CNPJ__c = '22151181000190';


        Test.startTest();
        Empreendimento__c actual = TestDataFactory.gerarEmpreendimento();
        Test.stopTest();

        Assert.areEqual(empreendimento, actual);
    }


    @isTest
    private static void gerarTabelaVendasTest() {
        TabelaVendas__c tabelaVendas = new TabelaVendas__c();
        tabelaVendas.Name = 'Teste'; 
        tabelaVendas.PeriodicidadeParcelaPos__c = 1;
        tabelaVendas.PeriodicidadeParcela__c = '1';

        Test.startTest();
        TabelaVendas__c actual = TestDataFactory.gerarTabelaVendas();
        Test.stopTest(); 

        Assert.areEqual(tabelaVendas, actual);
    }

    @isTest
    private static void gerarSeriePagamentoTest() {
        Id idTabela = [SELECT Id FROM TabelaVendas__c LIMIT 1].Id;

        SeriePagamentos__c serie = new SeriePagamentos__c();
        serie.Name = 'Teste';
        serie.InicioPagamento__c = 1;
        serie.QuantidadeParcelas__c = 1;
        serie.ValorTotal__c= 1;
        serie.TabelaVenda__c = idTabela;
        serie.TipoCondicao__c = 'Ato';


        Test.startTest();
        SeriePagamentos__c actual = TestDataFactory.gerarSeriePagamento(idTabela);
        Test.stopTest();

        Assert.areEqual(serie, actual);
    }

    @isTest
    private static void gerarUnidadeTabelaVendasTest() {
        Id idTabela = [SELECT Id FROM TabelaVendas__c LIMIT 1].Id;

        UnidadeTabelaVendas__c unidadeVenda = new UnidadeTabelaVendas__c();
        unidadeVenda.Name = 'UnidadeVendaTeste';
        unidadeVenda.TabelaVenda__c = idTabela;
        unidadeVenda.PrecoLista__c = 300000;

        Test.startTest();
        UnidadeTabelaVendas__c actual = TestDataFactory.gerarUnidadeTabelaVendas(idTabela);
        Test.stopTest();

        Assert.areEqual(unidadeVenda, actual);
    }
}