force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indique se o empreendimento está disponível para venda de unidades.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <label>Bairro</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/DataConclusaoPlanejada__c.field-meta.xml
<CustomField>
    <fullName>DataConclusaoPlanejada__c</fullName>
    <label>Data de Conclusão Planejada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/DataInicioPlanejada__c.field-meta.xml
<CustomField>
    <fullName>DataInicioPlanejada__c</fullName>
    <label>Data de Início Planejada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/Uf__c.field-meta.xml
<CustomField>
    <fullName>Uf__c</fullName>
    <label>UF</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <description>Bairro do lead</description>
    <label>Bairro</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <description>Cep do Lead</description>
    <label>CEP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDDCelular__c.field-meta.xml
<CustomField>
    <fullName>DDDCelular__c</fullName>
    <label>DDD Celular</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDICelular__c.field-meta.xml
<CustomField>
    <fullName>DDICelular__c</fullName>
    <label>DDI Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <description>Empreendimento Interessado</description>
    <label>Empreendimento</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaAtual__c.field-meta.xml
<CustomField>
    <fullName>MidiaAtual__c</fullName>
    <label>Mídia Atual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Midia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/UF__c.field-meta.xml
<CustomField>
    <fullName>UF__c</fullName>
    <description>UF do Lead</description>
    <label>UF</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventDATest.cls
@isTest
public class EventDATest {

    @TestSetup
    private static void makeData() {
        doCreateData();
    }

    private static void doCreateData() {
        // Criando um registro de Empreendimento com mais campos relevantes
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Empreendimento Teste',
            CNPJ__c = '12345678000195', // CNPJ válido
            Bairro__c = 'Centro',
            CEP__c = '01001-000',
            Cidade__c = 'São Paulo',
            UF__c = 'SP',
            Logradouro__c = 'Rua Teste',
            DataInicioPlanejada__c = Date.today(), // Data de início planejada
            DataConclusaoPlanejada__c = Date.today().addMonths(12), // Data de conclusão planejada
            Ativo__c = true // Empreendimento ativo
        );
        insert empreendimento;

        Lead lead = new Lead(
            LastName = 'Teste',
            Company = 'Teste',
            Description = 'Teste',
            DDITelefone__c = 'Brasil (+55)',
            DDDTelefone__c = '16',
            Phone = '18845-6789',
            DDICelular__c = 'Brasil (+55)',
            DDDCelular__c = '16',
            Celular__c = '18845-6789',
            Email = 'Example@email.com',
            Status = 'Scheduled',
            MidiaAtual__c = 'Instagram',
            LeadSource = 'Instagram',
            CPF__c = '12345678909', // Usando um CPF válido
            CNPJ__c = '12345678000195', // Preenchendo o campo CNPJ
            EmpreendimentoInteresse__c = empreendimento.Id // Usando o ID do Empreendimento criado
        );
        insert lead;

        List<Event> events = new List<Event>{
            new Event(
                Subject = 'Teste',
                ActivityDate = Date.today(),
                DurationInMinutes = 60,
                ActivityDateTime = Datetime.now(),
                WhoId = lead.Id,
                StatusVisita__c = 'Done'
            ),
            new Event(
                Subject = 'Teste',
                ActivityDate = Date.today(),
                DurationInMinutes = 60,
                ActivityDateTime = Datetime.now(),
                WhoId = lead.Id
            )
        };

        insert events;
    }

    @isTest
    private static void getEventDoneByWhoIdTest() {
        Test.startTest();

        List<Lead> leads = [SELECT Id FROM Lead];
        List<Event> events = EventDA.getEventDoneByWhoId(
            new Set<String>{'Id'},
            new Set<Id>{leads.get(0).Id}
        );

        Test.stopTest();
        Assert.isTrue(events.size() == 1, 'Deve haver um evento com status "Done".');
    }

    @isTest
    private static void getEventByWhoIdTest() {
        Lead lead = [SELECT Id FROM Lead].get(0);
        List<Event> events = new List<Event>();

        Test.startTest();
        events = EventDA.getEventByWhoId(
            new Set<String>{'Id', 'WhoId'},
            new Set<Id>{lead.Id}
        );
        Test.stopTest();

        Assert.isTrue(events.size() == 2, 'Deve haver dois eventos associados ao Lead.');
    }
}