force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmpreendimentoTriggerHandler.cls
public with sharing class EmpreendimentoTriggerHandler extends TriggerHandler {

    // Sobrescrevendo o método beforeInsert para lidar com a lógica antes de inserir registros
    public override void beforeInsert() {
        List<String> ceps = new List<String>();
        for (Empreendimento__c emp : (List<Empreendimento__c>) Trigger.new) {
            if (emp.CEP__c != null) {
                ceps.add(emp.CEP__c);
            }
        }

        // Lógica para verificar se não é um contexto futuro ou em lote
        if (!ceps.isEmpty() && !System.isFuture() && !System.isBatch()) {
            for (String cep : ceps) {
                EmpreendimentoHelper.getCEPDataAsyncFuture(cep);
            }
        }
    }

    // Sobrescrevendo o método beforeUpdate para lidar com a lógica antes de atualizar registros
    public override void beforeUpdate() {
        List<String> ceps = new List<String>();
        for (Empreendimento__c emp : (List<Empreendimento__c>) Trigger.new) {
            Empreendimento__c oldEmp = (Empreendimento__c) Trigger.oldMap.get(emp.Id);
            if (emp.CEP__c != null && emp.CEP__c != oldEmp.CEP__c) {
                ceps.add(emp.CEP__c);
            }
        }

        // Lógica para verificar se não é um contexto futuro ou em lote
        if (!ceps.isEmpty() && !System.isFuture() && !System.isBatch()) {
            for (String cep : ceps) {
                EmpreendimentoHelper.getCEPDataAsyncFuture(cep);
            }
        }
    }
}