force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indique se o empreendimento está disponível para venda de unidades.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EmpreendimentodeInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentodeInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Empreendimento__c.Generico__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades(Empreendimento de interesse)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoVenda__c.field-meta.xml
<CustomField>
    <fullName>TipoVenda__c</fullName>
    <label>Tipo de Venda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoVenda</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A Unidade deve estar relacionada ao Empreendimento de Interesse</errorMessage>
        <filterItems>
            <field>$Source.EmpreendimentodeInteresse__c</field>
            <operation>equals</operation>
            <valueField>Product2.Empreendimento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Coeficiente__c.field-meta.xml
<CustomField>
    <fullName>Coeficiente__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Coeficiente a ser aplicado nesta unidade para geração do valor comercial.</description>
    <inlineHelpText>Coeficiente a ser aplicado nesta unidade para geração do valor comercial.</inlineHelpText>
    <label>Coeficiente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MetragemDaUnidadeM__c.field-meta.xml
<CustomField>
    <fullName>MetragemDaUnidadeM__c</fullName>
    <label>Metragem da Unidade (m²)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <formula>ValorBase__c * Coeficiente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <referenceTo>UnidadeTabelaVendas__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ValorDaUnidade__c.field-meta.xml
<CustomField>
    <fullName>ValorDaUnidade__c</fullName>
    <formula>Bloco__r.Empreendimento__r.ValorMetroQuadrado__c * MetragemDaUnidadeM__c +  ValorDeAcrescimo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor da Unidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Unidade.recordType-meta.xml
<RecordType>
    <fullName>Unidade</fullName>
    <active>true</active>
    <label>Unidade</label>
</RecordType>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/TipoVenda__c.field-meta.xml
<CustomField>
    <fullName>TipoVenda__c</fullName>
    <label>Tipo de Venda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoVenda</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/VigenciaFim__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFim__c</fullName>
    <label>Vigência fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/VigenciaInicio__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicio__c</fullName>
    <label>Vigência início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/UnidadeTabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Entrada de Preço</label>
    <nameField>
        <label>Nome de Unidade da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entrada de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/CoeficienteTabela__c.field-meta.xml
<CustomField>
    <fullName>CoeficienteTabela__c</fullName>
    <label>Coeficiente na Tabela</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/MetragemUnidade__c.field-meta.xml
<CustomField>
    <fullName>MetragemUnidade__c</fullName>
    <label>Metragem da Unidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipName>Unidades_da_Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entrada de Preços</relationshipLabel>
    <relationshipName>UnidadesTabelaVendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/TipoVenda.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Financiamento Bancário</fullName>
    </customValue>
    <customValue>
        <fullName>Venda á Vista</fullName>
    </customValue>
    <customValue>
        <fullName>Financiamento Direto</fullName>
    </customValue>
    <masterLabel>Tipo da Venda</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TabelaVendasHelper.cls
public with sharing class TabelaVendasHelper {
    
    public static void inserirUnidadesTabelas(List<TabelaVendas__c> tabelas) {
        Set<Id> empreendimentoIds = new Set<Id>();
        Set<Id> tabelaVendasIds = new Set<Id>();
        
        for (TabelaVendas__c tab : tabelas) {
            if (tab.Empreendimento__c != null) {
                empreendimentoIds.add(tab.Empreendimento__c);
            }
            tabelaVendasIds.add(tab.Id);
        }
        
        Map<Id, Product2> unidades = ProdutoSelector.obterUnidadesRelacionadas(empreendimentoIds);
        Map<Id, UnidadeTabelaVendas__c> unidadesExistentes = UnidadeTabelaSelector.obterUnidadesTabelaExistentes(tabelaVendasIds);
        
        
        List<UnidadeTabelaVendas__c> unidadesParaAtualizar = new List<UnidadeTabelaVendas__c>();
        List<UnidadeTabelaVendas__c> unidadesParaInserir = new List<UnidadeTabelaVendas__c>();
        List<UnidadeTabelaVendas__c> unidadesParaExcluir = new List<UnidadeTabelaVendas__c>();
        
        Set<Id> idsExistentesParaManter = new Set<Id>();
        
        for (TabelaVendas__c tab : tabelas) {
            for (Product2 unidade : unidades.values()) {
                Boolean found = false;
                
                for (UnidadeTabelaVendas__c existente : unidadesExistentes.values()) {
                    if (existente.Unidade__c == unidade.Id && existente.TabelaVenda__c == tab.Id) {
                        existente.Name = unidade.Name;
                        existente.PrecoLista__c = unidade.ValorDaUnidade__c;
                        existente.CoeficienteTabela__c = unidade.Coeficiente__c;
                        existente.MetragemUnidade__c = unidade.MetragemDaUnidadeM__c;
                        unidadesParaAtualizar.add(existente);
                        idsExistentesParaManter.add(existente.Id);
                        found = true;
                        break;
                    }
                }
                
                if (!found) {
                    UnidadeTabelaVendas__c novaUnidadeTabela = new UnidadeTabelaVendas__c();
                    novaUnidadeTabela.Name = unidade.Name;
                    novaUnidadeTabela.PrecoLista__c = unidade.ValorDaUnidade__c;
                    novaUnidadeTabela.CoeficienteTabela__c = unidade.Coeficiente__c;
                    novaUnidadeTabela.MetragemUnidade__c = unidade.MetragemDaUnidadeM__c;
                    novaUnidadeTabela.Unidade__c = unidade.Id;
                    novaUnidadeTabela.TabelaVenda__c = tab.Id;
                    unidadesParaInserir.add(novaUnidadeTabela);
                }
            }
        }
        
        for (UnidadeTabelaVendas__c existente : unidadesExistentes.values()) {
            if (!idsExistentesParaManter.contains(existente.Id)) {
                unidadesParaExcluir.add(existente);
            }
        }
        
        if (!unidadesParaAtualizar.isEmpty()) {
            update unidadesParaAtualizar;
        }
        if (!unidadesParaInserir.isEmpty()) {
            insert unidadesParaInserir;
        }
        if (!unidadesParaExcluir.isEmpty()) {
            delete unidadesParaExcluir;
        }
    }
    
    public static void validarTipoVenda(List<TabelaVendas__c> tabelas) {
        Set<String> tipoVenda = new Set<String>();
        Set<String> setNome = new Set<String>();
        Set<Id> setEmpreendimento = new Set<Id>();
    
        for (TabelaVendas__c iTab : tabelas) {
            if (iTab.Name != null) {
                setNome.add(iTab.Name);
            }
            if (iTab.Empreendimento__c != null) {
                setEmpreendimento.add(iTab.Empreendimento__c);
            }
            if (iTab.TipoVenda__c != null) {
                tipoVenda.add(iTab.TipoVenda__c);
            }
        }
    
        List<TabelaVendas__c> tipoVendaTabela = [
            SELECT 
                Id, 
                Name, 
                TipoVenda__c,
                Empreendimento__c
            FROM TabelaVendas__c
            WHERE 
                Name IN :setNome 
                OR Empreendimento__c IN :setEmpreendimento
                OR TipoVenda__c IN :tipoVenda
        ];
    
        List<Opportunity> tipoVendaOportunidade = [
            SELECT 
                Id, 
                Name, 
                EmpreendimentodeInteresse__c
            FROM Opportunity
            WHERE 
                EmpreendimentodeInteresse__c IN :setEmpreendimento
        ];
    
        Map<Id, String> empreendimentoTabelaMap = new Map<Id, String>();
        for (TabelaVendas__c tabela : tipoVendaTabela) {
            if (tabela.Empreendimento__c != null) {
                empreendimentoTabelaMap.put(tabela.Empreendimento__c, tabela.TipoVenda__c);
            }
        }
    
        for (Opportunity opp : tipoVendaOportunidade) {
            if (opp.EmpreendimentodeInteresse__c != null && empreendimentoTabelaMap.containsKey(opp.EmpreendimentodeInteresse__c)) {
                String tipoVendaTab = empreendimentoTabelaMap.get(opp.EmpreendimentodeInteresse__c);
    
                for (TabelaVendas__c tabela : tabelas) {
                    if (tabela.Empreendimento__c == opp.EmpreendimentodeInteresse__c) {
                        if (tabela.TipoVenda__c == tipoVendaTab && tabela.Id == null && tabela.Ativo__c == true) {
                            throw new AuraHandledException('Já existe uma tabela com o mesmo tipo de venda para esse empreendimento.');
                        }
                    }
                }
            }
        }
    }
    
    public static void validarTabelaIguais(List<TabelaVendas__c> tabelas) {
        Set<String> setNome = new Set<String>();
        Set<Id> setEmpreendimento = new Set<Id>();
    
        for (TabelaVendas__c iTab : tabelas) {
            if (iTab.Name != null) {
                setNome.add(iTab.Name);
            }
            if (iTab.Empreendimento__c != null) {
                setEmpreendimento.add(iTab.Empreendimento__c);
            }
        }
    
        List<TabelaVendas__c> existingTabelas = [
            SELECT 
                Id, 
                Name, 
                Ativo__c, 
                VigenciaInicio__c, 
                VigenciaFim__c, 
                Empreendimento__c
            FROM TabelaVendas__c
            WHERE 
                Name IN :setNome 
                OR 
                Empreendimento__c IN :setEmpreendimento
        ];
    

        if (existingTabelas.isEmpty()) {
            return;

        }

        for (TabelaVendas__c iTab : tabelas) {
            if (iTab.Name == null) {
                continue;
            }
    
            if (iTab.Id == null) {
                if (!existingTabelas.isEmpty()) {
                    for (TabelaVendas__c existingTab : existingTabelas) {
                        if (existingTab.Name == iTab.Name && existingTab.Id != iTab.Id) {
                            throw new AuraHandledException('Já existe uma tabela de vendas ativa com este nome.');
                        }
                    }
    
                    for (TabelaVendas__c existingTab : existingTabelas) {
                        if (existingTab.Empreendimento__c == iTab.Empreendimento__c && existingTab.Id != iTab.Id) {
                            if (iTab.VigenciaInicio__c <= existingTab.VigenciaFim__c && iTab.VigenciaFim__c >= existingTab.VigenciaInicio__c) {
                                throw new AuraHandledException('As datas de vigência não podem se sobrepor às datas de uma tabela existente para o mesmo empreendimento com o mesmo tipo de venda.');
                            }
                            if (iTab.Ativo__c == true && iTab.Id == null) {
                                throw new AuraHandledException('A tabela só deve ser ativada após ela ser criada.');
                            }
                        }
                    }
                }
            }
        }
    }
}