force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/ValorMetroQuadrado__c.field-meta.xml
<CustomField>
    <fullName>ValorMetroQuadrado__c</fullName>
    <label>Valor (m²)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MetragemDaUnidadeM__c.field-meta.xml
<CustomField>
    <fullName>MetragemDaUnidadeM__c</fullName>
    <label>Metragem da Unidade (m²)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ValorVaga__c.field-meta.xml
<CustomField>
    <fullName>ValorVaga__c</fullName>
    <label>Valor Vaga</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Unidade.recordType-meta.xml
<RecordType>
    <fullName>Unidade</fullName>
    <active>true</active>
    <label>Unidade</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Vaga.recordType-meta.xml
<RecordType>
    <fullName>Vaga</fullName>
    <active>true</active>
    <label>Vaga</label>
</RecordType>

force-app/main/default/classes/Product2ControllerTest.cls
@isTest
private class Product2ControllerTest {

    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData(){

        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Empreendimento',
            CNPJ__c = '10155540000106',
            ValorMetroQuadrado__c  = 300000.0
        );

        insert empreendimento;

        Id vagaRecordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Vaga' AND SObjectType = 'Product2' LIMIT 1].Id;
        Id unidadeRecordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Unidade' AND SObjectType = 'Product2' LIMIT 1].Id;

        insert new List<Product2>{
            new Product2(
                Name = 'Unidade 1',
                Empreendimento__c = empreendimento.Id,
                RecordTypeId = unidadeRecordType,
                MetragemDaUnidadeM__c = 30
            ),
            new Product2(
                Name = 'Vaga 1',
                Empreendimento__c = empreendimento.Id,
                RecordTypeId = vagaRecordType,
                ValorVaga__c = 200000.0
            ),
            new Product2(
                Name = 'Vaga 2',
                Empreendimento__c = empreendimento.Id,
                RecordTypeId = vagaRecordType,
                ValorVaga__c = 300000.0
            )
        };
    }

    @isTest
    static void getVagasGaragemTest() {
        Id vagaRecordType = [SELECT Id FROM RecordType WHERE DeveloperName = 'Vaga' AND SObjectType = 'Product2' LIMIT 1].Id;
        Id empreendimentoId = [SELECT Id FROM Empreendimento__c LIMIT 1].Id;
        
        List<Product2> vagas = [SELECT Id FROM Product2 WHERE RecordTypeId = :vagaRecordType];
        List<Product2> vagasToTest = Product2Controller.getVagasGaragem(empreendimentoId);
        
        Assert.areEqual(vagas.size(), vagasToTest.size());
    }
}