force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/Generico__c.field-meta.xml
<CustomField>
    <fullName>Generico__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Genérico</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DataHoraAtualizacaoFase__c.field-meta.xml
<CustomField>
    <fullName>DataHoraAtualizacaoFase__c</fullName>
    <label>Data/Hora Atualização de Fase</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDDCelular__c.field-meta.xml
<CustomField>
    <fullName>DDDCelular__c</fullName>
    <label>DDD Celular</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDICelular__c.field-meta.xml
<CustomField>
    <fullName>DDICelular__c</fullName>
    <label>DDI Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <description>Empreendimento Interessado</description>
    <label>Empreendimento</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/isPJ__c.field-meta.xml
<CustomField>
    <fullName>isPJ__c</fullName>
    <defaultValue>false</defaultValue>
    <label>É PJ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/LeadNaoQuisVisitar__c.field-meta.xml
<CustomField>
    <fullName>LeadNaoQuisVisitar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead não quis visitar empreendimento</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaAtual__c.field-meta.xml
<CustomField>
    <fullName>MidiaAtual__c</fullName>
    <label>Mídia Atual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Midia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaOriginal__c.field-meta.xml
<CustomField>
    <fullName>MidiaOriginal__c</fullName>
    <label>Mídia Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PrimeiraOrigem__c.field-meta.xml
<CustomField>
    <fullName>PrimeiraOrigem__c</fullName>
    <label>Primeira Origem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PrimeiroEmpreendimento__c.field-meta.xml
<CustomField>
    <fullName>PrimeiroEmpreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primeiro Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads (Primeiro Empreendimento)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ResponsavelPeloLead__c.field-meta.xml
<CustomField>
    <fullName>ResponsavelPeloLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsável pelo Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/TotalDeAtividadesFaseAtual__c.field-meta.xml
<CustomField>
    <fullName>TotalDeAtividadesFaseAtual__c</fullName>
    <label>Total de Atividades da Fase Atual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/LeadHelper.cls
public with sharing class LeadHelper {

    private static final List<String> STATUS_PICKLIST_VALUES = ObjectHelper.getPickListValuesList('Lead', 'Status');

    private static Id pfRecordTypeId = Schema.SObjectType.Lead
            .getRecordTypeInfosByName()
            .get('Pessoa Física')
            .getRecordTypeId();

    private static Id pjRecordTypeId = Schema.SObjectType.Lead
            .getRecordTypeInfosByName()
            .get('Pessoa Jurídica')
            .getRecordTypeId();

    public static void handleUpdate(List<Lead> leads, Map<Id,Lead> oldLeadsMap) {
        LeadSLAHelper.verifyLeadControlSLA(leads, oldLeadsMap); 
        resetNumberActivities(oldLeadsMap, leads);
        setFirstFields(leads);
        validatePipelineStatus(leads, oldLeadsMap);
        updateResponsavelPeloLead(leads);
    }

    private static void updateResponsavelPeloLead(List<Lead> leads) {
        for (Lead iLead : leads) {
            if (iLead.OwnerId != null && iLead.OwnerId.getSObjectType() == User.SObjectType) {
                iLead.ResponsavelPeloLead__c = iLead.OwnerId;
            }
        }
    }

    public static void handleNewLeads(List<Lead> leads) {
        assignInitialStatus(leads);
        LeadSLAHelper.verifyLeadControlSLA(leads, null);
        setLeadsRecordType(leads);
        setFirstFields(leads);
        updateResponsavelPeloLead(leads);
    }

    public static Boolean isPhoneEqual(Lead iLead, Lead jLead) {
        return String.join(
            new List<String>{
                iLead.DDITelefone__c,
                iLead.DDDTelefone__c,
                iLead.Phone
            },
            ' '
        ).equals(
            String.join(
                new List<String>{
                    jLead.DDITelefone__c,
                    jLead.DDDTelefone__c,
                    jLead.Phone
                },
                ' '
            )
        );
    }

    public static Boolean isMobilePhoneEqual(Lead iLead, Lead jLead) {
        return String.join(
            new List<String> {
                iLead.DDICelular__c,
                iLead.DDDCelular__c,
                iLead.Celular__c
            },
            ' '
        ).equals(
            String.join(
                new List<String>{
                    jLead.DDICelular__c,
                    jLead.DDDCelular__c,
                    jLead.Celular__c
                },
                ' '
            )
        );
    }

    private static void setLeadsRecordType(List<Lead> leads) {
        for(Lead iLead : leads) {
            if(iLead.RecordTypeId != null) continue;
            iLead.RecordTypeId = iLead.isPJ__c ? pjRecordTypeId : pfRecordTypeId;
        }
    }

    private static void validatePipelineStatus(List<Lead> leads, Map<Id,Lead> oldLeadsMap) {
        List<Lead> contactingStatusLeads = new List<Lead>();
        List<Lead> scheduledStatusLeads = new List<Lead>();
        List<Lead> convertedStatusLeads = new List<Lead>();

        for(Lead iLead : leads) {
            Lead oldLead = oldLeadsMap.get(iLead.Id);

            if(oldLead.Status == iLead.Status) continue;

            Integer statusGap = STATUS_PICKLIST_VALUES.indexOf(iLead.Status) - STATUS_PICKLIST_VALUES.indexOf(oldLead.Status);

            if(statusGap > 1 && oldLead.Status != 'Lost' && oldLead.Status != 'Unqualified') {
                iLead.addError('O lead pode avançar apenas uma etapa por vez');
                continue;
            }

            if(STATUS_PICKLIST_VALUES.indexOf(iLead.Status) > STATUS_PICKLIST_VALUES.indexOf(oldLead.Status)) {
                if(iLead.IsConverted) convertedStatusLeads.add(iLead);
                if(oldLead.Status == 'Contacting') contactingStatusLeads.add(iLead);
                else if(oldLead.Status == 'Scheduled') scheduledStatusLeads.add(iLead);
            }
        }

        validateContactTask(contactingStatusLeads);
        validateLeadsVisit(scheduledStatusLeads);
        validateConvertedLeadsActivities(convertedStatusLeads);
    }

    private static void assignInitialStatus(List<Lead> leads) {
        Set<Id> integrationUsersIds = new Map<Id,User>([
            SELECT 
                Id
            FROM User WHERE UserRole.DeveloperName = 'Integracao'
        ]).keySet();

        for(Lead iLead : leads) {
            if(!integrationUsersIds.contains(iLead.OwnerId)) {
                iLead.Status = 'Contacting';
            }else {
                iLead.Status = 'New';
            }
        }
    }
    
    private static void setFirstFields(List<Lead> leads){
        for(Lead iLead : leads) {
            setFirstFields(iLead, new Map<String, String>{
                'EmpreendimentoInteresse__c' => 'PrimeiroEmpreendimento__c',
                'MidiaAtual__c' => 'MidiaOriginal__c',
                'LeadSource' => 'PrimeiraOrigem__c'
            });
        }
    }

    private static void setFirstFields(Lead pLead, Map<String, String> pMapFromToFields) {
        Set<Id> setId = new Map<Id,Empreendimento__c>([
            SELECT
                Id
            FROM Empreendimento__c 
            WHERE Generico__c = true
        ]).keySet();

        for(String iFrom : pMapFromToFields.keySet()) {
            Object fromValue = pLead.get(iFrom);
            Object toValue = pLead.get(pMapFromToFields.get(iFrom));

            if (pMapFromToFields.get(iFrom) != 'PrimeiroEmpreendimento__c' && fromValue != null && toValue == null) {
                pLead.put(pMapFromToFields.get(iFrom), fromValue);
            }

            if (pLead.PrimeiroEmpreendimento__c == null && !setId.contains((Id) pLead.get('EmpreendimentoInteresse__c'))) {
                pLead.put('PrimeiroEmpreendimento__c', pLead.get('EmpreendimentoInteresse__c'));
            }
        }
    }

    private static void resetNumberActivities(Map<Id, Lead> oldLeadsMap, List<Lead> newLeads){
        for(Lead iLead : newLeads){

            if(iLead.Status != oldLeadsMap.get(iLead.Id).Status) {
                iLead.TotalDeAtividadesFaseAtual__c = 0;
                iLead.DataHoraAtualizacaoFase__c = Datetime.now();
            }
        }
    }

    private static void validateConvertedLeadsActivities(List<Lead> leads) {
        Set<Id> setContactId = ObjectHelper.getLookUpId(leads, 'ConvertedContactId');

        Map<Id,List<Task>> mapTasks = ActivityHelper.getActivitiesByWhoIdMap(
            TaskDA.getContactTasksByWhoIdAndStatus(new Set<String>{'WhoId'}, setContactId, 'Completed')  
        );

        Map<Id,List<Event>> mapEvents = ActivityHelper.getActivitiesByWhoIdMap(
            EventDA.getEventDoneByWhoId(new Set<String>{'WhoId'}, setContactId)
        );

        Set<Id> defaultEmpreendimentoSetId = new Map<Id,Empreendimento__c>([
            SELECT
                Id
            FROM Empreendimento__c 
            WHERE Generico__c = true
        ]).keySet();
                
        for(Lead iLead : leads) {
            if (defaultEmpreendimentoSetId.contains(iLead.EmpreendimentoInteresse__c)) {
                iLead.addError('O lead não pode avançar com um empreendimento genérico.');
                continue;
            }

            if(!iLead.LeadNaoQuisVisitar__c && !mapEvents.containsKey(iLead.ConvertedContactId)) {
                iLead.addError('O lead precisa ter um compromisso realizado com sucesso para ser convertido');
                continue;
            }

            if(!mapTasks.containsKey(iLead.ConvertedContactId)) 
                iLead.Status.addError('O lead não pode prosseguir para essa fase, pois não foi feito um contato');
        }
    }

    private static void validateLeadsVisit(List<Lead> leads){
        Map<Id,List<Event>> mapEvents = ActivityHelper.getActivitiesByWhoIdMap(
            EventDA.getEventDoneByWhoId(
                new Set<String>{'WhoId'},
                new Map<Id,Lead>(leads).keySet()
            )
        );

        Set<Id> defaultEmpreendimentoSetId = new Map<Id,Empreendimento__c>([
            SELECT
                Id
            FROM Empreendimento__c 
            WHERE Generico__c = true
        ]).keySet();
        
        for(Lead lead : leads) {
            if (defaultEmpreendimentoSetId.contains(lead.EmpreendimentoInteresse__c)) {
                lead.addError('O lead não pode avançar com um empreendimento genérico.');
            }

            if(!lead.LeadNaoQuisVisitar__c && !mapEvents.containsKey(lead.Id)) {
                lead.addError('O lead precisa ter um compromisso realizado com sucesso para avançar de fase');
            }
        }
    }

    private static void validateContactTask(List<Lead> leads){
        Map<Id, List<Task>> mapLeadTasks = ActivityHelper.getActivitiesByWhoIdMap(
            TaskDA.getContactTasksByWhoIdAndStatus(
                new Set<String>{'WhoId'},
                new Map<Id, Lead>(leads).keySet(),
                'Completed'
            )
        );

        for(Lead iLead : leads){
            if(!mapLeadTasks.containsKey(iLead.Id)) 
                iLead.Status.addError('O lead não pode prosseguir para essa fase, pois não foi feito um contato');
        }
    }
}