force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDDCelular__c.field-meta.xml
<CustomField>
    <fullName>DDDCelular__c</fullName>
    <label>DDD Celular</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDICelular__c.field-meta.xml
<CustomField>
    <fullName>DDICelular__c</fullName>
    <label>DDI Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <description>Empreendimento Interessado</description>
    <label>Empreendimento</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaAtual__c.field-meta.xml
<CustomField>
    <fullName>MidiaAtual__c</fullName>
    <label>Mídia Atual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Midia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/TotalDeAtividadesFaseAtual__c.field-meta.xml
<CustomField>
    <fullName>TotalDeAtividadesFaseAtual__c</fullName>
    <label>Total de Atividades da Fase Atual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EventTriggerHandlerTest.cls
@isTest
public class EventTriggerHandlerTest {
    @TestSetup
    static void makeData() {
        doCreateData();
    }  

    private static void doCreateData() {
        // Criando um Empreendimento para associar ao Lead
        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Empreendimento Teste',
            CNPJ__c = '12345678000195' // CNPJ válido
        );
        insert empreendimento;

        // Criando o Lead com os campos obrigatórios CPF/CNPJ e Empreendimento preenchidos
        List<Lead> leads = new List<Lead> {
            new Lead(
                LastName = 'Teste',
                Company = 'Teste',
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '16',
                Phone = '18845-6789',
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '16',
                Celular__c = '18845-6789',
                Status = 'Scheduled',
                TotalDeAtividadesFaseAtual__c = 0,
                MidiaAtual__c = 'Instagram',
                LeadSource = 'Instagram',
                CPF__c = '12345678909', // Preenchendo o campo CPF válido
                EmpreendimentoInteresse__c = empreendimento.Id // Associando o Lead a um Empreendimento
            )
        };

        insert leads;
    }

    @isTest
    public static void validateEventLookupTest() {
        Lead scheduledLead = [SELECT Id FROM Lead].get(0);

        Event event = new Event(
            Subject = 'Teste',
            ActivityDate = Date.today(),
            DurationInMinutes = 60,
            ActivityDateTime = Datetime.now(),
            WhoId = scheduledLead.Id
        );

        Test.startTest();
        insert event;
        Test.stopTest();

        Assert.isFalse(event.hasErrors());
    }

    @IsTest
    private static void afterDeleteTest() {
        Lead lead = [SELECT Id, TotalDeAtividadesFaseAtual__c FROM Lead].get(0);

        Event events = new Event(
            Subject = 'Teste',
            ActivityDate = Date.today(),
            DurationInMinutes = 60,
            ActivityDateTime = Datetime.now(),
            WhoId = lead.Id
        );

        Test.startTest();
        insert events;
        delete events;
        Test.stopTest();

        System.debug(lead.TotalDeAtividadesFaseAtual__c);
        Assert.isTrue(lead.TotalDeAtividadesFaseAtual__c == 0);
    }
}