force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indique se o empreendimento está disponível para venda de unidades.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/MetragemPrivativaTotal__c.field-meta.xml
<CustomField>
    <fullName>MetragemPrivativaTotal__c</fullName>
    <label>Metragem Privativa Total (m²)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/VagasUnidade__c.field-meta.xml
<CustomField>
    <fullName>VagasUnidade__c</fullName>
    <label>Vagas por Unidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/ValorM__c.field-meta.xml
<CustomField>
    <fullName>ValorM__c</fullName>
    <description>Valor do metro quadrado do empreendimento.</description>
    <label>Valor (m²)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Cotacao__c.field-meta.xml
<CustomField>
    <fullName>Cotacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotação</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PercentualDeAcrescimo__c.field-meta.xml
<CustomField>
    <fullName>PercentualDeAcrescimo__c</fullName>
    <inlineHelpText>Percentual (%) que será acrescido no valor das Unidades</inlineHelpText>
    <label>Percentual de acréscimo (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/Situacao__c.field-meta.xml
<CustomField>
    <fullName>Situacao__c</fullName>
    <formula>IF(
    AND(
        TODAY() &gt;= DataInicio__c ,
        TODAY() &lt;= DataFim__c
    ),
    &quot;Em vigor&quot;,
    &quot;Suspensa&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Em vigor- Dentro da vigência / Suspensa - Fora da vigência</inlineHelpText>
    <label>Situação</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/TaxaDescontoVPL__c.field-meta.xml
<CustomField>
    <fullName>TaxaDescontoVPL__c</fullName>
    <label>Taxa desconto VPL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/TaxaTP__c.field-meta.xml
<CustomField>
    <fullName>TaxaTP__c</fullName>
    <label>Taxa TP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/VigenciaFim__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFim__c</fullName>
    <label>Vigência fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/VigenciaInicio__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicio__c</fullName>
    <label>Vigência início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/UnidadeTabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Entrada de Preço</label>
    <nameField>
        <label>Nome de Unidade da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entrada de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipName>Unidades_da_Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TabelaVendaSelector.cls
public class TabelaVendaSelector {
    public static List<UnidadeTabelaVendas__c> obterUnidadeTabelasPorId (Id tabelaVendasId) {
        return [
            SELECT PrecoLista__c
            FROM UnidadeTabelaVendas__c
            WHERE TabelaVenda__c = :tabelaVendasId
            LIMIT 1
        ];
    }

    public static TabelaVendas__c obterTabelasRelacionadas(Id tabelaRelacionada){
        return [
            SELECT
                Id,
                // Empreendimento__r.ValorM__c,
                Empreendimento__r.MetragemPrivativaTotal__c
            FROM TabelaVendas__c
            WHERE Id = :tabelaRelacionada LIMIT 1
        ];
    }

    public static List<TabelaVendas__c> obterTabelasPorIdEmpreendimento(Id idEmpreendimento) {
        return [
            SELECT Id, 
                   Name,
                   Situacao__c,
                   Ativo__c,
                   VigenciaInicio__c,
                   VigenciaFim__c,
                   TaxaDescontoVPL__c,
                   Empreendimento__r.VagasUnidade__c,
                   TaxaTP__c
            FROM   TabelaVendas__c
            WHERE  Empreendimento__c  = :idEmpreendimento
        ];
    }

    public static List<TabelaVendas__c> obterCotacaoRelacionada(Id idCotacao){
        system.debug('id cotacao no selector' + idCotacao);
        return [
            SELECT
                Id,
                Cotacao__c
            FROM TabelaVendas__c
            WHERE Cotacao__c = :idCotacao
            ORDER BY Cotacao__c DESC
            LIMIT 1
        ];
    }

    public static TabelaVendas__c buscarTabelaPorIdCotacao(Id idCotacao){
        List<TabelaVendas__c> result = [
            SELECT Id 
            FROM TabelaVendas__c 
            WHERE Cotacao__c = :idCotacao 
            LIMIT 1
        ];
        
        return result.isEmpty() ? null : result[0];
    }

    public static TabelaVendas__c  obterCamposParaCloneTabela( Id idTabelaVenda){
        System.debug('id tabela venda no selector' + idTabelaVenda);

        return [
        SELECT Id,
        Name, 
        VigenciaInicio__c, 
        VigenciaFim__c,
        PercentualDeAcrescimo__c 
        FROM TabelaVendas__c 
        WHERE Id = :idTabelaVenda 
        LIMIT 1
        ];
    }
    
}