force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/MetragemPrivativaTotal__c.field-meta.xml
<CustomField>
    <fullName>MetragemPrivativaTotal__c</fullName>
    <label>Metragem Privativa Total (m²)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <referenceTo>UnidadeTabelaVendas__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Unidade.recordType-meta.xml
<RecordType>
    <fullName>Unidade</fullName>
    <active>true</active>
    <label>Unidade</label>
</RecordType>

force-app/main/default/objects/SeriePagamentos__c/SeriePagamentos__c.object-meta.xml
<CustomObject>
    <label>Série de Pagamentos</label>
    <nameField>
        <label>Nome de Série de Pagamentos</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Series de Pagamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SeriePagamentos__c/fields/AposHabiteSe__c.field-meta.xml
<CustomField>
    <fullName>AposHabiteSe__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Após a data de entrega do empreendimento</inlineHelpText>
    <label>Após Habite-se</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/InicioPagamento__c.field-meta.xml
<CustomField>
    <fullName>InicioPagamento__c</fullName>
    <inlineHelpText>Numeral, em meses. Se for &quot;0&quot;, significa hoje. Se for &quot;40&quot;, significa &quot;daqui a 40 meses&quot; a partir de hoje</inlineHelpText>
    <label>Início de Pagamento</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/QuantidadeParcelas__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeParcelas__c</fullName>
    <label>Quantidade de Parcelas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipLabel>Series de Pagamentos</relationshipLabel>
    <relationshipName>SeriesPagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/TipoCondicao__c.field-meta.xml
<CustomField>
    <fullName>TipoCondicao__c</fullName>
    <label>Tipo de Condição</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TiposCondicoes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/ValorTotal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotal__c</fullName>
    <label>Valor total (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SeriePagamentos__c/fields/ValorTotalNominal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotalNominal__c</fullName>
    <label>Valor Total Nominal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/UnidadeTabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Entrada de Preço</label>
    <nameField>
        <label>Nome de Unidade da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entrada de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipName>Unidades_da_Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entrada de Preços</relationshipLabel>
    <relationshipName>UnidadesTabelaVendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/TiposCondicoes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ato</fullName>
    </customValue>
    <customValue>
        <fullName>Sinal</fullName>
    </customValue>
    <customValue>
        <fullName>Mensais</fullName>
    </customValue>
    <customValue>
        <fullName>Semestrais</fullName>
    </customValue>
    <customValue>
        <fullName>Anuais</fullName>
    </customValue>
    <customValue>
        <fullName>Única</fullName>
    </customValue>
    <customValue>
        <fullName>Financiamento</fullName>
    </customValue>
    <customValue>
        <fullName>Periódica</fullName>
    </customValue>
    <customValue>
        <fullName>Bimestral</fullName>
    </customValue>
    <customValue>
        <fullName>Trimestral</fullName>
    </customValue>
    <masterLabel>Tipos de Condições</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ComparativoServiceTest.cls
@isTest
public with sharing class ComparativoServiceTest {
    @TestSetup
    static void makeData(){

        Empreendimento__c empreendimento = TestDataFactory.gerarEmpreendimento();
        empreendimento.MetragemPrivativaTotal__c = 100;
        empreendimento.CNPJ__c = '41956129000155';
        insert empreendimento;

        Product2 produto = TestDataFactory.gerarProduto();
        produto.Empreendimento__c = empreendimento.Id;
        insert produto;


        TabelaVendas__c tabela = TestDataFactory.gerarTabelaVendas();
        tabela.Empreendimento__c = empreendimento.id;
        insert tabela;

        UnidadeTabelaVendas__c entradaPreco = TestDataFactory.gerarUnidadeTabelaVendas(tabela.Id);
        entradaPreco.Unidade__c = produto.Id;
        insert entradaPreco;

        SeriePagamentos__c serie = TestDataFactory.gerarSeriePagamento(tabela.Id);
        insert serie;
    }

    @isTest
    public static void testCalcularComparacao() {
        TabelaVendas__c tabela = [SELECT Id, Name FROM TabelaVendas__c LIMIT 1];
        UnidadeTabelaVendas__c unidade = [SELECT Id, Name FROM UnidadeTabelaVendas__c WHERE Name = 'UnidadeVendaTeste' LIMIT 1];
        List<SeriePagamentos__c> series = [SELECT Id, Name,InicioPagamento__c, QuantidadeParcelas__c, ValorTotal__c, TabelaVenda__c, TipoCondicao__c, AposHabiteSe__c, ValorTotalNominal__c FROM SeriePagamentos__c];
    
        Test.startTest();
        List<Object> comparativo = ComparativoService.calcularComparacao(unidade.Id, tabela.Id, series);
        Test.stopTest();

        Assert.areEqual(true, (comparativo.size() > 0), 'A lista não pode estar vazia');
    }
}