force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <label>Bairro</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/Uf__c.field-meta.xml
<CustomField>
    <fullName>Uf__c</fullName>
    <label>UF</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmpreendimentoHelper.cls
public with sharing class EmpreendimentoHelper {

    @future(callout=true)
    public static void getCEPDataAsyncFuture(String cep) {
        getCEPDataAsync(cep);
    }
    
    public static void getCEPDataAsync(String cep) {
        ViaCEPResponse cepResponse = null;
        try {
            String baseURL = 'https://viacep.com.br/ws/';
            String requestURL = baseURL + cep + '/json/';
    
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(requestURL);
            request.setMethod('GET');
    
            HttpResponse response = http.send(request);
    
            if (response.getStatusCode() == 200) {
                cepResponse = (ViaCEPResponse)JSON.deserialize(response.getBody(), ViaCEPResponse.class);
            } else {
                System.debug('Erro: ' + response.getStatus());
            }
        } catch (Exception e) {
            System.debug('Exception: ' + e.getMessage());
        }
    
        if (cepResponse != null) {
            updateEmpreendimentoWithCEP(cep, cepResponse);
        }
    }

    public static List<EmpreendimentoResponse> getEmpreendimentosResponse() {
        List<EmpreendimentoResponse> empreendimentosResponse = new List<EmpreendimentoResponse>();

        for(Empreendimento__c e : [SELECT Id, Name FROM Empreendimento__c]) {
            empreendimentosResponse.add(new EmpreendimentoResponse(e));
        }

        return empreendimentosResponse;
    } 
    
    public static void updateEmpreendimentoWithCEP(String cep, ViaCEPResponse cepResponse) {
        List<Empreendimento__c> empreendimentosToUpdate = [SELECT Id
                                              FROM Empreendimento__c
                                              WHERE CEP__c = :cep];
    
        for (Empreendimento__c emp : empreendimentosToUpdate) {
            emp.Bairro__c = cepResponse.bairro;
            emp.Cidade__c = cepResponse.localidade;
            emp.UF__c = cepResponse.uf;
            emp.Logradouro__c = cepResponse.logradouro;
        }
    
        update empreendimentosToUpdate;
    }
}