force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indique o empreendimento em que se encontra esta unidade.</inlineHelpText>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Unidades</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <referenceTo>UnidadeTabelaVendas__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Unidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Tabela de Vendas</relationshipLabel>
    <relationshipName>Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/UnidadeTabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Entrada de Preço</label>
    <nameField>
        <label>Nome de Unidade da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entrada de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entrada de Preços</relationshipLabel>
    <relationshipName>UnidadesTabelaVendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TabelaVendaServiceTest.cls
@isTest
private class TabelaVendaServiceTest {
    
    @TestSetup
    static void makeData() {
        List<Empreendimento__c> empreendimentos = new List<Empreendimento__c> {
            TestDataFactory.gerarEmpreendimento(),
            TestDataFactory.gerarEmpreendimento()
        };

        insert empreendimentos;

        TabelaVendas__c tabela1 = TestDataFactory.gerarTabelaVendas();
        tabela1.Empreendimento__c = empreendimentos.get(0).Id;
        insert tabela1;

        TabelaVendas__c tabela2 = TestDataFactory.gerarTabelaVendas();
        tabela2.Empreendimento__c = empreendimentos.get(1).Id;
        insert tabela2;

        Product2 produto1 = TestDataFactory.gerarProduto();
        produto1.Empreendimento__c = empreendimentos.get(1).Id;
        insert produto1;

        Product2 produto2 = TestDataFactory.gerarProduto();
        produto2.Empreendimento__c = empreendimentos.get(0).Id;
        insert produto2;

        UnidadeTabelaVendas__c unidadeTabela = TestDataFactory.gerarUnidadeTabelaVendas(tabela2.id);
        unidadeTabela.Unidade__c = produto1.Id;
        insert unidadeTabela;

        insert TestDataFactory.gerarUnidadeTabelaVendas(tabela2.id);
    }

    @isTest
    private static void getTabelaVendaTest() {
        Assert.isFalse(!true);
    }
}