force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDICelular__c.field-meta.xml
<CustomField>
    <fullName>DDICelular__c</fullName>
    <label>DDI Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <description>Empreendimento Interessado</description>
    <label>Empreendimento</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaAtual__c.field-meta.xml
<CustomField>
    <fullName>MidiaAtual__c</fullName>
    <label>Mídia Atual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Midia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/LeadTriggerTest.cls
@isTest
public class LeadTriggerTest {
    
    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData(){

        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Empreendimento',
            CNPJ__c = '32339125000137'
        );

        insert empreendimento;

        List<Lead> leads = new List<Lead>{
            new Lead(
                    LastName = 'Teste',
                    Company = 'Teste',
                    Email = 'teste@email.com',
                    MidiaAtual__c = 'Instagram',
                    LeadSource = 'Instagram',
                    Status = 'New',
                    DDICelular__c = null,
                    DDITelefone__c = null
                ),

                new Lead(
                    LastName = 'Teste',
                    Company = 'Teste',
                    Email = 'teste2@email.com',
                    MidiaAtual__c = 'Instagram',
                    LeadSource = 'Instagram',
                    Status = 'Scheduled',
                    DDICelular__c = null,
                    DDITelefone__c = null
                ),

                new Lead(
                    LastName = 'Teste',
                    Company = 'Teste',
                    Email = 'teste3@email.com',
                    MidiaAtual__c = 'Instagram',
                    LeadSource = 'Instagram',
                    CPF__c = '10020030088',
                    EmpreendimentoInteresse__c = empreendimento.Id,
                    Status = 'New',
                    DDICelular__c = null,
                    DDITelefone__c = null
                )
        };

        insert leads;

        Event event = new Event(
            Subject = 'Teste',
            ActivityDate = Date.today(),
            DurationInMinutes = 60,
            ActivityDateTime = Datetime.now(),
            WhoId = leads.get(1).Id,
            StatusVisita__c = 'Done'
        );

        insert event;

        insert new List<Task> {
            new Task(
                Subject = 'Call',
                Status = 'Completed',
                WhoId = leads.get(1).Id,
                ActivityDate = Date.today().addDays(1)
            ),
            new Task(
                Subject = 'Call',
                Status = 'Not Started',
                WhoId = leads.get(1).Id,
                ActivityDate = Date.today().addDays(1)
            ),
            new Task(
                Subject = 'Call',
                Status = 'Completed',
                WhoId = leads.get(2).Id,
                ActivityDate = Date.today().addDays(1)
            ),
            new Task(
                Subject = 'Call',
                Status = 'Not Started',
                WhoId = leads.get(2).Id,
                ActivityDate = Date.today().addDays(1)
            )
        };
    }
    
    @isTest
    public static void beforeUpdateTest(){
        List<Lead> leads = [SELECT Id, Status FROM Lead];

        leads.get(1).Status = 'Qualified';

        Test.startTest();
        TriggerHandler.bypass('LeadTriggerHandler');
        update leads;
        TriggerHandler.clearBypass('LeadTriggerHandler');
        Test.stopTest();

        Assert.isFalse(leads.get(0).hasErrors());
        Assert.isFalse(leads.get(1).hasErrors());
        Assert.isFalse(leads.get(2).hasErrors());
    }
}