force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <label>Bairro</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <label>Logradouro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Empreendimento__c/fields/Uf__c.field-meta.xml
<CustomField>
    <fullName>Uf__c</fullName>
    <label>UF</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmpreendimentoHelperTest.cls
@isTest
private class EmpreendimentoHelperTest {

    @TestSetup
    static void makeData() {
        doCreateData();
    }

    private static void doCreateData() {
        List<Empreendimento__c> emp = new List<Empreendimento__c>{
            new Empreendimento__c(
                Name = 'Test Empreendimento',
                CNPJ__c = '71273553000166',
                CEP__c = '76979970' // CNPJ e CEP no formato correto
            )
        };

        insert emp;
    }

    // Testando o método @future getCEPDataAsyncFuture
    @isTest
    static void testGetCEPDataAsyncFuture() {
        Test.startTest();
            EmpreendimentoHelper.getCEPDataAsyncFuture('01001000');
        Test.stopTest();
    }

    @isTest
    static void updateEmpreendimentoWithCEPTest() {
        Empreendimento__c empreendimentoParaAtualizar = new Empreendimento__c(
            Name = 'Empreendimento para Atualizar',
            CNPJ__c = '71273553000166',
            CEP__c = '68904620'
        );
        insert empreendimentoParaAtualizar;

        ViaCEPResponse viaCEPResponse = new ViaCEPResponse(
            '01001000', 'Praça da Sé', 'lado ímpar', 'Sé', 'São Paulo', 'SP', '3550308', '1004', '11', '7107'
        );

        Test.startTest();
            EmpreendimentoHelper.updateEmpreendimentoWithCEP('68904620', viaCEPResponse);
        Test.stopTest();

        Empreendimento__c empreendimentoAtualizado = [SELECT Id, Bairro__c, Cidade__c, UF__c, Logradouro__c FROM Empreendimento__c WHERE Id = :empreendimentoParaAtualizar.Id LIMIT 1];

        System.assertNotEquals(null, empreendimentoAtualizado.Bairro__c);
        System.assertNotEquals(null, empreendimentoAtualizado.Cidade__c);
        System.assertNotEquals(null, empreendimentoAtualizado.UF__c);
        System.assertNotEquals(null, empreendimentoAtualizado.Logradouro__c);
    }

    @isTest
    public static void getEmpreendimentosResponseTest() {
        List<EmpreendimentoResponse> empreendimentosResponse = EmpreendimentoHelper.getEmpreendimentosResponse();
        System.assertEquals(1, empreendimentosResponse.size(), 'Deve retornar 1 empreendimento');
        System.assertEquals('Test Empreendimento', empreendimentosResponse[0].razaoSocial, 'Nome do empreendimento deve ser "Test Empreendimento"');
    }
}