force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <description>Empreendimento Interessado</description>
    <label>Empreendimento</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaAtual__c.field-meta.xml
<CustomField>
    <fullName>MidiaAtual__c</fullName>
    <label>Mídia Atual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Midia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/TotalDeAtividadesFaseAtual__c.field-meta.xml
<CustomField>
    <fullName>TotalDeAtividadesFaseAtual__c</fullName>
    <label>Total de Atividades da Fase Atual</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/ActivityHelperTeste.cls
@isTest
public class ActivityHelperTeste {
    
    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData(){
        Empreendimento__c empreendimento = new Empreendimento__c (
            Name = 'Empreendimento Teste',
            CNPJ__c = '42318254000100'
        );

        insert empreendimento;
        
        Lead lead = new Lead(
            LastName = 'Zika',
            Company = 'Chave',
            Email = 'teste@email.com',
            LeadSource = 'Outros',
            MidiaAtual__c = 'Facebook Ads',
            CPF__c = '10020030088',
            EmpreendimentoInteresse__c = empreendimento.Id
        );


        insert lead;

        insert new List<Task> {
            new Task(
                Subject = 'Call',
                Status = 'Completed',
                WhoId = lead.Id,
                ActivityDate = Date.today().addDays(1)
            ),
            new Task(
                Subject = 'Call',
                Status = 'Not Started',
                WhoId = lead.Id,
                ActivityDate = Date.today().addDays(1)
            )
        };

        insert new Event(
            Subject = 'Teste',
            ActivityDate = Date.today(),
            DurationInMinutes = 60,
            ActivityDateTime = Datetime.now(),
            WhoId = lead.Id
        );
    }

    @IsTest
    private static void updateTotalLeadActivitiesTest(){
        List<SObject> activities = new List<SObject>();
        activities.add([SELECT Id, WhoId FROM Event].get(0));
        activities.add([SELECT Id, WhoId FROM Task].get(0));

        Test.startTest();
        ActivityHelper.updateTotalLeadActivities(activities);
        Test.stopTest();

        Lead lead = [SELECT Id, TotalDeAtividadesFaseAtual__c FROM Lead].get(0);
        Assert.isTrue(lead.TotalDeAtividadesFaseAtual__c == 3, 'O lead deve ter três atividades no contador');
    }

    @isTest
    private static void getActivitiesByWhoIdMapTest() {
        Id idLead = [SELECT Id FROM Lead LIMIT 1].Id;

        List<Task> tasks = [SELECT WhoId FROM Task WHERE WhoId = :idLead];
        List<Event> events = [SELECT WhoId FROM Event WHERE WhoId = :idLead];

        Map<Id,List<SObject>> expectedTaskMap = new Map<Id,List<SObject>>();
        expectedTaskMap.put(idLead, tasks);

        Map<Id,List<SObject>> expectedEventMap = new Map<Id,List<SObject>>();
        expectedEventMap.put(idLead, events);

        Test.startTest();
            Map<Id,List<SObject>> actualTaskMap = ActivityHelper.getActivitiesByWhoIdMap(tasks);
            Map<Id, List<SObject>> actualEventMap = ActivityHelper.getActivitiesByWhoIdMap(events);
        Test.stopTest();

        Assert.areEqual(expectedEventMap.get(idLead), actualEventMap.get(idLead));
        Assert.areEqual(expectedTaskMap.get(idLead), actualTaskMap.get(idLead));
    }
}