force-app/main/default/objects/ConfiguracaoChecklistDocumentos__mdt/ConfiguracaoChecklistDocumentos__mdt.object-meta.xml
<CustomObject>
    <label>Configuracão Checklist Documentos</label>
    <pluralLabel>Configuracões Checklist Documentos</pluralLabel>
</CustomObject>

force-app/main/default/objects/ConfiguracaoChecklistDocumentos__mdt/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoChecklistDocumentos__mdt/fields/CampoConta__c.field-meta.xml
<CustomField>
    <fullName>CampoConta__c</fullName>
    <label>Campo da conta</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoChecklistDocumentos__mdt/fields/LabelCampo__c.field-meta.xml
<CustomField>
    <fullName>LabelCampo__c</fullName>
    <label>Label do campo</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfiguracaoChecklistDocumentos__mdt/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <label>Tipo do Documento</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ExtensoesDocumentosChecklist__mdt/ExtensoesDocumentosChecklist__mdt.object-meta.xml
<CustomObject>
    <label>Extensão documentos checklist</label>
    <pluralLabel>Extensões documentos checklist</pluralLabel>
</CustomObject>

force-app/main/default/objects/ExtensoesDocumentosChecklist__mdt/fields/Extensao__c.field-meta.xml
<CustomField>
    <fullName>Extensao__c</fullName>
    <label>Extensão</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/TipoDocumento__c.object-meta.xml
<CustomObject>
    <label>Tipo de Documento</label>
    <nameField>
        <label>Nome do Tipo de Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Documento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DocumentosChecklistSelector.cls
public class DocumentosChecklistSelector {
    @AuraEnabled(cacheable=true)
    public static List<ConfiguracaoChecklistDocumentos__mdt> buscarConfiguracoesDocumentosChecklist() {
        return [SELECT Ativo__c, CampoConta__c, TipoDocumento__c, LabelCampo__c FROM ConfiguracaoChecklistDocumentos__mdt];
    }

    public static List<ExtensoesDocumentosChecklist__mdt> buscarExtensoesPermitidasDocumentosChecklist() {
        return [SELECT Extensao__c FROM ExtensoesDocumentosChecklist__mdt];
    }
}