force-app/main/default/objects/ConfiguracoesDeNegocio__c/ConfiguracoesDeNegocio__c.object-meta.xml
<CustomObject>
    <label>Configurações de Negócio</label>
    <nameField>
        <label>Nome de Configurações de Negócio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações de Negócio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/FaseParaRedirecionamentoDoLead__c.field-meta.xml
<CustomField>
    <fullName>FaseParaRedirecionamentoDoLead__c</fullName>
    <inlineHelpText>Fase do Lead após o vencimento do SLA.</inlineHelpText>
    <label>Fase para redirecionamento do Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Contacting</fullName>
                <label>Tentando Contato</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <label>Contato Realizado</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Agendamento</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <label>Convertido</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <label>Lead perdido</label>
            </value>
            <value>
                <fullName>Unqualified</fullName>
                <label>Não qualificado</label>
            </value>
            <value>
                <fullName>VisitDone</fullName>
                <label>Visita Realizada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/FilaParaRedirecionamentoDoLead__c.field-meta.xml
<CustomField>
    <fullName>FilaParaRedirecionamentoDoLead__c</fullName>
    <inlineHelpText>Fila de redirecionamento de Leads perdidos.</inlineHelpText>
    <label>Fila para redirecionamento do Lead</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ConfiguracaoDeSLA__c.field-meta.xml
<CustomField>
    <fullName>ConfiguracaoDeSLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuração de SLA</label>
    <referenceTo>ConfiguracoesDeNegocio__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadVencidoHelper.cls
public with sharing class LeadVencidoHelper {

    private static LeadVencidoHelper instance = new LeadVencidoHelper();
    public static LeadVencidoHelper getInstance(){
        return instance;
    }

    public void atualizaLeadVencido(List<Lead> leads) {
        Map<String, Id> filaNameToIdMap = new Map<String, Id>();
        List<Lead> leadsToUpdate = new List<Lead>();
        for (Lead lead : leads) {
            if (!String.isEmpty(lead.ConfiguracaoDeSLA__c) && !String.isEmpty(lead.ConfiguracaoDeSLA__r.FilaParaRedirecionamentoDoLead__c)) {
                filaNameToIdMap.put(lead.ConfiguracaoDeSLA__r.FilaParaRedirecionamentoDoLead__c, null);
            }
        }

        if (!filaNameToIdMap.isEmpty()) {
            for (Group fila : [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND Name IN :filaNameToIdMap.keySet()]) {
                filaNameToIdMap.put(fila.Name, fila.Id);
            }
        }

        for (Lead lead : leads) {
            Lead leadUpdate = new Lead();
            Boolean updateLead = false;
            leadUpdate.Id = lead.Id;
            if (filaNameToIdMap.containsKey(lead.ConfiguracaoDeSLA__r.FilaParaRedirecionamentoDoLead__c)) {
                leadUpdate.OwnerId = filaNameToIdMap.get(lead.ConfiguracaoDeSLA__r.FilaParaRedirecionamentoDoLead__c);
                updateLead = true;
            }

            if (!String.isEmpty(lead.ConfiguracaoDeSLA__c)) {
                leadUpdate.Status = lead.ConfiguracaoDeSLA__r.FaseParaRedirecionamentoDoLead__c;
                System.debug(lead.ConfiguracaoDeSLA__r.FaseParaRedirecionamentoDoLead__c);
                updateLead = true;
            }
            if(updateLead) leadsToUpdate.add(leadUpdate);
        }

        if(leadsToUpdate.isEmpty()) return;

        TriggerHandler.bypass('LeadTriggerHandler');
        
        update leadsToUpdate;

        TriggerHandler.clearBypass('LeadTriggerHandler');

    }
}