force-app/main/default/objects/ConfiguracoesDeNegocio__c/ConfiguracoesDeNegocio__c.object-meta.xml
<CustomObject>
    <label>Configurações de Negócio</label>
    <nameField>
        <label>Nome de Configurações de Negócio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações de Negócio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <inlineHelpText>Fase atual do Lead.</inlineHelpText>
    <label>Fase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Contacting</fullName>
                <label>Tentando Contato</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <label>Contato Realizado</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Agendamento</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <label>Convertido</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <label>Lead Perdido</label>
            </value>
            <value>
                <fullName>Unqualified</fullName>
                <label>Não Qualificado</label>
            </value>
            <value>
                <fullName>VisitDone</fullName>
                <label>Visita Realizada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/FaseParaRedirecionamentoDoLead__c.field-meta.xml
<CustomField>
    <fullName>FaseParaRedirecionamentoDoLead__c</fullName>
    <inlineHelpText>Fase do Lead após o vencimento do SLA.</inlineHelpText>
    <label>Fase para redirecionamento do Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Contacting</fullName>
                <label>Tentando Contato</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <label>Contato Realizado</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Agendamento</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <label>Convertido</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <label>Lead perdido</label>
            </value>
            <value>
                <fullName>Unqualified</fullName>
                <label>Não qualificado</label>
            </value>
            <value>
                <fullName>VisitDone</fullName>
                <label>Visita Realizada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/FilaParaRedirecionamentoDoLead__c.field-meta.xml
<CustomField>
    <fullName>FilaParaRedirecionamentoDoLead__c</fullName>
    <inlineHelpText>Fila de redirecionamento de Leads perdidos.</inlineHelpText>
    <label>Fila para redirecionamento do Lead</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/TempoDeSLA__c.field-meta.xml
<CustomField>
    <fullName>TempoDeSLA__c</fullName>
    <inlineHelpText>Define a qualidade esperada de um serviço,
tempo estabelecido em minutos.</inlineHelpText>
    <label>Tempo de SLA</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Celular__c.field-meta.xml
<CustomField>
    <fullName>Celular__c</fullName>
    <label>Celular</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DDDCelular__c.field-meta.xml
<CustomField>
    <fullName>DDDCelular__c</fullName>
    <label>DDD Celular</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DDDTelefone__c.field-meta.xml
<CustomField>
    <fullName>DDDTelefone__c</fullName>
    <label>DDD Telefone</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DDICelular__c.field-meta.xml
<CustomField>
    <fullName>DDICelular__c</fullName>
    <label>DDI Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/DDITelefone__c.field-meta.xml
<CustomField>
    <fullName>DDITelefone__c</fullName>
    <label>DDI Telefone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Corretor.recordType-meta.xml
<RecordType>
    <fullName>Corretor</fullName>
    <active>true</active>
    <description>Tipo de Registro criado para controlar o cadastro dos corretores parceiros</description>
    <label>Corretor</label>
</RecordType>

force-app/main/default/objects/Empreendimento__c/Empreendimento__c.object-meta.xml
<CustomObject>
    <label>Empreendimento</label>
    <nameField>
        <label>Nome de Empreendimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empreendimentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Empreendimento__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ConfiguracaoDeSLA__c.field-meta.xml
<CustomField>
    <fullName>ConfiguracaoDeSLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuração de SLA</label>
    <referenceTo>ConfiguracoesDeNegocio__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Corretor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <inlineHelpText>Digite apenas números.</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDDCelular__c.field-meta.xml
<CustomField>
    <fullName>DDDCelular__c</fullName>
    <label>DDD Celular</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDICelular__c.field-meta.xml
<CustomField>
    <fullName>DDICelular__c</fullName>
    <label>DDI Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Empreendimento__c.field-meta.xml
<CustomField>
    <fullName>Empreendimento__c</fullName>
    <description>Empreendimento Interessado</description>
    <label>Empreendimento</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/EmpreendimentoInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentoInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/FaixaInvestimento__c.field-meta.xml
<CustomField>
    <fullName>FaixaInvestimento__c</fullName>
    <label>Faixa de Investimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>R$ 300 Mil a R$ 999 Mil</fullName>
            </value>
            <value>
                <fullName>R$ 1 Milhão a R$ 1,9 Milhões</fullName>
            </value>
            <value>
                <fullName>R$ 2 Milhões a R$ 3,9 Milhões</fullName>
            </value>
            <value>
                <fullName>R$ 4 Milhões a R$ 5,9 Milhões</fullName>
            </value>
            <value>
                <fullName>Acima de R$ 6 Milhões</fullName>
            </value>
            <value>
                <fullName>Não definido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaAtual__c.field-meta.xml
<CustomField>
    <fullName>MidiaAtual__c</fullName>
    <label>Mídia Atual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Midia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaOriginal__c.field-meta.xml
<CustomField>
    <fullName>MidiaOriginal__c</fullName>
    <label>Mídia Original</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PrimeiraOrigem__c.field-meta.xml
<CustomField>
    <fullName>PrimeiraOrigem__c</fullName>
    <label>Primeira Origem</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PrimeiroEmpreendimento__c.field-meta.xml
<CustomField>
    <fullName>PrimeiroEmpreendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primeiro Empreendimento</label>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Leads (Primeiro Empreendimento)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/PessoaFisica.recordType-meta.xml
<RecordType>
    <fullName>PessoaFisica</fullName>
    <active>true</active>
    <businessProcess>Processo de Lead</businessProcess>
    <label>Pessoa Física</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/LeadHelperTest.cls
@isTest
private class LeadHelperTest {

    @TestSetup
    static void makeData() {
        doCreateData();
    }

    private static void doCreateData() {
        
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            Id idRole = [SELECT Id FROM UserRole WHERE UserRole.DeveloperName = 'Integracao'].Id;
            Id idProfile = [SELECT Id FROM Profile WHERE (Name = 'Usuário Padrão') OR (Name = 'Standard User') LIMIT 1].Id;

            insert new User(
                FirstName = 'Ricardo',
                LastName = 'Doe',
                Email = 'ricardo@testemail.com',
                Username = 'ricardo@testemail.com',
                Alias = 'rdoe',
                ProfileId = idProfile,
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                UserRoleId = idRole,
                LanguageLocaleKey = 'en_US'
            );

            Group testGroup = new Group(Name='Fila perdidos', Type='Queue');
            insert testGroup;
            insert new QueueSObject(QueueID = testGroup.id, SObjectType = 'Lead');
        }

        Empreendimento__c empreendimento = new Empreendimento__c(
            Name = 'Empreendimento',
            CNPJ__c = '21268544000109'
        );

        insert empreendimento;

        Contact contact = new Contact(
            FirstName = 'John',  // Preenchendo o primeiro nome obrigatório
            LastName = 'Doe',    // Preenchendo o sobrenome obrigatório
            Email = 'john.doe@testemail.com',
            RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Corretor'].get(0).Id
        );
        insert contact;

        insert new List<Lead>{
            new Lead(
                RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PessoaFisica'].get(0).Id,
                FirstName = 'Lead', // Adicionando FirstName para atender à regra de validação
                LastName = 'Teste',
                Company = 'Chave',
                Email = 'e@e.com',  
                LeadSource = 'Outros',
                MidiaAtual__c = 'Facebook Ads',
                DDDCelular__c = '19',
                DDICelular__c = 'Afeganistão (+93)',
                Celular__c = '12345-6789',
                DDDTelefone__c = '78',
                DDITelefone__c = 'Afeganistão (+93)',
                Phone = '12345-6789',
                Status = 'Qualified'
            ),

            new Lead(
                RecordTypeId = [SELECT Id FROM RecordType WHERE DeveloperName = 'PessoaFisica'].get(0).Id,
                LastName = 'test2',
                Company = 'Chave',
                LeadSource = 'Outros',
                MidiaAtual__c = 'Facebook Ads',
                Email = 'a@a.com',
                EmpreendimentoInteresse__c = empreendimento.Id,
                CPF__c = '70611982650',
                Corretor__c = contact.Id,
                FaixaInvestimento__c = 'R$ 300 Mil a R$ 999 Mil',
                DDDCelular__c = '11',
                DDICelular__c = 'Afeganistão (+93)',
                Celular__c = '12345-6789',
                DDDTelefone__c = '77',
                DDITelefone__c = 'Afeganistão (+93)',
                Phone = '12345-7789',
                Status = 'Qualified'
            )
        };

        insert new List<ConfiguracoesDeNegocio__c> {
            new ConfiguracoesDeNegocio__c(
                TempoDeSla__c = 1440,
                Fase__c = 'Qualified',
                FaseParaRedirecionamentoDoLead__c = 'Lost',
                FilaParaRedirecionamentoDoLead__c = 'Fila perdidos'
            ),

            new ConfiguracoesDeNegocio__c(
                TempoDeSla__c = 1440,
                Fase__c = 'Scheduled',
                FaseParaRedirecionamentoDoLead__c = 'Lost',
                FilaParaRedirecionamentoDoLead__c = 'Fila perdidos'
            ),

            new ConfiguracoesDeNegocio__c(
                TempoDeSla__c = 1440,
                Fase__c = 'Contacting',
                FaseParaRedirecionamentoDoLead__c = 'Lost',
                FilaParaRedirecionamentoDoLead__c = 'Fila perdidos'
            )
        };

    }

    @isTest
    private static void handleUpdateValidateStatusFailTest() {
        List<Lead> leads = [
            SELECT 
                Id,
                Status, 
                EmpreendimentoInteresse__c,
                PrimeiroEmpreendimento__c,
                MidiaAtual__c,
                MidiaOriginal__c,
                LeadSource,
                PrimeiraOrigem__c,
                IsConverted,
                Owner.Id
            FROM Lead
        ];

        Map<Id,Lead> leadsMap = new Map<Id,Lead>(leads);
        Map<Id,Lead> oldLeadsMap = leadsMap.deepClone();

        leads[0].Status = 'Qualified';

        Lead leadContacting = oldLeadsMap.get(leads[0].Id);

        leadContacting.Status = 'Contacting';

        oldLeadsMap.put(leadContacting.Id, leadContacting);

        Test.startTest();
            try {
                LeadHelper.handleUpdate(leads, oldLeadsMap);
            } catch(DmlException e) {
                System.debug(e);
            }
        Test.stopTest();

        Assert.isTrue(leads[0].hasErrors());
    }

    @isTest
    private static void handleUpdateValidateStatusSuccessTest() {
        List<Lead> leads = [
            SELECT 
                Id,
                Status, 
                EmpreendimentoInteresse__c,
                PrimeiroEmpreendimento__c,
                MidiaAtual__c,
                MidiaOriginal__c,
                LeadSource,
                Owner.Id,
                ConfiguracaoDeSLA__c,
                RecordTypeId,   
                PrimeiraOrigem__c
            FROM Lead
        ];

        Map<Id,Lead> leadsMap = new Map<Id,Lead>(leads);
        Map<Id,Lead> oldLeadsMap = leadsMap.deepClone();

        Lead leadScheduling = oldLeadsMap.get(leads[1].Id);
        leadScheduling.Status = 'Scheduled';
        oldLeadsMap.put(leadScheduling.Id, leadScheduling);

        leads[0].Status = 'Scheduled';

        Test.startTest();
            insert new List<Task> {
                new Task(
                    WhoId = leads[0].Id,
                    Subject = 'E-mail',
                    Status = 'Completed',
                    ActivityDate = Date.today().addDays(1)
                ),

                new Task(
                    WhoId = leads[1].Id,
                    Subject = 'E-mail',
                    Status = 'Completed',
                    ActivityDate = Date.today().addDays(1)
                ),

                new Task(
                    WhoId = leads[0].Id,
                    Subject = 'E-mail',
                    Status = 'Not Started',
                    ActivityDate = Date.today().addDays(1)
                ),

                new Task(
                    WhoId = leads[1].Id,
                    Subject = 'E-mail',
                    Status = 'Not Started',
                    ActivityDate = Date.today().addDays(1)
                )
            };



            TriggerHandler.bypass('LeadTriggerHandler');
            update oldLeadsMap.get(leads[1].Id);
            TriggerHandler.clearBypass('LeadTriggerHandler');

            
            insert new Event(
                WhoId = leads[1].Id,
                Type = 'Reunião',
                DurationInMinutes = 30,
                ActivityDateTime = Datetime.now()
            );

            leads[1].Status = 'Converted';

            LeadHelper.handleNewLeads(leads); // Agora passamos apenas a lista de Leads
        Test.stopTest();

        Assert.isFalse(leads[0].hasErrors());
        Assert.isFalse(leads[1].hasErrors());
        Assert.isTrue(leads[0].ConfiguracaoDeSLA__c != null);
    }

    @isTest
    private static void isMobilePhoneEqualTest() {
        List<Lead> leads = new List<Lead>{
            new Lead(
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '11',
                Celular__c = '1234-1234'
            ),
            new Lead(
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '11',
                Celular__c = '1234-1234'
            )
        };


        Assert.isTrue(LeadHelper.isMobilePhoneEqual(leads[0], leads[1]));
        leads[0].DDDCelular__c = '19';
        Assert.isFalse(LeadHelper.isMobilePhoneEqual(leads[0], leads[1]));
    }

    @isTest
    private static void isPhoneEqualTest() {
        List<Lead> leads = new List<Lead>{
            new Lead(
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '11',
                Phone = '1234-1234'
            ),
            new Lead(
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '11',
                Phone = '1234-1234'
            )
        };


        Assert.isTrue(LeadHelper.isPhoneEqual(leads[0], leads[1]));
        leads[0].DDDTelefone__c = '19';
        Assert.isFalse(LeadHelper.isPhoneEqual(leads[0], leads[1]));
    }

    @isTest
    private static void handleNewLeadsTest() {
        List<Lead> leads = new List<Lead> {
            new Lead(
                LastName = 'teste1845',
                Company = 'Company',
                Email = '4csdf@sdfds.com',
                DDDCelular__c = '11',
                DDICelular__c = 'Afeganistão (+93)',
                Celular__c = '12785-6789',
                DDDTelefone__c = '78',
                DDITelefone__c = 'Afeganistão (+93)',
                Phone = '12345-6778'
            ),
            new Lead(
                LastName = 'teste784545',
                Company = 'TulioCompany',
                Email = '474df@sdfds.com',
                OwnerId = [SELECT Id FROM User WHERE UserRole.DeveloperName = 'Integracao'].get(0).Id,
                DDDCelular__c = '11',
                DDICelular__c = 'Afeganistão (+93)',
                Celular__c = '12785-1289',
                DDDTelefone__c = '78',
                DDITelefone__c = 'Afeganistão (+93)',
                Phone = '12345-6778'
            )
        };

        Test.startTest();
            LeadHelper.handleNewLeads(leads); // Passando apenas o parâmetro correto (leads)
        Test.stopTest();

        Assert.isTrue(leads.get(0).Status == 'Contacting');
        Assert.isTrue(leads.get(1).Status == 'New');
    }
}