force-app/main/default/objects/ConfiguracoesDeNegocio__c/ConfiguracoesDeNegocio__c.object-meta.xml
<CustomObject>
    <label>Configurações de Negócio</label>
    <nameField>
        <label>Nome de Configurações de Negócio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações de Negócio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <inlineHelpText>Fase atual do Lead.</inlineHelpText>
    <label>Fase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Contacting</fullName>
                <label>Tentando Contato</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <label>Contato Realizado</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Agendamento</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <label>Convertido</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <label>Lead Perdido</label>
            </value>
            <value>
                <fullName>Unqualified</fullName>
                <label>Não Qualificado</label>
            </value>
            <value>
                <fullName>VisitDone</fullName>
                <label>Visita Realizada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/FaseParaRedirecionamentoDoLead__c.field-meta.xml
<CustomField>
    <fullName>FaseParaRedirecionamentoDoLead__c</fullName>
    <inlineHelpText>Fase do Lead após o vencimento do SLA.</inlineHelpText>
    <label>Fase para redirecionamento do Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Contacting</fullName>
                <label>Tentando Contato</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <label>Contato Realizado</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Agendamento</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <label>Convertido</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <label>Lead perdido</label>
            </value>
            <value>
                <fullName>Unqualified</fullName>
                <label>Não qualificado</label>
            </value>
            <value>
                <fullName>VisitDone</fullName>
                <label>Visita Realizada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/FilaParaRedirecionamentoDoLead__c.field-meta.xml
<CustomField>
    <fullName>FilaParaRedirecionamentoDoLead__c</fullName>
    <inlineHelpText>Fila de redirecionamento de Leads perdidos.</inlineHelpText>
    <label>Fila para redirecionamento do Lead</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/TempoDeSLA__c.field-meta.xml
<CustomField>
    <fullName>TempoDeSLA__c</fullName>
    <inlineHelpText>Define a qualidade esperada de um serviço,
tempo estabelecido em minutos.</inlineHelpText>
    <label>Tempo de SLA</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/tempoLimiteParaFarolAmarelo__c.field-meta.xml
<CustomField>
    <fullName>tempoLimiteParaFarolAmarelo__c</fullName>
    <inlineHelpText>Duração do tempo para alcançar o próximo semáforo em minutos.</inlineHelpText>
    <label>Tempo limite para farol amarelo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/tempoLimiteParaFarolVermelho__c.field-meta.xml
<CustomField>
    <fullName>tempoLimiteParaFarolVermelho__c</fullName>
    <inlineHelpText>Duração do tempo para ocorrer a perda do lead em minutos.</inlineHelpText>
    <label>Tempo limite para farol vermelho</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ConfiguracoesDeNegocioHelperTest.cls
@isTest
public class ConfiguracoesDeNegocioHelperTest {
    

    @isTest
    static void validaDuplicado() {
        List<ConfiguracoesDeNegocio__c> configs = new List<ConfiguracoesDeNegocio__c> {
            new ConfiguracoesDeNegocio__c(
                TempoDeSla__c = 5,
                Fase__c = 'Novo',
                tempoLimiteParaFarolAmarelo__c = 4,
                tempoLimiteParaFarolVermelho__c = 3,
                FaseParaRedirecionamentoDoLead__c = 'Lead Perdido',
                FilaParaRedirecionamentoDoLead__c = 'rock'
            )
        };
        insert configs;

        ConfiguracoesDeNegocio__c config = new ConfiguracoesDeNegocio__c(
            TempoDeSla__c = 5,
            Fase__c = 'Novo',
            tempoLimiteParaFarolAmarelo__c = 4,
            tempoLimiteParaFarolVermelho__c = 3,
            FaseParaRedirecionamentoDoLead__c = 'Lead Perdido',
            FilaParaRedirecionamentoDoLead__c = 'rock'
        );

        Test.startTest();
        try {
            insert config;
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Já existe uma configuração de negócio para esta fase do Lead'));
        }
        Test.stopTest();
    }

    
    @isTest
    static void validaDuplicadoUpdate() {
        List<ConfiguracoesDeNegocio__c> configs = new List<ConfiguracoesDeNegocio__c> {
            new ConfiguracoesDeNegocio__c(
                TempoDeSla__c = 5,
                Fase__c = 'Novo',
                tempoLimiteParaFarolAmarelo__c = 4,
                tempoLimiteParaFarolVermelho__c = 3,
                FaseParaRedirecionamentoDoLead__c = 'Lead Perdido',
                FilaParaRedirecionamentoDoLead__c = 'rock'
            )
        };
        insert configs;

        ConfiguracoesDeNegocio__c config = new ConfiguracoesDeNegocio__c(
            TempoDeSla__c = 5,
            Fase__c = 'Em Atendimento	',
            tempoLimiteParaFarolAmarelo__c = 4,
            tempoLimiteParaFarolVermelho__c = 3,
            FaseParaRedirecionamentoDoLead__c = 'Lead Perdido',
            FilaParaRedirecionamentoDoLead__c = 'rock'
        );

        insert config;

        Test.startTest();
        try {
            config.Fase__c = 'Novo';
            update config;
        } catch (Exception e) {
            System.assert(e.getMessage().contains('Já existe uma configuração de negócio para esta fase do Lead'));
        }
        Test.stopTest();
    }
}