force-app/main/default/objects/ConfiguracoesDeNegocio__c/ConfiguracoesDeNegocio__c.object-meta.xml
<CustomObject>
    <label>Configurações de Negócio</label>
    <nameField>
        <label>Nome de Configurações de Negócio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações de Negócio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <inlineHelpText>Fase atual do Lead.</inlineHelpText>
    <label>Fase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Contacting</fullName>
                <label>Tentando Contato</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <label>Contato Realizado</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Agendamento</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <label>Convertido</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <label>Lead Perdido</label>
            </value>
            <value>
                <fullName>Unqualified</fullName>
                <label>Não Qualificado</label>
            </value>
            <value>
                <fullName>VisitDone</fullName>
                <label>Visita Realizada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConfiguracoesDeNegocioHelper.cls
public with sharing class ConfiguracoesDeNegocioHelper {

    private static ConfiguracoesDeNegocioHelper instance = new ConfiguracoesDeNegocioHelper();
    public static ConfiguracoesDeNegocioHelper getInstance(){
        return instance;
    }
    
    public void validaDuplicado(List<ConfiguracoesDeNegocio__c> configuracoes) {
        Set<String> fases = new Set<String>();
        List<ConfiguracoesDeNegocio__c> configuracoesByFase = new List<ConfiguracoesDeNegocio__c>();
        for(ConfiguracoesDeNegocio__c configuracao : configuracoes) {
            if(!String.isEmpty(configuracao.Fase__c)) fases.add(configuracao.Fase__c);
        }

        if(fases.isEmpty()) return;
        configuracoesByFase = ConfiguracoesDeNegocioRepository.getInstance().getByFases(fases);
        if(configuracoesByFase.isEmpty()) return;

        for(ConfiguracoesDeNegocio__c configuracao : configuracoes) {
           
            for(ConfiguracoesDeNegocio__c configByFase : configuracoesByFase) {
                if(configuracao.Id != configByFase.Id && configuracao.Fase__c == configByFase.Fase__c) {
                    configuracao.addError('Já existe uma configuração de negócio para esta fase do Lead');
                }
            }

        }

    }
}