force-app/main/default/objects/ConfiguracoesDeNegocio__c/ConfiguracoesDeNegocio__c.object-meta.xml
<CustomObject>
    <label>Configurações de Negócio</label>
    <nameField>
        <label>Nome de Configurações de Negócio</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configurações de Negócio</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <inlineHelpText>Fase atual do Lead.</inlineHelpText>
    <label>Fase</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Contacting</fullName>
                <label>Tentando Contato</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <label>Contato Realizado</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Agendamento</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <label>Convertido</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <label>Lead Perdido</label>
            </value>
            <value>
                <fullName>Unqualified</fullName>
                <label>Não Qualificado</label>
            </value>
            <value>
                <fullName>VisitDone</fullName>
                <label>Visita Realizada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/FaseParaRedirecionamentoDoLead__c.field-meta.xml
<CustomField>
    <fullName>FaseParaRedirecionamentoDoLead__c</fullName>
    <inlineHelpText>Fase do Lead após o vencimento do SLA.</inlineHelpText>
    <label>Fase para redirecionamento do Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Contacting</fullName>
                <label>Tentando Contato</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <label>Contato Realizado</label>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <label>Agendamento</label>
            </value>
            <value>
                <fullName>Converted</fullName>
                <label>Convertido</label>
            </value>
            <value>
                <fullName>Lost</fullName>
                <label>Lead perdido</label>
            </value>
            <value>
                <fullName>Unqualified</fullName>
                <label>Não qualificado</label>
            </value>
            <value>
                <fullName>VisitDone</fullName>
                <label>Visita Realizada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/FilaParaRedirecionamentoDoLead__c.field-meta.xml
<CustomField>
    <fullName>FilaParaRedirecionamentoDoLead__c</fullName>
    <inlineHelpText>Fila de redirecionamento de Leads perdidos.</inlineHelpText>
    <label>Fila para redirecionamento do Lead</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/TempoDeSLA__c.field-meta.xml
<CustomField>
    <fullName>TempoDeSLA__c</fullName>
    <inlineHelpText>Define a qualidade esperada de um serviço,
tempo estabelecido em minutos.</inlineHelpText>
    <label>Tempo de SLA</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/tempoLimiteParaFarolAmarelo__c.field-meta.xml
<CustomField>
    <fullName>tempoLimiteParaFarolAmarelo__c</fullName>
    <inlineHelpText>Duração do tempo para alcançar o próximo semáforo em minutos.</inlineHelpText>
    <label>Tempo limite para farol amarelo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConfiguracoesDeNegocio__c/fields/tempoLimiteParaFarolVermelho__c.field-meta.xml
<CustomField>
    <fullName>tempoLimiteParaFarolVermelho__c</fullName>
    <inlineHelpText>Duração do tempo para ocorrer a perda do lead em minutos.</inlineHelpText>
    <label>Tempo limite para farol vermelho</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ConfiguracaoDeSLA__c.field-meta.xml
<CustomField>
    <fullName>ConfiguracaoDeSLA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Configuração de SLA</label>
    <referenceTo>ConfiguracoesDeNegocio__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DataHoraVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataHoraVencimento__c</fullName>
    <label>Tempo limite para perda</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaAtual__c.field-meta.xml
<CustomField>
    <fullName>MidiaAtual__c</fullName>
    <label>Mídia Atual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Midia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task/recordTypes/Task.recordType-meta.xml
<RecordType>
    <fullName>Task</fullName>
    <active>true</active>
    <label>Task</label>
</RecordType>

force-app/main/default/classes/LeadVencidoBatchTest.cls
@isTest
public class LeadVencidoBatchTest {
    
    @testSetup
    static void setup() {
        System.runAs ( new User(Id = UserInfo.getUserId()) ) {
            Group testGroup = new Group(Name='rock', Type='Queue');
        	insert testGroup;
    		insert new QueueSObject(QueueID = testGroup.id, SObjectType = 'Lead');
		}
        
        List<ConfiguracoesDeNegocio__c> configs = new List<ConfiguracoesDeNegocio__c> {
            new ConfiguracoesDeNegocio__c(
                // 1.440 minutos(um dia)
                TempoDeSla__c = -5,
                Fase__c = 'Contacting',
                tempoLimiteParaFarolAmarelo__c = -3,
                tempoLimiteParaFarolVermelho__c = -2,
                FaseParaRedirecionamentoDoLead__c = 'Lost',
                FilaParaRedirecionamentoDoLead__c = 'rock'
            )
        };
        insert configs;

        Lead lead = new Lead(
            FirstName = 'teeste',
            LastName = 'Teste',
            Email = 'testsla@test.com',
            Description = 'Teste',
            Status = 'Novo',
            ConfiguracaoDeSLA__c = configs.get(0).Id,
            DataHoraVencimento__c = DateTime.now().addDays(-1),
            MidiaAtual__c = 'Instagram',
            LeadSource = 'Instagram'
        );
        insert lead;

        Task task = new Task(
            Subject = 'Whatsapp',
            WhoId = lead.Id,
            ActivityDate = Date.today()
        );
        insert task;
    }

    @isTest
    static void atualizaLeadVencido() {
        Test.startTest();
        LeadVencidoBatch batch = new LeadVencidoBatch();
        Database.executeBatch(batch, 200);
        Test.stopTest();

        List<Lead> leadsAfterTest = [SELECT Id, Status FROM Lead WHERE Status = 'Lost'];
        System.assert(!leadsAfterTest.isEmpty());
        
    }
}