force-app/main/default/objects/HierarquiaDaComissao__c/HierarquiaDaComissao__c.object-meta.xml
<CustomObject>
    <label>Hierarquia da Comissão</label>
    <nameField>
        <label>Hierarquia da Comissão</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquia da Comissão</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HierarquiaDaComissao__c/fields/Comission__c.field-meta.xml
<CustomField>
    <fullName>Comission__c</fullName>
    <label>Comissão (%)</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/HierarquiaDaComissao__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Cargo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrador</fullName>
            </value>
            <value>
                <fullName>Administrativo Comercial</fullName>
            </value>
            <value>
                <fullName>Assessor(a) Comercial - Interno</fullName>
            </value>
            <value>
                <fullName>Assessor(a) Comercial - Parceiros</fullName>
            </value>
            <value>
                <fullName>Assessor(a) Comercial - SP/Miami</fullName>
            </value>
            <value>
                <fullName>Assistência Técnica</fullName>
            </value>
            <value>
                <fullName>Assistente Comercial - Interno</fullName>
            </value>
            <value>
                <fullName>Assistente Comercial - Parceiros</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>Controladoria</fullName>
            </value>
            <value>
                <fullName>Corretores</fullName>
            </value>
            <value>
                <fullName>Corretores - SP/Miami</fullName>
            </value>
            <value>
                <fullName>csouz Conta pessoal de Parceiro</fullName>
            </value>
            <value>
                <fullName>Diretor(a) Engenharia</fullName>
            </value>
            <value>
                <fullName>Diretor Comercial</fullName>
            </value>
            <value>
                <fullName>Diretoria(a) Adm</fullName>
            </value>
            <value>
                <fullName>Diretor Presidente</fullName>
            </value>
            <value>
                <fullName>Equipe Claudio Executivo de Parceiro</fullName>
            </value>
            <value>
                <fullName>Equipe Claudio Gerente de Parceiro</fullName>
            </value>
            <value>
                <fullName>Equipe Claudio Usuário de Parceiro</fullName>
            </value>
            <value>
                <fullName>Felicità Executivo de Parceiro</fullName>
            </value>
            <value>
                <fullName>Felicità Gerente de Parceiro</fullName>
            </value>
            <value>
                <fullName>Felicità Usuário de Parceiro</fullName>
            </value>
            <value>
                <fullName>Financeiro</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial Geral</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial - Interno</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial Regional - Parceiros</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial SP/Miami</fullName>
            </value>
            <value>
                <fullName>Gerente de Marketing</fullName>
            </value>
            <value>
                <fullName>Gerente de Operações Engenharia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HierarquiaDaComissao__c/fields/TabelaDeComissao__c.field-meta.xml
<CustomField>
    <fullName>TabelaDeComissao__c</fullName>
    <label>Tabela de Comissão</label>
    <referenceTo>TabelaDeComissao__c</referenceTo>
    <relationshipLabel>Hierarquia da Comissão</relationshipLabel>
    <relationshipName>HierarquiaDaComissao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ComissionTotalPercentage__c.field-meta.xml
<CustomField>
    <fullName>ComissionTotalPercentage__c</fullName>
    <label>Percentual Total de Comissão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityTeamMember/fields/ComissionPercentage__c.field-meta.xml
<CustomField>
    <fullName>ComissionPercentage__c</fullName>
    <label>Porcentagem da Comissão</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TabelaDeComissao__c/TabelaDeComissao__c.object-meta.xml
<CustomObject>
    <label>Tabela de Comissão</label>
    <nameField>
        <label>Tabela de Comissão</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela De Comissão</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaDeComissao__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Define se a tabela de comissão estará ativa ou não.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TabelaDeComissao__c/fields/EndOfTerm__c.field-meta.xml
<CustomField>
    <fullName>EndOfTerm__c</fullName>
    <label>Vigência Fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TabelaDeComissao__c/fields/SalesChannel__c.field-meta.xml
<CustomField>
    <fullName>SalesChannel__c</fullName>
    <label>Canal de Venda</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TabelaDeComissao__c/fields/StartOfTerm__c.field-meta.xml
<CustomField>
    <fullName>StartOfTerm__c</fullName>
    <label>Vigência Início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/SalesChannel__c.field-meta.xml
<CustomField>
    <fullName>SalesChannel__c</fullName>
    <label>Canal de Vendas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CommissionDistributionService.cls
public with sharing class CommissionDistributionService {

    public static void distributeCommissionToOppTeamMembers(List<OpportunityTeamMember> oppTeamMembers) {
        Map<HierarquiaDaComissao__c, List<OpportunityTeamMember>> oppTeamMembersByHierarchy = new Map<HierarquiaDaComissao__c, List<OpportunityTeamMember>>();
                
        for (OpportunityTeamMember teamMember : oppTeamMembers) {
            User teamMemberUser = [
                SELECT 
                    Id, 
                    UserRoleId, 
                    UserRole.Name, 
                    SalesChannel__c 
                FROM User WHERE Id = :teamMember.UserId
            ];
            
            Date today = Date.today();

            List<HierarquiaDaComissao__c> commissionHierarchyList = [
                SELECT 
                    Id, 
                    Comission__c 
                FROM HierarquiaDaComissao__c 
                WHERE Role__c = :teamMemberUser.UserRole.Name 
                    AND TabelaDeComissao__r.SalesChannel__c = :teamMemberUser.SalesChannel__c 
                    AND TabelaDeComissao__r.Active__c = true 
                    AND TabelaDeComissao__r.StartOfTerm__c <= :today AND TabelaDeComissao__r.EndOfTerm__c >= :today
                LIMIT 1];

            if (commissionHierarchyList.size() == 0) {
                continue;
            }

            HierarquiaDaComissao__c commissionHierarchy = commissionHierarchyList.get(0);

            if (!oppTeamMembersByHierarchy.containsKey(commissionHierarchy)) {
                List<OpportunityTeamMember> oppTeamMembersInSameHierarchy = [
                    SELECT
                        Id,
                        ComissionPercentage__c,
                        OpportunityId
                    FROM OpportunityTeamMember
                    WHERE User.UserRoleId = :teamMemberUser.UserRoleId AND User.SalesChannel__c = :teamMemberUser.SalesChannel__c AND Opportunity.isClosed = false
                ];

                if (oppTeamMembersInSameHierarchy.size() > 0) {
                    oppTeamMembersByHierarchy.put(commissionHierarchy, oppTeamMembersInSameHierarchy);
                }
            }
        }

        updateOppTeamMembersByCommissionHierarchy(oppTeamMembersByHierarchy);
    }

    public static void distributeCommissionHierarchiesToOppTeamMembers(List<HierarquiaDaComissao__c> commissionHierarchies) {
        Map<HierarquiaDaComissao__c, List<OpportunityTeamMember>> oppTeamMembersByHierarchy = new Map<HierarquiaDaComissao__c, List<OpportunityTeamMember>>();

        for (HierarquiaDaComissao__c commissionHierarchy : commissionHierarchies) {
            if (HierarquiaDaComissaoDomain.isCommissionChangeIsValid(commissionHierarchy)) {
                continue;
            }

            TabelaDeComissao__c commissionTable = [
                SELECT
                    Id,
                    SalesChannel__c
                FROM TabelaDeComissao__c
                WHERE Id = :commissionHierarchy.TabelaDeComissao__c
            ];

            List<OpportunityTeamMember> oppTeamMembers = [
                SELECT
                    Id,
                    ComissionPercentage__c,
                    OpportunityId
                FROM OpportunityTeamMember
                WHERE User.UserRole.Name = :commissionHierarchy.Role__c AND User.SalesChannel__c = :commissionTable.SalesChannel__c AND Opportunity.isClosed = false
            ];

            if (oppTeamMembers.size() > 0) {
                oppTeamMembersByHierarchy.put(commissionHierarchy, oppTeamMembers);
            }
        }

        updateOppTeamMembersByCommissionHierarchy(oppTeamMembersByHierarchy);
    }

    public static void updateOppTeamMembersByCommissionHierarchy(Map<HierarquiaDaComissao__c, List<OpportunityTeamMember>> oppTeamMembersByHierarchy) {        
        List<OpportunityTeamMember> oppTeamMembersToUpdate = new List<OpportunityTeamMember>();
        List<Id> opportunitiesToUpdate = new List<Id>();
        
        for (HierarquiaDaComissao__c commissionHierarchy : oppTeamMembersByHierarchy.keySet()) {
            Map<Id, List<OpportunityTeamMember>> oppTeamMembersByOpp = OpportunityTeamMemberDomain.divideOppTeamMembersByOpportunity(oppTeamMembersByHierarchy.get(commissionHierarchy));

            for (Id opportunityId : oppTeamMembersByOpp.keySet()) {
                Decimal commissionPercentageTotal = commissionHierarchy.Comission__c;
                Decimal commissionPercentageForEachMember = commissionPercentageTotal / oppTeamMembersByOpp.get(opportunityId).size();

                for (OpportunityTeamMember teamMember : oppTeamMembersByOpp.get(opportunityId)) {
                    teamMember.ComissionPercentage__c = commissionPercentageForEachMember;
                    oppTeamMembersToUpdate.add(teamMember);
                }

                opportunitiesToUpdate.add(opportunityId);
            }
        }

        update oppTeamMembersToUpdate;
        
        updateOpportunityWithCommissionPercentageTotal(opportunitiesToUpdate);
    }

    public static List<HierarquiaDaComissao__c> removeCommissionFromCommissionHierarchiesObjects(List<HierarquiaDaComissao__c> commissionHierarchiesToDelete) {        
        List<HierarquiaDaComissao__c> commissionHierarchiesToReturn = new List<HierarquiaDaComissao__c>();

        for (HierarquiaDaComissao__c commissionHierarchy : commissionHierarchiesToDelete) {
            commissionHierarchiesToReturn.add(new HierarquiaDaComissao__c(
                Id = commissionHierarchy.Id,
                Comission__c = 0,
                Role__c = commissionHierarchy.Role__c,
                TabelaDeComissao__c = commissionHierarchy.TabelaDeComissao__c,
                Name = commissionHierarchy.Name
            ));
        }

        return commissionHierarchiesToReturn;
    }

    public static void updateOpportunityWithCommissionPercentageTotal(List<Id> opportunityIds) {
        for (Id opportunityId : opportunityIds) {
            List<OpportunityTeamMember> oppTeamMembers = [SELECT Id, ComissionPercentage__c FROM OpportunityTeamMember WHERE OpportunityId = :opportunityId];
            Decimal commissionPercentageTotal = 0;
    
            for (OpportunityTeamMember teamMember : oppTeamMembers) {
                commissionPercentageTotal += teamMember.ComissionPercentage__c ?? 0;
            }
    
            update new Opportunity(Id = opportunityId, ComissionTotalPercentage__c = commissionPercentageTotal);
        }
    }
}