force-app/main/default/objects/HierarquiaDaComissao__c/HierarquiaDaComissao__c.object-meta.xml
<CustomObject>
    <label>Hierarquia da Comissão</label>
    <nameField>
        <label>Hierarquia da Comissão</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hierarquia da Comissão</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HierarquiaDaComissao__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Cargo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrador</fullName>
            </value>
            <value>
                <fullName>Administrativo Comercial</fullName>
            </value>
            <value>
                <fullName>Assessor(a) Comercial - Interno</fullName>
            </value>
            <value>
                <fullName>Assessor(a) Comercial - Parceiros</fullName>
            </value>
            <value>
                <fullName>Assessor(a) Comercial - SP/Miami</fullName>
            </value>
            <value>
                <fullName>Assistência Técnica</fullName>
            </value>
            <value>
                <fullName>Assistente Comercial - Interno</fullName>
            </value>
            <value>
                <fullName>Assistente Comercial - Parceiros</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>Controladoria</fullName>
            </value>
            <value>
                <fullName>Corretores</fullName>
            </value>
            <value>
                <fullName>Corretores - SP/Miami</fullName>
            </value>
            <value>
                <fullName>csouz Conta pessoal de Parceiro</fullName>
            </value>
            <value>
                <fullName>Diretor(a) Engenharia</fullName>
            </value>
            <value>
                <fullName>Diretor Comercial</fullName>
            </value>
            <value>
                <fullName>Diretoria(a) Adm</fullName>
            </value>
            <value>
                <fullName>Diretor Presidente</fullName>
            </value>
            <value>
                <fullName>Equipe Claudio Executivo de Parceiro</fullName>
            </value>
            <value>
                <fullName>Equipe Claudio Gerente de Parceiro</fullName>
            </value>
            <value>
                <fullName>Equipe Claudio Usuário de Parceiro</fullName>
            </value>
            <value>
                <fullName>Felicità Executivo de Parceiro</fullName>
            </value>
            <value>
                <fullName>Felicità Gerente de Parceiro</fullName>
            </value>
            <value>
                <fullName>Felicità Usuário de Parceiro</fullName>
            </value>
            <value>
                <fullName>Financeiro</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial Geral</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial - Interno</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial Regional - Parceiros</fullName>
            </value>
            <value>
                <fullName>Gerente Comercial SP/Miami</fullName>
            </value>
            <value>
                <fullName>Gerente de Marketing</fullName>
            </value>
            <value>
                <fullName>Gerente de Operações Engenharia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HierarquiaDaComissao__c/fields/TabelaDeComissao__c.field-meta.xml
<CustomField>
    <fullName>TabelaDeComissao__c</fullName>
    <label>Tabela de Comissão</label>
    <referenceTo>TabelaDeComissao__c</referenceTo>
    <relationshipLabel>Hierarquia da Comissão</relationshipLabel>
    <relationshipName>HierarquiaDaComissao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Oportunidades.recordType-meta.xml
<RecordType>
    <fullName>Oportunidades</fullName>
    <active>true</active>
    <businessProcess>Processo de Vendas Oportunidade</businessProcess>
    <label>Oportunidades</label>
</RecordType>

force-app/main/default/objects/TabelaDeComissao__c/TabelaDeComissao__c.object-meta.xml
<CustomObject>
    <label>Tabela de Comissão</label>
    <nameField>
        <label>Tabela de Comissão</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela De Comissão</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaDeComissao__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Define se a tabela de comissão estará ativa ou não.</description>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TabelaDeComissao__c/fields/EndOfTerm__c.field-meta.xml
<CustomField>
    <fullName>EndOfTerm__c</fullName>
    <label>Vigência Fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TabelaDeComissao__c/fields/SalesChannel__c.field-meta.xml
<CustomField>
    <fullName>SalesChannel__c</fullName>
    <label>Canal de Venda</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TabelaDeComissao__c/fields/StartOfTerm__c.field-meta.xml
<CustomField>
    <fullName>StartOfTerm__c</fullName>
    <label>Vigência Início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/SalesChannel__c.field-meta.xml
<CustomField>
    <fullName>SalesChannel__c</fullName>
    <label>Canal de Vendas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/HierarquiaDaComissaoDomain.cls
public with sharing class HierarquiaDaComissaoDomain {
    
    public static Boolean isCommissionChangeIsValid(HierarquiaDaComissao__c hierachy) {
        if (hierachy.TabelaDeComissao__c == null) {
            return true;
        }

        TabelaDeComissao__c commissionTable = [
            SELECT Id, SalesChannel__c, Active__c, StartOfTerm__c, EndOfTerm__c
            FROM TabelaDeComissao__c 
            WHERE Id = :hierachy.TabelaDeComissao__c
        ];
        
        Date today = Date.today();

        if (commissionTable.Active__c && (today >= commissionTable.StartOfTerm__c && today <= commissionTable.EndOfTerm__c)) {
            Integer countOppTeamMembers = [
                SELECT COUNT() 
                FROM OpportunityTeamMember 
                WHERE User.SalesChannel__c = :commissionTable.SalesChannel__c
                    AND USer.UserRole.Name = :hierachy.Role__c
                    AND Opportunity.IsClosed = false
            ];

            if (countOppTeamMembers != 0) {
                hierachy.addError('Existem Equipes de Oportunidades em andamento atreladas a essa hierarquia. Crie uma nova Tabela/Hierarquia de Comissão.');
                return false;
            }
        }

        return true;
    }
}