force-app/main/default/objects/Lead/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <description>Bairro do lead</description>
    <label>Bairro</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <description>Cep do Lead</description>
    <label>CEP</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/UF__c.field-meta.xml
<CustomField>
    <fullName>UF__c</fullName>
    <description>UF do Lead</description>
    <label>UF</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ViaCepService.cls
public class ViaCepService {
    public class Address {
        public String cep;
        public String logradouro;
        public String complemento;
        public String bairro;
        public String localidade;
        public String uf;
        public String unidade;
        public String ibge;
        public String gia;
    }

    @future(callout=true)
    public static void getAddress(String cep, Id leadId) {
        String url = 'https://viacep.com.br/ws/' + cep + '/json/';
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(url);
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        
        if (response.getStatusCode() == 200) {
            Address address = (Address) JSON.deserialize(response.getBody(), Address.class);
            if (address != null) {
                Lead lead = [SELECT Id, Street, City, UF__c, CEP__c , Bairro__c  FROM Lead WHERE Id = :leadId LIMIT 1];
                lead.Street = address.logradouro;
                lead.City = address.localidade;
                lead.UF__c = address.uf;
                lead.CEP__c = address.cep;
                lead.Bairro__c = address.bairro;
                update lead;
            }
        }
    }
}