force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <description>Canal de Atendimento</description>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaCanalAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Corretor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/TelefoneFormatado__c.field-meta.xml
<CustomField>
    <fullName>TelefoneFormatado__c</fullName>
    <formula>IF(
				ISBLANK(Phone), 
				&quot;&quot;, 
				MID(
								TEXT(DDITelefone__c), 
								FIND(&quot;+&quot;, TEXT(DDITelefone__c)), 
								(LEN(TEXT(DDITelefone__c))-FIND(&quot;+&quot;, TEXT(DDITelefone__c)))) + 
				    IF (
								    ISBLANK(DDDTelefone__c),
												&quot; &quot;,
												&quot; (&quot;+DDDTelefone__c+&quot;) &quot;
								)
				    +  Phone)</formula>
    <label>Telefone Formatado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadSelector.cls
public without sharing class LeadSelector {
    public static List<Lead> obterLeadsPorIds(Set<Id> idsLeads) {
        return [
            SELECT 
                Name, 
                CanalAtendimento__c,
                Corretor__c, 
                FirstName, 
                LastName, 
                MobilePhone, 
                Email, 
                Status, 
                OwnerId, 
                Owner.Name
            FROM Lead 
            WHERE Id IN :idsLeads
        ];
    }

    public static List<Lead> obterLeadsPorInformacoesConcierge(String whereParams) {
        return Database.query(
            'SELECT ' +
                'Name, ' +
                'FirstName, ' +
                'LastName, ' +
                'Company, '+
                'CelularFormatado__c, '+
                'TelefoneFormatado__c, ' +
                'Email, ' +
                'Status, ' +
                'Owner.Name ' +
            'FROM Lead WHERE '+whereParams
        );
    }
}