force-app/main/default/objects/Lead/fields/CanalAtendimento__c.field-meta.xml
<CustomField>
    <fullName>CanalAtendimento__c</fullName>
    <description>Canal de Atendimento</description>
    <label>Canal de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaCanalAtendimento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DDDCelular__c.field-meta.xml
<CustomField>
    <fullName>DDDCelular__c</fullName>
    <label>DDD Celular</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDICelular__c.field-meta.xml
<CustomField>
    <fullName>DDICelular__c</fullName>
    <label>DDI Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaAtual__c.field-meta.xml
<CustomField>
    <fullName>MidiaAtual__c</fullName>
    <label>Mídia Atual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Midia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/TelefoneFormatado__c.field-meta.xml
<CustomField>
    <fullName>TelefoneFormatado__c</fullName>
    <formula>IF(
				ISBLANK(Phone), 
				&quot;&quot;, 
				MID(
								TEXT(DDITelefone__c), 
								FIND(&quot;+&quot;, TEXT(DDITelefone__c)), 
								(LEN(TEXT(DDITelefone__c))-FIND(&quot;+&quot;, TEXT(DDITelefone__c)))) + 
				    IF (
								    ISBLANK(DDDTelefone__c),
												&quot; &quot;,
												&quot; (&quot;+DDDTelefone__c+&quot;) &quot;
								)
				    +  Phone)</formula>
    <label>Telefone Formatado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadSelectorTest.cls
@isTest
private class LeadSelectorTest {

    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData() {
        List<Lead> leads = new List<Lead>{
            new Lead(
                LastName = 'Teste1',
                LeadSource = 'Site',
                MidiaAtual__c = 'Instagram',
                CanalAtendimento__c = 'Chat',
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '16',
                Phone = '18845-6789',
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '16',
                Celular__c = '18845-6789',
                Email = 'teste1@teste.com'
            ),

            new Lead(
                LastName = 'Teste2',
                LeadSource = 'Site',
                MidiaAtual__c = 'Instagram',
                CanalAtendimento__c = 'Chat',
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '16',
                Phone = '28845-6789',
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '16',
                Celular__c = '13845-6789',
                Email = 'teste2@teste.com'
            )
        };

        insert leads;
    }

    @isTest
    static void obterLeadsPorIdsTest() {
        List<Lead> leads = [SELECT Name, FirstName, LastName, CelularFormatado__c, TelefoneFormatado__c, Email, Status, Owner.Name FROM Lead];
        Set<Id> idsLeads = new Map<Id,Lead>(leads).keySet();

        Assert.areEqual(idsLeads, new Map<Id,Lead>(LeadSelector.obterLeadsPorIds(idsLeads)).keySet());
    }

    @isTest
    static void obterLeadsPorInformacoesConciergeTest() {
        List<Lead> leads = [SELECT Name, FirstName, LastName, CelularFormatado__c, TelefoneFormatado__c, Email, Status, Owner.Name FROM Lead WHERE LastName LIKE '%Teste1%'];
        
        Assert.areEqual(leads, LeadSelector.obterLeadsPorInformacoesConcierge('LastName LIKE \'%Teste1%\''));
    }
}