force-app/main/default/objects/Lead/fields/DDDCelular__c.field-meta.xml
<CustomField>
    <fullName>DDDCelular__c</fullName>
    <label>DDD Celular</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DDICelular__c.field-meta.xml
<CustomField>
    <fullName>DDICelular__c</fullName>
    <label>DDI Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ListaPaisesDDI</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/MidiaAtual__c.field-meta.xml
<CustomField>
    <fullName>MidiaAtual__c</fullName>
    <label>Mídia Atual</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Midia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignMemberDATest.cls
@IsTest
private class CampaignMemberDATest {
    
    @TestSetup
    static void makeData(){
        doCreateData();
    }

    private static void doCreateData() {
        Lead lead = new Lead(
                LastName = 'Teste', 
                Status = 'Novo',  
                DDITelefone__c = 'Brasil (+55)',
                DDDTelefone__c = '16',
                Phone = '18845-6789',  
                DDICelular__c = 'Brasil (+55)',
                DDDCelular__c = '16',
                Celular__c = '18845-6789', 
                Email = 'teste@email.com', 
                MidiaAtual__c = 'Instagram', 
                LeadSource = 'Instagram'
                );
        Campaign campaign = new Campaign(Name = 'Teste', isActive = true);

        insert lead;
        insert campaign;

        insert new CampaignMember(LeadId = lead.Id, CampaignId = campaign.Id);
    }

    @IsTest
    private static void getByLeadCampaignTest() {

        List<Lead> leads = [SELECT Id FROM Lead];
        List<Campaign> campaigns = [SELECT Id FROM Campaign];

        Set<Id> setIdLead = new Map<Id,Lead>(leads).keySet();
        Set<Id> setIdCampaign = new Map<Id,Campaign>(campaigns).keySet();

        Test.startTest();

        List<CampaignMember> expectedCampaignMembers = CampaignMemberDA.getByLeadCampaign(
            new Set<String>{'Id'},
            setIdLead,
            setIdCampaign
        );

        Test.stopTest();

        Assert.areEqual(1, expectedCampaignMembers.size());
    }
}