force-app/main/default/objects/Opportunity/fields/EmpreendimentodeInteresse__c.field-meta.xml
<CustomField>
    <fullName>EmpreendimentodeInteresse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empreendimento de Interesse</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Empreendimento__c.Generico__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Empreendimento__c</referenceTo>
    <relationshipLabel>Oportunidades(Empreendimento de interesse)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoVenda__c.field-meta.xml
<CustomField>
    <fullName>TipoVenda__c</fullName>
    <label>Tipo de Venda</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoVenda</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TipoVenda.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Financiamento Bancário</fullName>
    </customValue>
    <customValue>
        <fullName>Venda á Vista</fullName>
    </customValue>
    <customValue>
        <fullName>Financiamento Direto</fullName>
    </customValue>
    <masterLabel>Tipo da Venda</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OpportunitySelector.cls
public without sharing class OpportunitySelector {
    public static Opportunity obterOportunidadePorId(Id idOportunidade) {
        return [ 
            SELECT 
                Id, Name, TipoVenda__c, CloseDate, Owner.Name, Account.Name, EmpreendimentodeInteresse__c
            FROM Opportunity 
            WHERE 
                Id = :idOportunidade];
    }

    public static Opportunity obterOportunidadePorIdCotacao (Id idCotacao) {

        Id idOportunidade = [SELECT OpportunityId FROM Quote WHERE Id = :idCotacao LIMIT 1].OpportunityId;

        return obterOportunidadePorId(idOportunidade);
    }
}