force-app/main/default/objects/Opportunity/fields/TotalValuePlusReferral__c.field-meta.xml
<CustomField>
    <fullName>TotalValuePlusReferral__c</fullName>
    <label>Valor total com indicação</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TabelaDeComissao__c/TabelaDeComissao__c.object-meta.xml
<CustomObject>
    <label>Tabela de Comissão</label>
    <nameField>
        <label>Tabela de Comissão</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela De Comissão</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaDeComissao__c/fields/Indication__c.field-meta.xml
<CustomField>
    <fullName>Indication__c</fullName>
    <label>Indicação</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/TabelaDeComissao__c/fields/SalesChannel__c.field-meta.xml
<CustomField>
    <fullName>SalesChannel__c</fullName>
    <label>Canal de Venda</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/SalesChannel__c.field-meta.xml
<CustomField>
    <fullName>SalesChannel__c</fullName>
    <label>Canal de Vendas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TabelaDeComissaoDomain.cls
public with sharing class TabelaDeComissaoDomain {
    public static void handleBeforeUpdate(List<TabelaDeComissao__c> newTables, Map<Id, TabelaDeComissao__c> oldTables) {
        for (TabelaDeComissao__c newTable : newTables) {
            handleIndicacaoChange(newTable, oldTables.get(newTable.Id));
        }
    }
    
    public static void handleIndicacaoChange(TabelaDeComissao__c newTable, TabelaDeComissao__c oldTable) {
        if (newTable.Indication__c != oldTable.Indication__c) {
            Map<Id, Id> OTMUniques = new Map<Id, Id>();
            for (OpportunityTeamMember otm : [
            SELECT 
                Id,
                OpportunityId
            FROM 
                OpportunityTeamMember 
            WHERE 
                User.SalesChannel__c = :newTable.SalesChannel__c
            ORDER BY 
                CreatedDate 
                    ASC
            ]) {
                if(!OTMUniques.containsKey(otm.OpportunityId)) {
                    OTMUniques.put(otm.OpportunityId, otm.Id);
                }
            }
            if(!OTMUniques.isEmpty()) {
                List<Opportunity> opps = [
                SELECT 
                    Id,
                    TotalValuePlusReferral__c,
                    Amount
                FROM 
                    Opportunity 
                WHERE 
                    Id IN :OTMUniques.keySet()
            ];
                
                for (Opportunity opp : opps) {
                    Decimal referralValue = opp.Amount * (newTable.Indication__c / 100);
                    opp.TotalValuePlusReferral__c = opp.Amount + referralValue;
                }
                
                update opps;
            }
        }
    }
}