force-app/main/default/objects/TabelaVendas__c/TabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Tabela de Venda</label>
    <nameField>
        <label>Nome de Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tabela de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcela__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcela__c</fullName>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Mensal</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>Semestral</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Anual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TabelaVendas__c/fields/PeriodicidadeParcelaPos__c.field-meta.xml
<CustomField>
    <fullName>PeriodicidadeParcelaPos__c</fullName>
    <inlineHelpText>Mensal = 1, Semestral = 6, Anual = 12</inlineHelpText>
    <label>Periodicidade da parcela</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/UnidadeTabelaVendas__c.object-meta.xml
<CustomObject>
    <label>Entrada de Preço</label>
    <nameField>
        <label>Nome de Unidade da Tabela de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entrada de Preços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/CoeficienteTabela__c.field-meta.xml
<CustomField>
    <fullName>CoeficienteTabela__c</fullName>
    <label>Coeficiente na Tabela</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/MetragemUnidade__c.field-meta.xml
<CustomField>
    <fullName>MetragemUnidade__c</fullName>
    <label>Metragem da Unidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/PrecoLista__c.field-meta.xml
<CustomField>
    <fullName>PrecoLista__c</fullName>
    <label>Preço de lista</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/TabelaVenda__c.field-meta.xml
<CustomField>
    <fullName>TabelaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de Venda</label>
    <referenceTo>TabelaVendas__c</referenceTo>
    <relationshipName>Unidades_da_Tabela_de_Vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entrada de Preços</relationshipLabel>
    <relationshipName>UnidadesTabelaVendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UnidadeTabelaVendas__c/fields/ValorVenda__c.field-meta.xml
<CustomField>
    <fullName>ValorVenda__c</fullName>
    <formula>(
    (PrecoLista__c  * CoeficienteTabela__c) -
    IF(ISBLANK(TabelaVenda__r.ValorDeAcrescimo__c), 0.0, TabelaVenda__r.ValorDeAcrescimo__c)
) * 
IF(ISBLANK(TabelaVenda__r.PercentualDeAcrescimo__c), 1.0, 1 + TabelaVenda__r.PercentualDeAcrescimo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor de venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/UnidadeTabelaSelectorTest.cls
@isTest
private class UnidadeTabelaSelectorTest {
    
    @TestSetup
    static void makeData() {
        TabelaVendas__c tabela = new TabelaVendas__c();
        tabela.Name = 'Teste'; 
        tabela.PeriodicidadeParcelaPos__c = 1;
        tabela.PeriodicidadeParcela__c = '1';
        insert tabela;

        UnidadeTabelaVendas__c unidadeVenda = new UnidadeTabelaVendas__c();
        unidadeVenda.Name = 'UnidadeVendaTeste';
        unidadeVenda.TabelaVenda__c = tabela.Id;
        unidadeVenda.PrecoLista__c = 300000;
        insert unidadeVenda;
    }

    @isTest
    private static void obterUnidadeTabelaPorIdTest() {
        List<UnidadeTabelaVendas__c> unidadesTabela = [
            SELECT
            Id,
            TabelaVenda__c,
            PrecoLista__c
            FROM UnidadeTabelaVendas__c
        ];

        Test.startTest();
        List<UnidadeTabelaVendas__c> actual = UnidadeTabelaSelector.obterUnidadeTabelaPorId(unidadesTabela.get(0).TabelaVenda__c);
        Test.stopTest();

        Assert.areEqual(unidadesTabela, actual);
    }

    @isTest
    private static void obterUnidadesTabelaExistentesTest() {
        Set<Id> tabelaVendasIds = new Map<Id,TabelaVendas__c>([SELECT Id FROM TabelaVendas__c]).keySet();

        Map<Id,UnidadeTabelaVendas__c> unidadesTabelaMap = new Map<Id, UnidadeTabelaVendas__c>([
            SELECT Id, Name, PrecoLista__c, CoeficienteTabela__c, MetragemUnidade__c, Unidade__c, TabelaVenda__c
            FROM UnidadeTabelaVendas__c
            WHERE TabelaVenda__c IN :tabelaVendasIds
        ]);

        Test.startTest();
        Map<Id,UnidadeTabelaVendas__c> actual = UnidadeTabelaSelector.obterUnidadesTabelaExistentes(tabelaVendasIds);
        Test.stopTest();

        for(Id idUnidade : unidadesTabelaMap.keySet()) {
            Assert.isTrue(actual.containsKey(idUnidade));
            Assert.areEqual(unidadesTabelaMap.get(idUnidade), actual.get(idUnidade));
        }
    }

    @isTest
    private static void obterUnidadesTabelaPorIdUnidadeTest() {
        UnidadeTabelaVendas__c unidade = [
            SELECT 
                Id,
                ValorVenda__c,
                Unidade__c
            FROM UnidadeTabelaVendas__c
            LIMIT 1
        ];

        Test.startTest();
        UnidadeTabelaVendas__c actual = UnidadeTabelaSelector.obterUnidadesTabelaPorIdUnidade(unidade.Unidade__c);
        Test.stopTest();

        Assert.areEqual(unidade, actual);
    }
}