force-app/main/default/objects/AnaliseDeCredito__c/AnaliseDeCredito__c.object-meta.xml
<CustomObject>
    <label>Análise de Crédito</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Análises de Crédito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnaliseDeCredito__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>AnlisesDeCredito</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Documento__c/Documento__c.object-meta.xml
<CustomObject>
    <label>Documento</label>
    <nameField>
        <label>Nome do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Documento__c/fields/Entregue__c.field-meta.xml
<CustomField>
    <fullName>Entregue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Entregue?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status Aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Entregue</fullName>
            </value>
            <value>
                <fullName>Pendente de Análise</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Vencido</fullName>
                <label>Expirada</label>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Corretor__c.field-meta.xml
<CustomField>
    <fullName>Corretor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Corretor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Corretor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResponsavelPeloLead__c.field-meta.xml
<CustomField>
    <fullName>ResponsavelPeloLead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responsável pelo Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unidade__c.field-meta.xml
<CustomField>
    <fullName>Unidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>A Unidade deve estar relacionada ao Empreendimento de Interesse</errorMessage>
        <filterItems>
            <field>$Source.EmpreendimentodeInteresse__c</field>
            <operation>equals</operation>
            <valueField>Product2.Empreendimento__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityHelper.cls
public with sharing class OpportunityHelper {
    
    public static void handleNewOpportunities(List<Opportunity> opportunities, Map<Id,Opportunity> oldOpportunitiesMap) {
        validateDuplicates(opportunities, oldOpportunitiesMap);
    }

    public static void handleBeforeUpdate(List<Opportunity> opportunities, Map<Id,Opportunity> oldOpportunitiesMap) {
        validateDuplicates(opportunities, oldOpportunitiesMap);
    }

    private static void validateDuplicates(List<Opportunity> opportunities, Map<Id,Opportunity> oldOpportunitiesMap) {
        for (Opportunity iOpp : opportunities) {

            if (iOpp.Unidade__c == null || iOpp.ResponsavelPeloLead__c == null) {
                continue;
            }

            List<Opportunity> duplicatedOpps = OpportunityDA.getOpportunityByAccountProduct(iOpp.AccountId, iOpp.Unidade__c, iOpp.ResponsavelPeloLead__c, iOpp.Corretor__c);

            Set<String> stageNameSet = ObjectHelper.getFieldValuesFromList([SELECT MasterLabel FROM OpportunityStage WHERE IsClosed = true], 'MasterLabel');
            Set<String> stageValueSet = ObjectHelper.getFieldValuesFromList(duplicatedOpps, 'StageName');
            
            for (Opportunity duplicada : duplicatedOpps) {
                
                if (duplicatedOpps.isEmpty() || ObjectHelper.containsAny(stageValueSet, stageNameSet) || ObjectHelper.isEqualField(new Set<String>{'AccountId', 'Unidade__c', 'ResponsavelPeloLead__c', 'Corretor__c'}, opportunities, oldOpportunitiesMap) || ObjectHelper.isEqualField(iOpp, duplicada, 'Id')) {
                    continue;
                }
                
                iOpp.addError('Não é possível criar uma oportunidade duplicada.');
            }
        }
    }   

    public static void validateDoc(List<Opportunity> newOpps, Map<Id, Opportunity> oldOpps) {
        if (newOpps == null || oldOpps == null) {
            return;
        }
    
        Set<Id> opportunityIds = new Set<Id>();
        for (Opportunity opp : newOpps) {
            opportunityIds.add(opp.Id);
        }
    
        Map<Id, List<Documento__c>> documentosPorOportunidade = new Map<Id, List<Documento__c>>();
    
        List<Documento__c> documentosEntregues = [
            SELECT Id, StatusAprovacao__c, Oportunidade__c 
            FROM Documento__c 
            WHERE Oportunidade__c IN :opportunityIds 
            AND Entregue__c = TRUE
        ];
    
    
        for (Documento__c doc : documentosEntregues) {
            if (!documentosPorOportunidade.containsKey(doc.Oportunidade__c)) {
                documentosPorOportunidade.put(doc.Oportunidade__c, new List<Documento__c>());
            }
            documentosPorOportunidade.get(doc.Oportunidade__c).add(doc);
        }
    
        for (Opportunity opp : newOpps) {
            Opportunity oldOpp = oldOpps.get(opp.Id);
            List<Documento__c> docsRelacionados = documentosPorOportunidade.get(opp.Id);
    
    
            if (oldOpp.StageName == 'Análise Jurídica' && opp.StageName == 'Aprovação') {
                if (docsRelacionados != null && !docsRelacionados.isEmpty()) {
                    Boolean todosAprovados = true;
                    Boolean algumEntregueNaoAprovado = false;
    
                    for (Documento__c doc : docsRelacionados) {
                        if (doc.StatusAprovacao__c != 'Aprovado') {
                            todosAprovados = false;
    
                            if (doc.StatusAprovacao__c == 'Entregue') {
                                algumEntregueNaoAprovado = true;
                            }
                        }
                    }
    
                    if (algumEntregueNaoAprovado) {
                        opp.addError('A oportunidade não pode avançar para a fase de aprovação porque existem documentos entregues que não estão aprovados.');
                    } else if (!todosAprovados) {
                        opp.addError('A oportunidade só pode avançar para a fase de aprovação quando todos os documentos entregues estiverem com o status "Aprovado".');
                    }
                }
            }
        }
    }
    
    public static void createAnaliseCredito(List<Opportunity> newOpps, Map<Id, Opportunity> oldOpps) {
        List<AnaliseDeCredito__c> novasAnalises = new List<AnaliseDeCredito__c>();

        for (Opportunity opp : newOpps) {
            Opportunity oldOpp = oldOpps.get(opp.Id);
            
            if (oldOpp.StageName != 'Documentação' && opp.StageName == 'Documentação') {
                AnaliseDeCredito__c novaAnalise = new AnaliseDeCredito__c();
                novaAnalise.Oportunidade__c = opp.Id;
                novasAnalises.add(novaAnalise);
            }
        }
    
        if (!novasAnalises.isEmpty()) {
            insert novasAnalises;
        }
    }
    
    
}