force-app/main/default/objects/AnaliseDeCredito__c/AnaliseDeCredito__c.object-meta.xml
<CustomObject>
    <label>Análise de Crédito</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Análises de Crédito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnaliseDeCredito__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>AnlisesDeCredito</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comprador__c/Comprador__c.object-meta.xml
<CustomObject>
    <label>Comprador</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Comprador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compradores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comprador__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Jurídica (PJ), Pessoa Física (PF), Imobiliária</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comprador__c/recordTypes/Comprador.recordType-meta.xml
<RecordType>
    <fullName>Comprador</fullName>
    <active>true</active>
    <label>Comprador</label>
</RecordType>

force-app/main/default/classes/AccountService.cls
public class AccountService {
    static Map<String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
    static Schema.SObjectType myobjectSchema = schemaMap.get('Account');
    static Map<String, Schema.SObjectField> fieldMap = myobjectSchema.getDescribe().fields.getMap();

    public static Map<String, Account> obterInfoContaPorAnaliseCredito(Id idAnaliseCredito) {
        AnaliseDeCredito__c analiseCredito = AnaliseCreditoSelector.obterAnaliseCreditoPorId(idAnaliseCredito);

        List<Comprador__c> compradores =  CompradorSelector.obterCompradoresPorOportunidade(analiseCredito.Oportunidade__c);

        Map<String, Account> infoConta = new Map<String, Account>();
        
        for(Comprador__c comprador : compradores) {
            infoConta.put(comprador.Conta__r.Name, AccountSelector.obterInfoContaPorId(comprador.Conta__r.Id));
        }

        return infoConta;
    }

    public static void atualizarValoresConta(Map<String, String> camposValores, Id idConta){
        Account conta = AccountSelector.obterContaPorId(idConta);
        
        for(String campo : camposValores.keySet()) {
            switch on fieldMap.get(campo).getDescribe().getType() {
                when DOUBLE {
                    conta.put(campo, Decimal.valueOf((String) camposValores.get(campo)));
                }
                when STRING, PHONE, PICKLIST, ID, ADDRESS, URL {
                    conta.put(campo, (String) camposValores.get(campo));
                }
                when DATE {
                    conta.put(campo, Date.valueOf((String) camposValores.get(campo)));
                }
                when BOOLEAN {
                    conta.put(campo, Boolean.valueOf((String) camposValores.get(campo)));
                }
                when INTEGER {
                    conta.put(campo, Integer.valueOf((String) camposValores.get(campo)));
                }
                when DATETIME {
                    conta.put(campo, Datetime.valueOf((String) camposValores.get(campo)));
                }
            }
        }

        update conta;
    }
}