force-app/main/default/objects/AnaliseDeCredito__c/AnaliseDeCredito__c.object-meta.xml
<CustomObject>
    <label>Análise de Crédito</label>
    <nameField>
        <displayFormat>AC-{0000000000}</displayFormat>
        <label>Nome</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Análises de Crédito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AnaliseDeCredito__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>AnlisesDeCredito</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comprador__c/Comprador__c.object-meta.xml
<CustomObject>
    <label>Comprador</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Comprador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compradores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comprador__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Jurídica (PJ), Pessoa Física (PF), Imobiliária</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comprador__c/recordTypes/Comprador.recordType-meta.xml
<RecordType>
    <fullName>Comprador</fullName>
    <active>true</active>
    <label>Comprador</label>
</RecordType>

force-app/main/default/objects/Documento__c/Documento__c.object-meta.xml
<CustomObject>
    <label>Documento</label>
    <nameField>
        <label>Nome do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Documento__c/fields/Comprador__c.field-meta.xml
<CustomField>
    <fullName>Comprador__c</fullName>
    <label>Comprador</label>
    <referenceTo>Comprador__c</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status Aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Entregue</fullName>
            </value>
            <value>
                <fullName>Pendente de Análise</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Vencido</fullName>
                <label>Expirada</label>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentoController.cls
public class DocumentoController {
    @AuraEnabled(cacheable=true)
    public static Map<String, List<Documento__c>> documentosPorCompradorEmOportunidade(Id idOportunidade) {
        Map<String, List<Documento__c>> documentosPorCompradorEmOportunidade = new Map<String, List<Documento__c>>();
        
        List<Comprador__c> compradores = CompradorSelector.obterCompradoresPorOportunidade(idOportunidade);

        for(Comprador__c comprador : compradores) {
            documentosPorCompradorEmOportunidade.put(comprador.Conta__r.Name, DocumentoSelector.obterDocumentosPorComprador(comprador.Id));
        }

        return documentosPorCompradorEmOportunidade;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, List<Documento__c>> documentosPorAnaliseCredito(Id idAnaliseCredito){
        AnaliseDeCredito__c analiseDeCredito = AnaliseCreditoSelector.obterAnaliseCreditoPorId(idAnaliseCredito);
        Map<String, List<Documento__c>> documentos = documentosPorCompradorEmOportunidade(analiseDeCredito.Oportunidade__c);

        return documentos;
    }

    @AuraEnabled
    public static void atualizarStatusDocumento(Map<Id, String> mapStatusPorIdDocumento){
        for(Id idDocumento : mapStatusPorIdDocumento.keySet()) {
            Documento__c documento = DocumentoSelector.obterDocumentoPorId(idDocumento);

            documento.StatusAprovacao__c = mapStatusPorIdDocumento.get(idDocumento);
            update documento;
        }
    }

    @AuraEnabled
    public static void adicionarObservacoesDocumento(Id idDocumento, String observacoes){
        Documento__c documento = DocumentoSelector.obterDocumentoPorId(idDocumento);

        documento.Observacoes__c = observacoes;
        update documento;
    }
}