force-app/main/default/objects/Comprador__c/Comprador__c.object-meta.xml
<CustomObject>
    <label>Comprador</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Comprador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compradores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comprador__c/fields/CompradorPrincipal__c.field-meta.xml
<CustomField>
    <fullName>CompradorPrincipal__c</fullName>
    <label>Comprador principal?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Jurídica (PJ), Pessoa Física (PF), Imobiliária</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CompradorSelector.cls
public class CompradorSelector {
    public static List<Comprador__c> obterCompradoresPorOportunidade(Id idOportunidade) {
        return [SELECT Conta__r.Name FROM Comprador__c WHERE Oportunidade__c = :idOportunidade];
    }
    
    public static List<Comprador__c> obterCompradoresPrincipaisPorOportunidades(Set<Id> setIdOportunidades) {
        return [SELECT Conta__r.Name, Oportunidade__r.Name, CompradorPrincipal__c FROM Comprador__c WHERE Oportunidade__c IN :setIdOportunidades AND CompradorPrincipal__c = 'Sim'];
    }
    
    public static List<Comprador__c> obterCompradorPorIdConta(Id idConta, Id idOportunidade) {
        return [SELECT Conta__r.Name, Oportunidade__c FROM Comprador__c WHERE Conta__c = :idConta AND Oportunidade__c = :idOportunidade];
    }

    public static List<Comprador__c> getCompradorListByOpportunityId(String OppId){
        return [SELECT Id, Name FROM Comprador__c WHERE Oportunidade__c = :OppId];
    }
}