force-app/main/default/objects/Comprador__c/Comprador__c.object-meta.xml
<CustomObject>
    <label>Comprador</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Comprador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compradores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comprador__c/fields/CompradorPrincipal__c.field-meta.xml
<CustomField>
    <fullName>CompradorPrincipal__c</fullName>
    <label>Comprador principal?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Jurídica (PJ), Pessoa Física (PF), Imobiliária</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/PorcentagemDeParticipacao__c.field-meta.xml
<CustomField>
    <fullName>PorcentagemDeParticipacao__c</fullName>
    <label>% de participação</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/TipoParticipante__c.field-meta.xml
<CustomField>
    <fullName>TipoParticipante__c</fullName>
    <label>Tipo de Participante</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprador</fullName>
            </value>
            <value>
                <fullName>Sócio</fullName>
            </value>
            <value>
                <fullName>Fiador</fullName>
            </value>
            <value>
                <fullName>Procurador</fullName>
            </value>
            <value>
                <fullName>Cônjuge/Companheiro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Comprador__c/recordTypes/Comprador.recordType-meta.xml
<RecordType>
    <fullName>Comprador</fullName>
    <active>true</active>
    <label>Comprador</label>
</RecordType>

force-app/main/default/objects/Documento__c/Documento__c.object-meta.xml
<CustomObject>
    <label>Documento</label>
    <nameField>
        <label>Nome do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Documento__c/fields/Comprador__c.field-meta.xml
<CustomField>
    <fullName>Comprador__c</fullName>
    <label>Comprador</label>
    <referenceTo>Comprador__c</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatório?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status Aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Entregue</fullName>
            </value>
            <value>
                <fullName>Pendente de Análise</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Vencido</fullName>
                <label>Expirada</label>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Documento__c/fields/StatusIcone__c.field-meta.xml
<CustomField>
    <fullName>StatusIcone__c</fullName>
    <label>Ícone de status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <label>Tipo do documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identificação</fullName>
            </value>
            <value>
                <fullName>Estado Civil</fullName>
            </value>
            <value>
                <fullName>Residência</fullName>
            </value>
            <value>
                <fullName>Renda</fullName>
            </value>
            <value>
                <fullName>Ficha de Cadastro</fullName>
            </value>
            <value>
                <fullName>Imposto de Renda</fullName>
            </value>
            <value>
                <fullName>CTPS e FGTS</fullName>
            </value>
            <value>
                <fullName>Dependentes</fullName>
            </value>
            <value>
                <fullName>Aplicações Financeiras</fullName>
            </value>
            <value>
                <fullName>Carta de Crédito</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
            <value>
                <fullName>Veículo</fullName>
            </value>
            <value>
                <fullName>Imóvel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Oportunidades.recordType-meta.xml
<RecordType>
    <fullName>Oportunidades</fullName>
    <active>true</active>
    <businessProcess>Processo de Vendas Oportunidade</businessProcess>
    <label>Oportunidades</label>
</RecordType>

force-app/main/default/objects/TipoDocumento__c/TipoDocumento__c.object-meta.xml
<CustomObject>
    <label>Tipo de Documento</label>
    <nameField>
        <label>Nome do Tipo de Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Documento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoDocumento__c/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatório?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CriacaoDocumentosService.cls
public class CriacaoDocumentosService {
    public static void criarDocumentosEmCriacaoDeOportunidade(List<Opportunity> oportunidades) {
    	for (Opportunity oportunidade : oportunidades) {
            Account conta = AccountSelector.obterInfoContaPorId(oportunidade.AccountId);
            Account conjuge = conta.Conjuge__pc != null ? AccountSelector.obterInfoContaPorId(conta.Conjuge__pc) : null;
            Boolean possuiConjuge = conjuge != null;
            Decimal porcentagemDeParticipacao = possuiConjuge ? 50.0 : 100.0;
            String tipoParticipante = conta.RecordType.DeveloperName == 'PessoaFisicaPF' ? 'Comprador' : 'Sócio';

            List<Comprador__c> compradoresSelector = CompradorSelector.obterCompradorPorIdConta(conta.Id, oportunidade.Id);
            Comprador__c comprador = compradoresSelector.isEmpty() ? inserirComprador(conta, oportunidade, true, porcentagemDeParticipacao, tipoParticipante) : compradoresSelector.get(0);

            if(!verificarDocumentosExistentes(comprador.Id)) {
                inserirDocumentos(oportunidade.Id, conta.Id, comprador.Id);
            }

            if (!possuiConjuge) {
                return;
            }

            List<Comprador__c> compradoresConjuge = CompradorSelector.obterCompradorPorIdConta(conjuge.Id, oportunidade.Id);
            Comprador__c compradorConjuge = compradoresConjuge.isEmpty() ? inserirComprador(conjuge, oportunidade, false, 50.0, 'Cônjuge/Companheiro') : compradoresConjuge.get(0);

            if(!verificarDocumentosExistentes(compradorConjuge.Id)) {
                inserirDocumentos(oportunidade.Id, conjuge.Id, compradorConjuge.Id);
            }
        }
    }

    public static void criarDocumentosEmCriacaoComprador(List<Comprador__c> compradores) {
        for(Comprador__c comprador : compradores) {
            if(!verificarDocumentosExistentes(comprador.Id)) {
                inserirDocumentos(comprador.Oportunidade__c, comprador.Conta__c, comprador.Id);
            }
        }
    }

    static Boolean verificarDocumentosExistentes(Id idComprador) {
        List<Documento__c> documentosSelector = DocumentoSelector.obterDocumentosPorComprador(idComprador);
        return !(documentosSelector.isEmpty());
    }

    static void inserirDocumentos(Id idOportunidade, Id idConta, Id idComprador) {
            String resourceNaoEntrege = '/resource/NaoEntregueIconResource';

            List<Documento__c> documentos = new List<Documento__c> {
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'CNH ou CPF',
                        TipoDocumento__c = 'Identificação',
                        Comprador__c = idComprador,
                        Obrigatorio__c = true,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Certidão de casamento',
                        TipoDocumento__c = 'Identificação',
                        Comprador__c = idComprador,
                        Obrigatorio__c = true,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c(
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Comprovante de Residencia',
                        TipoDocumento__c = 'Identificação',
                        Comprador__c = idComprador,
                        Obrigatorio__c = true,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Contrato Social',
                        TipoDocumento__c = 'Identificação',
                        Comprador__c = idComprador,
                        Obrigatorio__c = true,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Documento de Rodar',
                        TipoDocumento__c = 'Veículo',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Vistoria Cautelar',
                        TipoDocumento__c = 'Veículo',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'CND do Detran',
                        TipoDocumento__c = 'Veículo',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Fotos do Veículo',
                        TipoDocumento__c = 'Veículo',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Foto da KM',
                        TipoDocumento__c = 'Veículo',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Valor na Fipe',
                        TipoDocumento__c = 'Veículo',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'DUT',
                        TipoDocumento__c = 'Veículo',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Procuração',
                        TipoDocumento__c = 'Veículo',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Termo de Entrega',
                        TipoDocumento__c = 'Veículo',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Manual',
                        TipoDocumento__c = 'Veículo',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Chave Reserva',
                        TipoDocumento__c = 'Veículo',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Matricula Atualizada',
                        TipoDocumento__c = 'Imóvel',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'CND Condomino',
                        TipoDocumento__c = 'Imóvel',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'CND Prefeitura',
                        TipoDocumento__c = 'Imóvel',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'CND Lixo',
                        TipoDocumento__c = 'Imóvel',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'CND Água/esgoto',
                        TipoDocumento__c = 'Imóvel',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Boleto Energia',
                        TipoDocumento__c = 'Imóvel',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    ),
                    new Documento__c (
                        Oportunidade__c = idOportunidade,
                        Conta__c = idConta,
                        Name = 'Termo de vistoria recebimento',
                        TipoDocumento__c = 'Imóvel',
                        Comprador__c = idComprador,
                        Obrigatorio__c = false,
                        StatusAprovacao__c = 'Não Entregue',
                        StatusIcone__c = resourceNaoEntrege
                    )
                };
                
            insert documentos;
    }

    static Comprador__c inserirComprador(Account conta, Opportunity oportunidade, Boolean isPrincipal, Decimal porcentagemDeParticipacao, String tipoParticipante) {
        Comprador__c comprador = new Comprador__c (
                Conta__c = conta.Id,
                Oportunidade__c = oportunidade.Id,
                CompradorPrincipal__c = isPrincipal ? 'Sim' : 'Não',
                PorcentagemDeParticipacao__c = porcentagemDeParticipacao,
                TipoParticipante__c = tipoParticipante
        );

        insert comprador;
        return comprador;
    }
}