force-app/main/default/objects/Comprador__c/Comprador__c.object-meta.xml
<CustomObject>
    <label>Comprador</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Comprador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compradores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comprador__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Jurídica (PJ), Pessoa Física (PF), Imobiliária</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/TipoParticipante__c.field-meta.xml
<CustomField>
    <fullName>TipoParticipante__c</fullName>
    <label>Tipo de Participante</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprador</fullName>
            </value>
            <value>
                <fullName>Sócio</fullName>
            </value>
            <value>
                <fullName>Fiador</fullName>
            </value>
            <value>
                <fullName>Procurador</fullName>
            </value>
            <value>
                <fullName>Cônjuge/Companheiro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SignatariosService.cls
public with sharing class SignatariosService {
    public static void createSignatariosByOppId(Id oppId){
        List<Signatario__c> signers  = new List<Signatario__c>();
        for(Comprador__c comp : CompradorSelector.obterCompradoresPorOportunidade(oppId)){
            Signatario__c signer = new Signatario__c();
            signer.TipoSignatario__c = comp.TipoParticipante__c; 
            signer.Name = comp.Conta__r.Name; 
            signer.Email__c = comp.Conta__r.PersonEmail;
            signer.Contrato__c = comp.Oportunidade__r.ContractId; 
            signers.add(signer);            
        }
        insert signers;
    }
}