force-app/main/default/objects/Comprador__c/Comprador__c.object-meta.xml
<CustomObject>
    <label>Comprador</label>
    <nameField>
        <displayFormat>CP-{000000000}</displayFormat>
        <label>Comprador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compradores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comprador__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Jurídica (PJ), Pessoa Física (PF), Imobiliária</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Comprador__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Compradores</relationshipLabel>
    <relationshipName>Compradores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Documento__c/Documento__c.object-meta.xml
<CustomObject>
    <label>Documento</label>
    <nameField>
        <label>Nome do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Documento__c/fields/Comprador__c.field-meta.xml
<CustomField>
    <fullName>Comprador__c</fullName>
    <label>Comprador</label>
    <referenceTo>Comprador__c</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Checklist</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/Entregue__c.field-meta.xml
<CustomField>
    <fullName>Entregue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Entregue?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatório?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Checklist</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status Aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Entregue</fullName>
            </value>
            <value>
                <fullName>Pendente de Análise</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Vencido</fullName>
                <label>Expirada</label>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Documento__c/fields/StatusIcone__c.field-meta.xml
<CustomField>
    <fullName>StatusIcone__c</fullName>
    <label>Ícone de status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Documento__c/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <label>Tipo do documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identificação</fullName>
            </value>
            <value>
                <fullName>Estado Civil</fullName>
            </value>
            <value>
                <fullName>Residência</fullName>
            </value>
            <value>
                <fullName>Renda</fullName>
            </value>
            <value>
                <fullName>Ficha de Cadastro</fullName>
            </value>
            <value>
                <fullName>Imposto de Renda</fullName>
            </value>
            <value>
                <fullName>CTPS e FGTS</fullName>
            </value>
            <value>
                <fullName>Dependentes</fullName>
            </value>
            <value>
                <fullName>Aplicações Financeiras</fullName>
            </value>
            <value>
                <fullName>Carta de Crédito</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
            <value>
                <fullName>Veículo</fullName>
            </value>
            <value>
                <fullName>Imóvel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TipoDocumento__c/TipoDocumento__c.object-meta.xml
<CustomObject>
    <label>Tipo de Documento</label>
    <nameField>
        <label>Nome do Tipo de Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Documento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TipoDocumento__c/fields/Obrigatorio__c.field-meta.xml
<CustomField>
    <fullName>Obrigatorio__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Obrigatório?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DocumentoSelector.cls
public class DocumentoSelector {
    @AuraEnabled
    public static Documento__c obterDocumentoPorId(Id idDocumento) {
        return [SELECT StatusAprovacao__c, StatusIcone__c, TipoDocumento__c, Name, Observacoes__c FROM Documento__c WHERE Id = :idDocumento];
    }

    public static List<Documento__c> obterDocumentosPorIds(Set<Id> idsDocumentos) {
        return [SELECT Id, StatusAprovacao__c FROM Documento__c WHERE Id IN :idsDOcumentos];
    }

    public static List<Documento__c> obterDocumentosPorComprador(Id idComprador) {
        return [SELECT Name, Obrigatorio__c, Entregue__c, TipoDocumento__c, StatusAprovacao__c, StatusIcone__c, Conta__c FROM Documento__c WHERE Comprador__c = :idComprador];
    }

    // public static List<Documento__c> obterDocumentosObrigatoriosPorOportunidade(Set<Id> idsOportunidades) {
    //     return [SELECT Name, Entregue__c, TipoDocumento__c, Comprador__r.Oportunidade__c FROM Documento__c WHERE Obrigatorio__c = true AND Comprador__r.Oportunidade__c IN :idsOportunidades];
    // }
}